### ISSUE TITLE
New Wiser App - any breaking changes?

### ISSUE THREAD

**Issue by DrJohnT** [asantaga/wiserHomeAssistantPlatform#100]
Just wondering if this means Wiser have changed the API this integration uses.  Anything we should be aware of?? Any breaking changes?

![New Wiser update - re-order rooms](https://user-images.githubusercontent.com/10464775/80817458-5b9e2680-8bc9-11ea-8718-5797d0d1e412.png)

**Comment by msp1974** [comment]
Not as far as I can see.  Seems they are only adding a small new function to the app itself.  In any case, for them to be able to roll out the app with any new functions/changes to the hub, they would have to have updated the hub some time ago to accommodate.

Mine is working fine - trust yours is too?

**Comment by DrJohnT** [comment]
Oh yes, all seems good!

**Comment by asantaga** [comment]
yeap and mine.. Im currently reviewing and testing marks latest PR
