### ISSUE TITLE
Thermostat Card and Heating Boost

### ISSUE THREAD

**Issue by chris-github1975** [asantaga/wiserHomeAssistantPlatform#101]
I am using the thermostat card in home assistant front end.
The card has a "flame" on it which I presumed was for boosting the heat (Applying the defaults set in the integration). It would be really useful if it was.
When I click the flame, the gauge changes from "20.0 Auto" to "5.0 Heat-Override". If I click the flame again it changes to "5.0 Heat" (Which doesn't seem to do anything)
Is it possible to change the "flame" to boost the heating rather than just put the heating in override mode ?

Hope you can help
Thank You
Chris

**Comment by msp1974** [comment]
Chris, the flame is for manual heating mode.  There will be an updated release soon which will better handle the transition from auto (the calendar), to manual (flame) to off (off thing!), keeping the set temp more in line and changing the test to show whether the room is demanding heat or is idle (current open PR which is awaiting testing).

This functionality is standard for HA climate integrations.

There are 2 ways to boost the heating.

1) Click the 3 dots on the thermostat card and set the boost via the preset option.  This will increase the temp by x degress (x being your personal setting or 2C default) for the duration selected in the drop down.

2) The other option is to use the boost service and assign this to a button in HA to set the room, temp and duration you wish to boost by.

Mark

**Comment by chris-github1975** [comment]
Hi Mark
Thank you for the additional info, I look forward to any Wiser updates as it is my most used integration.
I had got to the stage of using a script to boost various rooms and was just looking at how to "cancel" the boost and resume to Auto. 
I had tried the 3 dots on the card but I get an error....
Failed to call service climate/set_preset_mode. 'WiserHubHandle' object has no attribute 'boost_temp_time'
I'll continue to persevere with the boost service and assign buttons etc.
Thank you
Chris

**Comment by msp1974** [comment]
Chris,

Yes just checked the code and there is a typo. I will issue a PR to angelo tomorrow to fix in current dev branch.

**Comment by asantaga** [comment]
glad I checked this , I was just about to push a release out.

**Comment by msp1974** [comment]
Just sent you PR.

**Comment by asantaga** [comment]
just merged to dev branch.
@chris-github1975  can u please independently test, then I can close this

**Comment by chris-github1975** [comment]
Dev branch seems to work fine. Both the preset service call and the detected i/o errors are gone.

**Comment by msp1974** [comment]
> Hi Mark
> Thank you for the additional info, I look forward to any Wiser updates as it is my most used integration.
> I had got to the stage of using a script to boost various rooms and was just looking at how to "cancel" the boost and resume to Auto.
> I had tried the 3 dots on the card but I get an error....
> Failed to call service climate/set_preset_mode. 'WiserHubHandle' object has no attribute 'boost_temp_time'
> I'll continue to persevere with the boost service and assign buttons etc.
> Thank you
> Chris

Chris,  great good to hear.  I should have also said that the integration cancels any boost setting when you select, auto, manual or off on the thermostat.  Ie if you set a boost and then click the auto (calendar) icon, it will cancel the boost.  Hope this helps.

**Comment by asantaga** [comment]
thanks guys, closing this one

**Comment by msp1974** [comment]
Angelo,  seems this fix did not make it into the 2.3 release.  Should we re-open until it is in current release?
