### ISSUE TITLE
Get code ready for HA inclusion

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#102]
Start reformatting files for HA Style guide. This is a requirement for HA submission

from what I can see

We can 
- issue black against the files
- Check PEP8 using pycharm
- run flake8 against our source.

_LOGGING comments should use the new %s style
e..g 
```_LOGGER.info("Can't connect to the webservice %s at %s", string1, string2)```
Latter looks like a recommendation so I may skip it

**Comment by asantaga** [comment]
__init.py__ done

Weird thing though.. if I use flake8 and fix all the >79 lines then flake8 is clean
but if I issue black against the file it reformats it to >79 characters... weird

**Comment by asantaga** [comment]
just found --line-length parameter
black --line-length=79  seams to do the trick

**Comment by asantaga** [comment]
@msp1974  FYI only

**Comment by asantaga** [comment]
Work happening here now..

Have started re-coding the integration so that it fits HA requirements (and there are lots)

Having trouble getting Homeassistant to recognise the wiser component through config flow when I run it from within a fork of HA, by copying the component into the component directory, it works if I provide YAML config, but not if I try and use the config flow..

Weird..

@msp1974  Have you seen this?

**Comment by asantaga** [comment]
to reproduce
- git clone https://github.com/asantaga/core
- copy custom_components/wiser to core/components/wiser


Run HA and if you try to add a component using the wizard, wiser isnt there..

dont know... Need to do more r&d on this approach

**Comment by asantaga** [comment]
Current Errors

```
ING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asantaga/.cache/pre-commit/patch1590368086.
pyupgrade................................................................Failed
- hook id: pyupgrade
- exit code: 1
- files were modified by this hook

Rewriting homeassistant/components/wiser/switch.py
Rewriting homeassistant/components/wiser/sensor.py
Rewriting homeassistant/components/wiser/climate.py

black....................................................................Failed
- hook id: black
- files were modified by this hook
codespell................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

homeassistant/components/wiser/switch.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:40:71: E231 missing whitespace after ','
homeassistant/components/wiser/switch.py:45:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:103:1: D200 One-line docstring should fit on one line with quotes
homeassistant/components/wiser/switch.py:103:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:116:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:125:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/switch.py:125:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:129:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:133:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:151:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:186:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:195:1: D101 Missing docstring in public class
homeassistant/components/wiser/switch.py:205:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:209:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:230:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/switch.py:230:1: D400 First line should end with a period
homeassistant/components/wiser/switch.py:251:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:273:1: D102 Missing docstring in public method
homeassistant/components/wiser/switch.py:279:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:1:1: D205 1 blank line required between summary line and description
homeassistant/components/wiser/sensor.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:12:1: F401 'homeassistant.const.ATTR_ATTRIBUTION' imported but unused
homeassistant/components/wiser/sensor.py:12:1: F401 'homeassistant.const.ATTR_VOLTAGE' imported but unused
homeassistant/components/wiser/sensor.py:12:1: F401 'homeassistant.const.CONF_ENTITY_NAMESPACE' imported but unused
homeassistant/components/wiser/sensor.py:12:1: F401 'homeassistant.const.STATE_UNKNOWN' imported but unused
homeassistant/components/wiser/sensor.py:22:1: F401 'homeassistant.helpers.icon.icon_for_battery_level' imported but unused
homeassistant/components/wiser/sensor.py:36:1: D401 First line should be in imperative mood; try rephrasing
homeassistant/components/wiser/sensor.py:71:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:83:1: D205 1 blank line required between summary line and description
homeassistant/components/wiser/sensor.py:83:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:83:1: D401 First line should be in imperative mood; try rephrasing
homeassistant/components/wiser/sensor.py:117:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:123:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:138:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:142:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:152:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:154:1: D107 Missing docstring in __init__
homeassistant/components/wiser/sensor.py:201:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:244:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:246:1: D107 Missing docstring in __init__
homeassistant/components/wiser/sensor.py:290:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:328:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:340:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:415:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:417:1: D107 Missing docstring in __init__
homeassistant/components/wiser/sensor.py:438:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/sensor.py:438:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:445:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:460:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/sensor.py:460:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:460:1: D401 First line should be in imperative mood
homeassistant/components/wiser/sensor.py:460:1: D403 First word of the first line should be properly capitalized
homeassistant/components/wiser/sensor.py:476:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:478:1: D107 Missing docstring in __init__
homeassistant/components/wiser/sensor.py:496:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/sensor.py:496:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:500:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:508:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:510:1: D107 Missing docstring in __init__
homeassistant/components/wiser/sensor.py:535:1: D102 Missing docstring in public method
homeassistant/components/wiser/sensor.py:542:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/sensor.py:542:1: D400 First line should end with a period
homeassistant/components/wiser/sensor.py:546:1: D102 Missing docstring in public method
homeassistant/components/wiser/config_flow.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/config_flow.py:25:1: F401 '.const.DATA_WISER_CONFIG' imported but unused
homeassistant/components/wiser/config_flow.py:46:1: D101 Missing docstring in public class
homeassistant/components/wiser/config_flow.py:63:1: D102 Missing docstring in public method
homeassistant/components/wiser/config_flow.py:70:9: E722 do not use bare 'except'
homeassistant/components/wiser/config_flow.py:74:1: D205 1 blank line required between summary line and description
homeassistant/components/wiser/config_flow.py:83:1: D205 1 blank line required between summary line and description
homeassistant/components/wiser/config_flow.py:126:1: D102 Missing docstring in public method
homeassistant/components/wiser/config_flow.py:143:66: E231 missing whitespace after ','
homeassistant/components/wiser/config_flow.py:162:1: D205 1 blank line required between summary line and description
homeassistant/components/wiser/config_flow.py:214:9: E722 do not use bare 'except'
homeassistant/components/wiser/config_flow.py:221:1: D101 Missing docstring in public class
homeassistant/components/wiser/const.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:27:1: F401 'homeassistant.const.ATTR_BATTERY_LEVEL' imported but unused
homeassistant/components/wiser/climate.py:35:1: F401 'homeassistant.helpers.entity.Entity' imported but unused
homeassistant/components/wiser/climate.py:104:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:148:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:160:33: E711 comparison to None should be 'if cond is not None:'
homeassistant/components/wiser/climate.py:169:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:185:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:231:1: D101 Missing docstring in public class
homeassistant/components/wiser/climate.py:252:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:265:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:269:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:284:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:288:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:292:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:296:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:300:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:313:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:324:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:338:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:345:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:376:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:388:13: E722 do not use bare 'except'
homeassistant/components/wiser/climate.py:392:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:439:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:455:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:498:1: D210 No whitespaces allowed surrounding docstring text
homeassistant/components/wiser/climate.py:498:1: D400 First line should end with a period
homeassistant/components/wiser/climate.py:511:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:512:25: E711 comparison to None should be 'if cond is not None:'
homeassistant/components/wiser/climate.py:524:1: D102 Missing docstring in public method
homeassistant/components/wiser/climate.py:538:1: D400 First line should end with a period
homeassistant/components/wiser/util.py:1:1: D400 First line should end with a period
homeassistant/components/wiser/util.py:14:1: D400 First line should end with a period
homeassistant/components/wiser/util.py:14:1: D401 First line should be in imperative mood; try rephrasing
homeassistant/components/wiser/util.py:16:1: W293 blank line contains whitespace
homeassistant/components/wiser/util.py:62:1: D400 First line should end with a period
homeassistant/components/wiser/util.py:62:1: D401 First line should be in imperative mood; try rephrasing
homeassistant/components/wiser/util.py:64:1: W293 blank line contains whitespace

bandit...................................................................Passed
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /home/asantaga/src/ha_dev/venv_wiser/core/homeassistant/components/wiser/switch.py
Fixing /home/asantaga/src/ha_dev/venv_wiser/core/homeassistant/components/wiser/config_flow.py
Fixing /home/asantaga/src/ha_dev/venv_wiser/core/homeassistant/components/wiser/climate.py
Fixing /home/asantaga/src/ha_dev/venv_wiser/core/homeassistant/components/wiser/__init__.py

Check JSON...............................................................Failed
- hook id: check-json
- exit code: 1

homeassistant/components/wiser/strings.json: Failed to json decode (Expecting property name enclosed in double quotes: line 15 column 17 (char 597))

Don't commit to branch...................................................Passed
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

homeassistant/components/wiser/services.yaml
  46:44     error    too many spaces before comma  (commas)
  82:8      error    no new line character at the end of file  (new-line-at-end-of-file)

mypy.....................................................................Passed
gen_requirements_all.....................................................Failed
- hook id: gen_requirements_all
- exit code: 1

******* ERROR
Errors while importing:  homeassistant.components.wiser[Please pin requirement wiser-heating-api>=1.0.8, see https://developers.home-assistant.io/docs/creating_platform_code_review.html#1-requirements]

hassfest.................................................................Failed
- hook id: hassfest
- exit code: 1
```

**Comment by msp1974** [comment]
I did see this when first doing the config flow and i spent ages trying to work it out and then cleared the browser cache and it appeared. However, i think this is fixed in 110 as i didnt have to do this when adding config flow to my Jag custom component.

I have however learnt quite a bit about doing a config flow for the Jag component and was thinking last night that it should have a bit of a rewrite in the wiser component to make a lot neater and simpler.  I used the Tado component as a really good guide.

Happy to have a look later today or tomorrow for you.

**Comment by msp1974** [comment]
Sorry, also just realised what you are saying above of copying in to the components directory... should learn to read.

If you look in the generated directory there is a config flows file that it needs to be listed in. There are some scripts you have to run to include it in a couple of files. Cant remember what they are but will google and post link here.

**Comment by msp1974** [comment]
Once you have updated your manifest and created the config_flow.py, you will need to run python3 -m script.hassfest (one time only) for Home Assistant to activate the config entry for your integration.

https://developers.home-assistant.io/docs/config_entries_config_flow_handler

**Comment by asantaga** [comment]
code getting there.. using new repository https://github.com/asantaga/homeassistant-core-wiserintegration/tree/WiserIntegrationInitial for published wiser.. as this appears to be the right thing to do..


Currently getting clean commits

```
(venv) asantaga@pluto:~/src/ha_dev/venv_wiser/homeassistant_publishing/core/homeassistant/components/wiser$ git commit -m "Loads of changes" -a
pyupgrade................................................................Passed
black....................................................................Passed
codespell................................................................Passed
flake8...................................................................Passed
bandit...................................................................Passed
isort....................................................................Passed
Check JSON...............................................................Passed
Don't commit to branch...................................................Passed
yamllint.................................................................Passed
mypy.....................................................................Passed
gen_requirements_all.....................................................Passed
hassfest.................................................................Passed
[WiserIntegrationInitial 56372d642e] Loads of changes
 18 files changed, 2487 insertions(+), 1 deletion(-)
```


@msp1974 : One of the issues Ive seen is that you used bare excepts in some places. I was able to figure out the right excepts for most except the one in ```config_flow.py``` in the async_step_import.
For now Ive commented the exception handler out to try and force the error(s).. any idea which ones I should be trapping?

**Comment by msp1974** [comment]
Its really only the same errors as in the user step code, just the returns from testing the connection to the hub. If there is a config error in config.yaml, this is handled by HA anyway.

As i said, this may benefit from a rewrite as it does a slightly hooky thing for the options as you cannot set options when creating/importing config. I didnt know how to do this properly when i wrote this and it actually does this the other way round of copying option changes to data. You have to set them in the data config and then copy to options once created.  The Tado code is a really good example of how to do this. Look between init.py and config flow.py.  first setup function is only if you have entry in config.yaml, setup_entry is when it is using config entry (once created via adding in UI or importing). Ie setup function calls config flow import routine and then runs setup entry. There are also functions in init.py to unload (when deleting in UI without needing reboot) and the listener function which is called when changing options. In Tado is calls a reload of component which also calls unload function and then setup entry again.

I have also learnt that there is a more simple way to handle if cannot connect to the hub on loading/adding to HA tha  the retry function i have used by raising a component not ready exception which already has a retry capability and again simplifies code greatly.

You will also see in Tado that import step just calls the user step and simplifies/ reduces duplicate code in import step.

Let me know if you want me to look at tidying this up.

Happy to update this if you want during next week. Which repo are you doing this in as could not see in your HA fork.

**Comment by msp1974** [comment]
Strike the question about the repo, think i may need glasses. Can see it there!

**Comment by asantaga** [comment]
Hey Mark, 
OK, lets rewrite it.  I've actually "cloned" the new code in this repo (wiserHomeAssistantPlatform) in the branch ```prepForPublishing``` . The branch appears to work fine, so I'll merge this back into ```dev``` so others can easily test..

**Comment by asantaga** [comment]
Done, changes merged code into dev. Use this repo as the basis..

on a side note, the way of developing for HA appears to have changed from venvs and installing HA to cloning the main repo and using devcontainers or other... 

Im trying to work out how to dev these components and still have different repositories on github

**Comment by msp1974** [comment]
Angelo,

Have had some time this weekend to simplify and tidy up config flow.  Have tested and think it works and handles errors well.

Also found a minor bug when cancelling boost if in manual mode - so fixed it.

I seemed to have issues with black whereby if I set to line length 79 then when doing a git commit it set back to 88.  I have left @ 88 for now but not sure what it should be as using the pre-commit scripts in core fork.  Let me know if I have messed this up - it is passing all format tests defined in core.

**Comment by asantaga** [comment]
Nice,

I wasnt able to look at it last night, but will tonight..  

I saw you issued the PR against the /homeassistant-core-wiserintegration repo - good..

I need to check with the HA Developers to find out whats the right way to do these extensions with ha directly.. Its weird that you have to clone the entire  repo.. What about if I have multiple extensions? What Ive done is renamed the repo, but is that right? so many questions. .. 

I still like the HACS approach.. much cleaner and easier.

**Comment by asantaga** [comment]
Nearly there,

Done initial docs using https://github.com/asantaga/home-assistant.io-wiserintegration repo. 
tox tests fail for main code repo (https://github.com/asantaga/homeassistant-core-wiserintegration) but I dont know why... Looking into this later (gotta take the boy to the park)

Other considerations

- Do we rename the domain of the new integration in the other repo? this means we dont have issues when we switch over from HACS to native HA?
- I am considering freezing this repository and moving all conversations to the other repo? Once we publish to HA natively it wont be possible to have HACS and HA working together  (unless we have multiple domains) and I dont think its worth it.

comments?

**Comment by asantaga** [comment]
submitted both the docs and code tonight

- https://github.com/home-assistant/core/pull/36805
- https://github.com/home-assistant/home-assistant.io/pull/13758

Still more to do :-(

**Comment by asantaga** [comment]
@msp1974 Hey Mark, given I made you a co-author in the HA submission I need you to sign the CLA..

Can you checkout the PR in HA, https://github.com/home-assistant/core/pull/36805

**Comment by msp1974** [comment]
Signed it. Do you need some help on this.

**Comment by msp1974** [comment]
@asantaga  hopefully you will see that I put a bit of time into this tonight to justify my collaborator status! ;-)

Have addressed most of the items raised by Frenck (except the reduce capability points).  Also did some learning on tox testing and amended the tests so that they should work fine now.  Passed on my machine.

I'll let you go back to Frenck re not reducing functionality.

KR Mark

**Comment by asantaga** [comment]
Thanks

I'm off this week but the wife had me painting ..... sigh

**Comment by asantaga** [comment]
Will revert to them for the others

**Comment by scooper1** [comment]
minor comment on the new beta
when heating is set to off the target seems to be changed to null instead of last value
for most displays, this would be better  to just so the last or a dummy value  (dummy value could be the frost protection level)

**Comment by asantaga** [comment]
Closing off, probably not going to do this
