### ISSUE TITLE
109.4 update causes wiserheatingapi to get deleted

### ISSUE THREAD

**Issue by scooper1** [asantaga/wiserHomeAssistantPlatform#105]
wiser api still being deleted and needing reinstall after update to 109.4
this is still happening after the comma fix

**Comment by asantaga** [comment]
I have no idea.. It works perfectly on my instance and Adam on https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/117 says it now works fine (after the comma fix)...


I'll create a clean virtual environment and test it out tomorrow...  So from memory, you need to log using portainer (so your using docker) and manually pip install the library  right?

**Comment by scooper1** [comment]
yes normal docker install 
i have send this behaviour both machines I have access to 
no other libraries (not checked that there are libraries)   that are  installed via hacs have this problems - i don't know how libraries are handled during a update but really would not expect them to get deleted unless the complete docker image is being replaced  ?

**Comment by msp1974** [comment]
Not seeing either. Just updated to 109.4 and all was fine.

**Comment by chris-github1975** [comment]
I have the latest HA, HACS, and Wiser and have no errors. I'm running it all on a VMware guest.

Chris

________________________________

**Comment by scooper1** [comment]
Maybe just a interaction on my systems 
Any idea what would cause library to get deleted  during a supervisor update ?

**Comment by asantaga** [comment]
I have no idea.,.  Im assuming your using the official (if it thats what we call it) home assistant docker image from docker hub right?

If so then perhaps delete the container, any assigned volumes and then recreate the container.. That said when u upgrade the container would be blitzed anyway..

**Comment by scooper1** [comment]
yes using official image
I accept that problem is something strange on my systems 
just trying to understand how it happens to be able to fix it
just happened again on 109.5 update

**Comment by asantaga** [comment]
lets sync up again in a couple of days, happy to hold a zoom with you and help debug this.. im very curious to why this is happening..

**Comment by scooper1** [comment]
Ok I would be up for that. 
Normally use discord but I try to get zoom account
Thanks

**Comment by scooper1** [comment]
should the  config\deps   folder contain a copy of the wiserheatingapi    or a link 
mine is empty 
documentation implies  that this contains a copy of any dependencies required after docker container restart - this may just be out of date info

**Comment by msp1974** [comment]
Only thing i can think of worth looking at is

[https://community.home-assistant.io/t/ha-0-103-0-update-broke-hacs-requirements-for-hacs-not-found-aiofiles-0-4-0/154896/9
](https://community.home-assistant.io/t/ha-0-103-0-update-broke-hacs-requirements-for-hacs-not-found-aiofiles-0-4-0/154896/9
)

I don't know if your other HACs integrations need to download any dependancies.

Other people on various similar issues have suggested taking a snapshot, delete and reinstall docker env and then restore shapshot. Never done this so dont know how much it does or does not keep...on you!

**Comment by asantaga** [comment]
Hey @scooper1 , I have a zoom account,  so zoom isnt a problem..

Not sure you need to create a snapshot of the docker env. If you configured it correctly all your config is mapped to a volume on your filesystem.. (ie the -v flag)

You should be able to delete the docker container, delete the image (just in case) and then recreate the container.. thats the beauty of docker

**Comment by asantaga** [comment]
oh, and yeah I would definitively also delete the wiser directory in custom_components

**Comment by scooper1** [comment]
the docker container appears to be recreated on each upgrade
it appears to me that hacs does a scan of the manifest files and reinstalls the requirements 
but on my system the  it misses the wiserheatingapi 
so I have deleted the wiser custom components and then  reinstalled via hacs then done the 109.6 upgrade that deletes the hassioassistant container and recreates it 
still same problem I had to pull wiserheatingapi manually

**Comment by asantaga** [comment]
Sorry bank holiday got me.. 

i have no clue..

Can we try one more thing..

Can you create a "NEW" HA container, pointing to a new config directory, ie a different -v mapping..

Lets see if it happens there too, if it works then there is something with the HA config we need de-debug,.

**Comment by scooper1** [comment]
I am not sure how to do a new container 
but turn on debugging for hacs 
uninstall  wiser restarted and then installed wiser restarted 
at no point did I get any debug messages about installing the wiserheatingapi 
tried a few other like breaking changes - still did not see any checking for requirements
thinking that my hacs is broken from the data I have in the config directory

**Comment by asantaga** [comment]
Hey, let me know when we can do a zoom and I'll have a nose.. I do think somethings wrong with HA but worth being sure. Ping me an email , see any of the files, and we'll sort this out offline

**Comment by scooper1** [comment]
the problem maybe because I have a growing  ha  system  and its tripped this problem
on update 
https://community.home-assistant.io/t/ha-0-103-0-update-broke-hacs-requirements-for-hacs-not-found-aiofiles-0-4-0/154896

**Comment by scooper1** [comment]
cant find a private email account
I set up a temporary  test user that you should be able to see my ha server via duckdns address - but I only want to send login details to private email address - not this public platform

**Comment by scooper1** [comment]
this problem seems to fixed in 1.10b0
beta installed without needing to pull wiserheatingapi
did notice some new log entries
2020-05-14 01:56:07 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify WiserSwitch to extend SwitchEntity
2020-05-14 01:56:07 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify WiserSmartPlug to extend SwitchEntity
2020-05-14 01:56:07 WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify WiserRoom to extend ClimateEntity

**Comment by msp1974** [comment]
Have been made aware of this on my jag integration. However, these new entity types are only available in v0.110 onwards which seems a little premature to give depreciation warnings in the logs. We will need to work out how we deploy these changes as people who have not upgraded to v0.110 will not be able to use it.

**Comment by msp1974** [comment]
Probably a good reason to get this into the main repo which we keep stopping Angelo doing with requests for fixes/upgrades. Me included! ;-)

**Comment by asantaga** [comment]
Joy!!! I'll push a new version out now to fix https://github.com/asantaga/wiserHomeAssistantPlatform/issues/95 and then look at this after

**Comment by asantaga** [comment]
closing this one, opening new issue
