### ISSUE TITLE
Homebridge Integration

### ISSUE THREAD

**Issue by charlesomer** [asantaga/wiserHomeAssistantPlatform#107]
Hi,

Looking at trying to get Wiser to work with HomeKit, I don’t suppose a homebridge version has been considered?

Thank you
Charles

**Comment by asantaga** [comment]
not directly, the integration works with Home Assistant and that in turn integrates with Alexa, HomeKit etc

Ive not tried it but checkout this HA component
https://www.home-assistant.io/integrations/homekit/

We have no intention to do native integration with Homegoogle, google or aws.
