### ISSUE TITLE
battery_level inconsistency

### ISSUE THREAD

**Issue by phixion** [asantaga/wiserHomeAssistantPlatform#108]
I was working on a template sensor/alert/automation for all my devices with batteries in HA. I'm reading a couple of domains battery_level's, but wiser returns strings rather than battery percentage. 

Question: wouldnt it make sense to move battery_percent to battery_level and the current battery_level (the string-foo from wiser) to something new (or even get rid of it?!) It would be more consistent within the HA domains and its commonly used that way

**Comment by mrvladis** [comment]
I personally just grabbed them within the NodeRed and used it to send out an email.

**Comment by asantaga** [comment]
@phixion So the issue is the name or just that its a string?

**Comment by phixion** [comment]
It's a non-issue by the way, I dont think the HA guys have any prefrence on what battery_level has to return.
the problem is that they call it "TwoThirds" and not 66 (percent) while most other integrations return a percentage for battery_level.  Im trying to get rid of countless single sensors and have a more universal approach, to remove clutter and make it easier to read.

```
- platform: template
  sensors:
    low_battery:
      friendly_name: "Low Battery"
      value_template: >
        {%- set threshold = 20 -%}
        {%- set domains = ['device', 'switch','climate'] -%}
        {%- for domain in domains -%}
        {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
            {{ item.attributes.friendly_name }}{%- if not loop.last %}, {% endif -%}
        {%- endfor -%}
        {%- endfor -%}
```

**Comment by msp1974** [comment]
@phixion I think maybe some of the issue you are seeing is that you are using the battery info on the device sensor and not the battery level on the battery sensors which should work better.

**Comment by msp1974** [comment]
@phixion to help you with this, I think the below value template should work.  Also just lists the room names by replacing "Wiser iTRV-" and " Battery Level".

```
{%- set threshold = 20 -%}
{%- for item in states.sensor %}
  {%- if ("Battery" in item.name)  and (item.state | int <= threshold) %}
    {{-item.name | replace(" Battery Level","") | replace("Wiser iTRV-","")}}
    {%- if not loop.last %}, {% endif %}
  {%- endif %}
{%- endfor %}
```

**Comment by phixion** [comment]
sorry for the late reply! This looks promising @msp1974 

> @phixion I think maybe some of the issue you are seeing is that you are using the battery info on the device sensor and not the battery level on the battery sensors which should work better.

Reason being to have a universal solution for all (phones, remotes, esps, laptops, you name it) devices and not single solutions. It removes clutter and improves readabilty. Usually (and this is just my impression) devices report their battery percentage via battery_level the attribute. I dont know if theres any guidelines by HA how battery_level has to be reported (integer/1-100/none) but the idea was to follow that 'rule' so everyones life is easier (except Angelos ofc  :)).

I'm not a programmer, so how come we have 2 sorts of representing the state of the battery anyway? Is the wiser api returning the weird values (onethrird etc) and this integration is calculating a percentage out of it?

**Comment by msp1974** [comment]
The wiser hub provides the one third, 2 thirds etc and a battery voltage.

The integration is using the battery voltage with info from wiser that Angelo got to calculate the % as the effective remaining useable %. The voltage and % are different for a trv and a thermostat due to the power needed to drive the motor.

The original version had thus battery data in the device sensor and we added the battery sensor later, initially removing the data from the device sensor. However, people were already using in automation so we put it back. Probably need to really depreciate the battery info on the device sensor after giving people time to migrate to the better battery sensor.

**Comment by msp1974** [comment]
Also worth pointing out that the battery sesnor is the more standard way to do this in HA and is a core part of the development functionality. Certainly for most integrations, phones etc (and even EV cars) they are providing this battery sesnor with dynamic icons to show battery level visually as well as a % state as the battery sesnor in this integration does.

**Comment by phixion** [comment]
Okay this makes sense, excuse the noise
