### ISSUE TITLE
Implement Remaining Boost Duration

### ISSUE THREAD

**Issue by nofuse1971** [asantaga/wiserHomeAssistantPlatform#112]
Can you please implement the remaining boost duration feature

**Comment by asantaga** [comment]
related : logged https://github.com/asantaga/wiserHomeAssistantPlatform/issues/113 for the outputstate

**Comment by asantaga** [comment]
nofuse1971 , checkout https://github.com/asantaga/wiserHomeAssistantPlatform/issues/114

**Comment by msp1974** [comment]
I can see what you're asking here.  On the wiserhub when a room is boosted, it reports an "OverrideTimeoutUnixTime": 1603980480.  Coupling this with the hubs Unix time - "UnixTime": 1603976880 you can determine the remaining boost duration.

I think exposing this is pretty straight forward (although json tag doesn't exist if not boosted), however not sure we can easily display this.  I also know that having it as some sort of countdown is very challenging (tried something similar before with a countdown timer from Alexa) as the UI only updates the values when there is an actual update to sensor values - which is only being read every x minutes as determined by your config.

I'll have a think about it and discuss with Angelo.  We have both been very busy lately (his probably a better excuse! :-) )

**Comment by nofuse1971** [comment]
I know it must be possible because the feature existed in OpenHAB when I use to use that before HA.

I’ve sort of come up with a work around at the moment....I’ve created timers and scripts that once I start a boost it starts a countdown timer that is shown on my homepage

**Comment by msp1974** [comment]
Ok been working on this.  I will add an attribute to the climate sensor that will show the boost end timestamp if the room is boosted.  

Is this the sort of thing you are after or are you looking for the integration to give some sort of count down.  I can easily give you an attribute with remaining time in minutes but as said previously, this will only update on the basis of the scan interval you have set.  So if this is 5 mins, then it will only change every 5 mins not every min.

**Comment by nofuse1971** [comment]
Whatever is easier. I think the end timestamp would work ok.

Thanks

**Comment by msp1974** [comment]
Released v2.4beta2 (you need to enable beta versions in HACS) with boost_end as a timestamp and boost_remaining in minutes attributes on a climate sensor.  Feedback welcome.

**Comment by msp1974** [comment]
@nofuse1971 are you ok with the changes made.  Does it do what you want?

**Comment by nofuse1971** [comment]
Hi, installed on Sunday night and it seems to be working fine.

Yes I am happy that it does what I requested.

Great work keep it going!!
