### ISSUE TITLE
Understanding Wiser Valve Protection

### ISSUE THREAD

**Issue by tombadog99** [asantaga/wiserHomeAssistantPlatform#115]
Apologies in advance for posting this as an issue as I'm just after some clarification.
What is the expected behaviour of the wiser valve protection switch. Does it refer to valve protection being on as a whole or does it only come on at the moment where the Wiser system is carrying out the action of valve protection (ie opening/closing valves)

**Comment by asantaga** [comment]
From what I know it simply tells the wiser system to activate the valve protection feature.  FWIK this means once a week or so, it opens and closes the valves so that they dont sieze.

@msp1974  any other info?

**Comment by tombadog99** [comment]
I was only curious because it was off by default and it isn't something you can turn on through the 1st party Drayton Wiser app so I assume it switches itself on once a week as you describe?

**Comment by asantaga** [comment]
@tombadog99 , unless we approach Wiser I dont think we'll ever know.. I know Wiser are aware of this integration and are "passively" allowing it.. 

I'll close this for now, but do some background R&D

**Comment by tombadog99** [comment]
> @tombadog99 , unless we approach Wiser I dont think we'll ever know.. I know Wiser are aware of this integration and are "passively" allowing it..
> 
> I'll close this for now, but do some background R&D

Perfect, makes sense.

**Comment by LewisSpring** [comment]
Hi @asantaga 
Sorry to bump to thread, but did you ever find anything out about the valve protection in your "background R&D"?
I'm interested in using it as I leave some valves to sit at one temperature for long amounts of time, so would be good to have them automatically exercised every once in a while.

**Comment by asantaga** [comment]
Hey, sorry I did find out from my plumber (who likes tado oh well :-) )that valve protection is a GOOD GOOD thing.  From what I know the wiser trvs do the valve protection by themselves, but if you want you do do a manual  "valve protection" by raising the temperature to 20 something, then close the valve then back to scheduled.. The only issue is the boiler may (will) activate for a short period of time.. 

The manuals say the valves do it themselves every 14 days.

**Comment by LewisSpring** [comment]
> Hey, sorry I did find out from my plumber (who likes tado oh well :-) )that valve protection is a GOOD GOOD thing. From what I know the wiser trvs do the valve protection by themselves, but if you want you do do a manual "valve protection" by raising the temperature to 20 something, then close the valve then back to scheduled.. The only issue is the boiler may (will) activate for a short period of time..
> 
> The manuals say the valves do it themselves every 14 days.

Thank you!
That's good news. I must have missed it in the manual, I did look.
Do you know what the switch exposed in HASS does, considering that they do it themselves?
