### ISSUE TITLE
TRV Control

### ISSUE THREAD

**Issue by bloddy** [asantaga/wiserHomeAssistantPlatform#116]
Hi there, sorry for opening this as a bug, do you have any method to control the TRV directly from the home assistant ? I'm asking this because, I have temperature sensors in every room with good precision that are reporting to hass instalation via node-red. 

As an ideea I would like to control the TRV based on my needs..

Thank you.

**Comment by mrvladis** [comment]
Hi,
I didn't personally try to control TRV through the current integration, but I can see that they are exposed into NodeRed from HomeAssistant.
I have tried to use Xiaomi Temperature sensors to correct the TRV "calculated" temperature and have used NodeRed directly integrated with the Wiser. 

In a few weeks - I gave up and just bought Wireless Thermostats for each room.

The problem that you'll have is inability to use any of the algorithms Wiser has to calculate for how long heating need to be On to compensate for the  temperature difference. So I was always getting overheated rooms.

Keep in mind, that you radiators have heat capacity. It wouldn't be enough just to turn the heating off, when you've reached the desired temperature. They will still keep warming the room.

Hope that helps.

**Comment by bloddy** [comment]
Hi, thx for the reply,

Yes I know about, that I already have PID worked around for my heat now ... I've gone calculating with the outside temperature getting the delta  and increasing the flow + temperature and it's working great, but now I want to go full on the per zone/room.  The idea is that if you can control every TRV, you control the temperature, the PID is a learning curve base on the outside temp. that's how they calculate for more precise heating..  At me it's easier.

The idea is simple can I control by issuing a comand/state to close the TRV ? That's it's my biggest question, and more exactly what part except the TRV is needed.. 

Thank you again.

**Comment by scooper1** [comment]
i would just use a heat mode and set to 10c when you want off and 30c when you want on

**Comment by asantaga** [comment]
I agree with scooper1 , @bloddy  is this acceptable?

**Comment by msp1974** [comment]
Closing as stale.
