### ISSUE TITLE
Window_State shows as null

### ISSUE THREAD

**Issue by rpeach92** [asantaga/wiserHomeAssistantPlatform#118]
![DE255E06-75E8-4B57-8BDE-BF392CED4D03](https://user-images.githubusercontent.com/67243688/95693520-be89f400-0c24-11eb-9649-5d611e47b6bf.jpeg)

Hi,

Not sure why this is happening or if it can be fixed, I have the window open sensor active but the state for window is fixed at null

**Comment by asantaga** [comment]
I'll check the code later... Im not 100% sure if we expose the window state (never looked for it to be honest)

**Comment by rpeach92** [comment]
> I'll check the code later... Im not 100% sure if we expose the window state (never looked for it to be honest)

**Comment by rpeach92** [comment]
It doesn’t appear to work properly anyway in the app itself because I was in my garden yesterday for a few hours and the radiator near my back door has the iTRV installed and the heating still came on with the back door wide open

**Comment by msp1974** [comment]
Had a look at this issue and the climate sensor is certainly picking this up correctly.  What I would say is that the wiser hub only provides this for iTRVs.  Any room that is controlled by a RoomStat does not actually have this parameter supplied by the hub.  Is the room in your screenshot a TRV or Roomstat?

**Comment by rpeach92** [comment]
Have ever had it actually work? I have a itrv by my back door and I had the door open for over 20 minutes last weekend and the heating stayed on! I was thinking it was an issue with the integration but it turns out it’s the hub or iTRV, tried wiping it off the system and re-pairing and it hasn’t helped, currently in talks with wiser about it. Good to know the window state is reported correctly though 🙂

**Comment by msp1974** [comment]
Never used it so don't know.  Will try at some point soon.  Please report back on your progress/conversations with Wiser.

**Comment by rpeach92** [comment]
The latest update:

Hello Richard,

Many thanks for your query. Currently, our open window detection is not working correctly. We are looking to fix it in the near future. In the mean time, could you disable it in the app. Thanks in advance.
Regards

Advance Technical Support Team - Drayton Controls

**Comment by asantaga** [comment]
Thanks Richard,

Nothing we can do about this until they fix it... We can leave this issue open so people know this doesnt work.

**Comment by rpeach92** [comment]
I had my first open window action just recently! I’m not sure if something has changed in the firmware but it triggered this state:
![1499B021-8890-4AF0-92DA-687EBEEFAB99](https://user-images.githubusercontent.com/67243688/100399774-f8378280-304b-11eb-8510-e953da4dc1b9.png)

**Comment by msp1974** [comment]
Looks like Wiser may have fixed this.  My hub has updated to v3.0.4 recently.  Presume yours has too.  Glad to hear its now working.

**Comment by rpeach92** [comment]
> Looks like Wiser may have fixed this. My hub has updated to v3.0.4 recently. Presume yours has too. Glad to hear its now working.

It only appears to be working on my kitchen itrv which reports an attribute state of either ‘Open’ or ‘Closed’, the rest of my house the itrv’s are still reporting ‘null’ and they are on the same firmware as the kitchen itrv too.

**Comment by msp1974** [comment]
OK, so we'll put that down to a partial fix for now! :-)

**Comment by rpeach92** [comment]
> OK, so we'll put that down to a partial fix for now! :-)

I have emailed support, it might be a simple case of re-paring the itrvs back to the system... hopefully!

**Comment by rpeach92** [comment]
No reply from support..

But if you restart everything including your hassio and heathub I now have the state applied correctly to the additional itrvs
![116694AC-1423-436E-AC71-718BD11F585D](https://user-images.githubusercontent.com/67243688/100538951-c6c8dd80-322a-11eb-8a2b-f43cf017398e.png)

**Comment by msp1974** [comment]
Ah, the old switch it off and back on again. Glad to hear it is now working.Sent from my Galaxy
