### ISSUE TITLE
Does the integration give up trying to contact the wiser hub?

### ISSUE THREAD

**Issue by dangel666** [asantaga/wiserHomeAssistantPlatform#122]
Had a problem with power today and this knocked out my PI4 which runs HASSIO and of course the wiser control panel too.  Noticed all my entities were stuck in 'restored' stage and my lovelace cards for my TRVs dead too.    My logs seemed to show HA gave up trying to contact the wiser hub (I've got a fixed IP) but it was running (schedules running and control fine via the android wiser app).

I power cycled the wiser CP, waiting and rebooted HASSIO - all is now well..

If the wiser CP goes offline would I always need a reboot of HA to pick it up again or is there a way of asking the integration to hang on in there, don't give up buddy it'll be back?

**Comment by scooper1** [comment]
A lot of effort  has been put in to stop this behavior
this problem only happens during reboot  

 hassio now has the ability to reload integrations on the integration page but it's not enabled on the wiser  - maybe as simple as registering a callback?
 
I not checked but suspect there would be a service call to reload integration via hassio engine

i could then do a bit of node-red to trigger a reload

**Comment by msp1974** [comment]
@scooper.  As far as I know you can reload the wiser integration.  Is there something I am missing that you see/don't see happening?

@dangel666 I think there maybe a small bug in the code that if it gets a 4xx return code from the api call, it does not try to connect later.  It is supposed to do this but I think it never gets to this part of the code.

Agree with @scooper1 that this is only an issue on hassio load if it cannot reach the wiser hub (situation you clearly had with a power cut).

Will leave this issue open to fix the bug and ensure it doesn't create another issue by doing so.

Note to self - line 107 in init.py is never reached as function returns false on line 106.  Should raise ConfigEntryNotReady error to allow retry.

**Comment by scooper1** [comment]
My bad.  I sure the reload option was not there maybe a beta issueI try it next time I have the startup issue On 28 Oct 2020 18:58, Mark Parker <notifications@github.com> wrote:
@scooper.  As far as I know you can reload the wiser integration.  Is there something I am missing that you see/don't see happening?
@dangel666 I think there maybe a small bug in the code that if it gets a 4xx return code from the api call, it does not try to connect later.  It is supposed to do this but I think it never gets to this part of the code.
Agree with @scooper1 that this is only an issue on hassio load if it cannot reach the wiser hub (situation you clearly had with a power cut).
Will leave this issue open to fix the bug and ensure it doesn't create another issue by doing so.
Note to self - line 107 in init.py is never reached as function returns false on line 106.  Should raise ConfigEntryNotReady error to allow retry.

**Comment by dangel666** [comment]
Ah, thanks so much for the responses - this makes some sense.  I'm due to have some power issues tomorrow (power meter is being replaced) so I'll fiddle a bit more if it reoccurs (and check if i can reload the int).   I realised after the fact that i should of grabbed the logs in front of me (so much for being in Software for 30+ years..) doh.

**Comment by scooper1** [comment]
um the reload option is not available  if the wiser integration  does not start at startup   ... duh

**Comment by dangel666** [comment]
> um the reload option is not available if the wiser integration does not start at startup ... duh

Not sure if this directed at me?   In my case it did load, it didn't connect.

**Comment by scooper1** [comment]
I meant to comment that if the integration does not connect at startup of hassio. Hassio in this case can not be asked to restart the intregration.  Other intregrations appear to be able to be restarted without restarting the whole of hassio.  I  guessing that wiser intregration is not failing into restartable manor during failed connection at startupOn 30 Oct 2020 07:59, dangel666 <notifications@github.com> wrote:

um the reload option is not available if the wiser integration does not start at startup ... duh

Not sure if this directed at me?   In my case it did load, it didn't connect.

**Comment by msp1974** [comment]
Yes this is correct. What is happening is that during load of the integration it is failing to connect and just stopping.The bit in my comment about raising a not ready exception is that Hassio will wait and try again later to load it.  Thus theory is that wiser hub will be up and running when it retires later.  You see this on integrations in log saying not ready, returning in 30 seconds etc.If the integration didn't load in the first place it cannot be reloaded. Which is what we have here.Sent from my Samsung Galaxy smartphone.

**Comment by scooper1** [comment]
But it can road later as hub has been reset but it does not  you have to reset hub and hassio On 30 Oct 2020 14:58, Mark Parker <notifications@github.com> wrote:



Yes this is correct. What is happening is that during load of the integration it is failing to connect and just stopping.The bit in my comment about raising a not ready exception is that Hassio will wait and try again later to load it.  Thus theory is that wiser hub will be up and running when it retires later.  You see this on integrations in log saying not ready, returning in 30 seconds etc.If the integration didn't load in the first place it cannot be reloaded. Which is what we have here.Sent from my Samsung Galaxy smartphone.

**Comment by msp1974** [comment]
Have issued a v2.4beta2 release that will fix this issue.  Please report back if you find scenarios that this is not working.
