### ISSUE TITLE
Add Boiler Percentage Demand in Climate

### ISSUE THREAD

**Issue by v966732** [asantaga/wiserHomeAssistantPlatform#13]
I would like to request that Boiler Percentage Demand is added as one of the available stats in the Climate element. I was using an OpenHAB Wiser component and it had percentage demand as an option. 

 I have had a play with it and identified the string that is needed:-

return self.handler.getHubData().getRoom(self.roomId).get("PercentageDemand")

Thank-you

**Comment by asantaga** [comment]
Np will add!

I did this calc using guarana and influxes but given it's a easy ER I'll
add it to the base.

**Comment by asantaga** [comment]
Hey v966732

Done a lot here.

Ive added PCT_Demand to each room as a custom attribute AND at the heating state level. I noticed that he heating state is an array (because drayton sell it with 1-2-3 channels) so Ive modified this accordingly..

Please test and let me know.

easiest way to test is to simply clone the entire branch into your custom_components directory (I changed a number of files)

Let me know if it all works and I'll merge it to master (probably up the version to 1.2)

**Comment by v966732** [comment]
Hi,

Thank-you for all your work on this.

I downloaded the new code and tested it, the percentage demand worked straight away but current temperature and target/set temperature both disappeared from the climate component.  I fiddled about with it and if I added target_temperature and current_temperature into the # Generic attributes section then I could read the values again.  I'm not sure why this would be the case given that this is a climate component.

The amended Generic attributes section is as follows:-

#    https://github.com/asantaga/wiserHomeAssistantPlatform/issues/13
    @property
    def state_attributes(self):
        # Generic attributes
        attrs={}
        attrs['percentage_demand'] = self.handler.getHubData().getRoom(self.roomId).get("PercentageDemand")
        attrs['heating_rate'] = self.handler.getHubData().getRoom(self.roomId).get("HeatingRate")
        attrs['window_state'] = self.handler.getHubData().getRoom(self.roomId).get("WindowState")
        attrs['window_detection_active']= self.handler.getHubData().getRoom(self.roomId).get("WindowDetectionActive")
        attrs['away_mode_supressed']= self.handler.getHubData().getRoom(self.roomId).get("AwayModeSuppressed")
        attrs['target_temperature']= self.handler.getHubData().getRoom(self.roomId).get("CurrentSetPoint")/10
        attrs['current_temperature']= self.handler.getHubData().getRoom(self.roomId).get("CalculatedTemperature")/10




        return attrs 

Cheers

**Comment by asantaga** [comment]
tis a bit strange.. but I'll make the changes anyway.. 

I still have to create the ability to "set" temperatures, I'll do that at the same time (if I finish my accounts tonight)

**Comment by asantaga** [comment]
sorted, it was because i wasnt calling super and not executing the base code. fixed now
also pushed this to master as v1,2

**Comment by v966732** [comment]
I've downloaded 1.2 and it all works fine, thank-you

**Comment by asantaga** [comment]
excellent :-) , gotta admit I was baffled by this , even adding your code didnt really do the trick so I investigated more.. Then lightbulb moment, by trade Im a java developer and when subclassing you always call the super.. so when I investigated that I realised this is precisely what I needed to do :-) So for me this bug helped me in many ways 

Awesome stats too!!!
