### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by nottledim** [asantaga/wiserHomeAssistantPlatform#131]
I'm absolutely perplexed: I've installed using HACS and code is in custom_components apparently OK but I can't configure it.
```
8. Configure using Home Assistant Configuration Assistant "Set up new integration"
```
Where do I find this?  I don't see anything that looks like configure integration. So I've added my config to configuration.yaml and still nothing.  If I do check_config it reports:
```
INFO:wiserHeatingAPI.wiserHub:WiserHub data null after refresh
```
It's like it's not loading the component.  It is in HACS display of custom integrations but otherwise no sign.

Home Assistant 0.116.4  HACS 1.6.2  ArchLinux

Any help would be much appreciated.

**Comment by msp1974** [comment]
From the left hand menu, select Configuration.  In this you will see an option for Integrations. In here, you can add an integration by clicking on plus sign (bottom right), select wiser from the list and it will prompt you to provide IP and secret key of hub to set it up.

**Comment by msp1974** [comment]
This integration no longer supports config.yaml as HA is moving to the method outlined above.  Hope that helps.

**Comment by nottledim** [comment]
On 11/29/20 8:49 PM, Mark Parker wrote:
>  From the left hand menu, select Configuration. In this you will see an option for 
> Integrations. In here, you can add an integration by clicking on plus sign (bottom right), 
> select wiser from the list and it will prompt you to provide IP and secret key of hub to 
> set it up.

Thanks for replying, but 'wiser' isn't in the list.  I guess that's the problem all along.

Why?

**Comment by nottledim** [comment]
I think I've resolved it.  All I had to do was reload the page in the browser.  I thought I'd done that. Frustration city.  Thanks for your help.
