### ISSUE TITLE
TRV temperature input

### ISSUE THREAD

**Issue by JkF50** [asantaga/wiserHomeAssistantPlatform#135]
Hey!

I was wondering if it's possible to be able to use a third party thermostat (e.g. a Govee BLE unit) to be able to input the actual temp into TRVs? If so, how would I go about this?

I know for example, if you use one of Draytons thermostats, the thermostat takes precedent, but I can't see anything in the documentation in terms of an input for the TRVs.

Cheers!

**Comment by msp1974** [comment]
Jack,This has been asked before. See closed issue #116.MarkSent from my Galaxy

**Comment by JkF50** [comment]
Looks like a resounding no! No worries. Thanks Mark.
