### ISSUE TITLE
Wiser heat without hib?

### ISSUE THREAD

**Issue by ochstobi** [asantaga/wiserHomeAssistantPlatform#136]
Hello, 
this is more likely a question than an issue.
I have an Wiser Heat for my radiator connected via zigbee with home assistant. Does this addon works without the Wiser Hub?

**Comment by scooper1** [comment]
Not possible On 24 Jan 2021 05:06, ochstobi <notifications@github.com> wrote:
Hello,
this is more likely a question than an issue.
I have an Wiser Heat for my radiator connected via zigbee with home assistant. Does this addon works without the Wiser Hub?

**Comment by msp1974** [comment]
No. It uses the rest api with the hub to control everything. In a normal setup the integration controls the hub and the hub controls the TRVs etc over zigbee.Sent from my Galaxy
-------- Original message --------From: ochstobi <notifications@github.com> Date: 24/01/2021  05:06  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform <wiserHomeAssistantPlatform@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [asantaga/wiserHomeAssistantPlatform] Wiser heat without hib? (#136) 
Hello,
this is more likely a question than an issue.
I have an Wiser Heat for my radiator connected via zigbee with home assistant. Does this addon works without the Wiser Hub?

**Comment by msp1974** [comment]
Should also say that if getting a full kit is cost prohibitive, you can often pick up a hub only on Ebay. I got one for testing for £25 just before xmas.Sent from my Galaxy
-------- Original message --------From: ochstobi <notifications@github.com> Date: 24/01/2021  05:06  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform <wiserHomeAssistantPlatform@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [asantaga/wiserHomeAssistantPlatform] Wiser heat without hib? (#136) 
Hello,
this is more likely a question than an issue.
I have an Wiser Heat for my radiator connected via zigbee with home assistant. Does this addon works without the Wiser Hub?

**Comment by ochstobi** [comment]
Sadly the hub is no option for me. There are so many vendors out there for different smart home purposes and I don't want a bunch of proprietary hubs. 
Thanks fot the fast answers. I'll try some otger products then.
