### ISSUE TITLE
(Feature Request) Integrate Scheduler card/component

### ISSUE THREAD

**Issue by jimleach** [asantaga/wiserHomeAssistantPlatform#138]
Would be really great if it was possible to integrate (import/export) with the Scheduler card/component:
https://community.home-assistant.io/t/scheduler-card-custom-component/217458

This would provide a GUI-based mechanism for modifying the schedules, rather than editing the text files.

Just a thought/Feature-Request

**Comment by asantaga** [comment]
Nice idea, I honestly dont have the time to implement this but PRs' welcome

**Comment by asantaga** [comment]
nearly done :-)

**Comment by msp1974** [comment]
Just release v3.1.0 with this in it.  Hope it is what you had in mind.

**Comment by jimleach** [comment]
This is great - nice work and exactly what it needed - thank you!
