### ISSUE TITLE
merge conflict messages still in file after commit

### ISSUE THREAD

**Issue by angrycamel** [asantaga/wiserHomeAssistantPlatform#14]
https://github.com/asantaga/wiserHomeAssistantPlatform/blob/7dfbb2e0dd67c61d3bb535e3b64c81a9f65f4f95/sensor/wiser.py#L298

Looks like some conflict messages are left in the file after the merge (also see line 239)

**Comment by asantaga** [comment]
hey thanks, 

Yes I noticed this after I merged with master, Ive fixed this in branch Add_BoilerPCTDemand, this will be merged with master soon,

**Comment by asantaga** [comment]
should be fixed in 1.2, let me know if it isnt
