### ISSUE TITLE
Two zone -Two zone valve. Communicate to boiler via OT. Possible?

### ISSUE THREAD

**Issue by vampywiz17** [asantaga/wiserHomeAssistantPlatform#141]
Hello there,

My problem is not connected exactly with this integration, but it is wiser related problem and i hope the users able to help a bit.

Use a WT734R with two channel. Connect to channel 1  and 3 relay to two zone valve. The boiler is connected via OpenTherm . Two wireless thermostat is paired one by one channel. If heating request is happen with channel 1 the relay open the zone 1 and start the boiler via OT. It working well. But if heating reqauest happen on channel 3, it only open the relay but not start the boiler... 

It is a config. problem? Somebody use this system similar configuration?

**Comment by asantaga** [comment]
Hey  @vampywiz17 , 

Ive never seen this, nor do I have this setup :-( 

Have you checked with Wiser support they're pretty good..

Can I suggest you ask this question on the Home Assistant Wiser Forum, a lot more people will see it there
https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965

**Comment by scooper1** [comment]
I use four zone valves in my system  one for each floor and one for underfloor heating system which have another two zone valves 
Effectively the 4 main zone valves all trigger a single heat demand channel ( the boiler also has a two-way valve as normal that it manages to do hot water heat exchanger and external heat demand).  In my system the heathub turns on all three zone valves together via channel one.  This is effecent as only the floor rads needing heating take heat.   I used to have one thermostat for each floor.    If anyone needs extra info on this system please let me know

The system. Works very well.
