### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by bitlisz1** [asantaga/wiserHomeAssistantPlatform#142]
Got warning in Core log:

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'wiser'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'wiser'

Found:
https://www.home-assistant.io/blog/2021/03/03/release-20213/

> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.
> 
> If you see these warnings, please report the issue with the author of that custom integration.

**Comment by phixion** [comment]
I was about to report that aswell, it seems the entry for `documentation` isn't correct it's 404ing for me either.https://github.com/asantaga/wiserHomeAssistantPlatform/blob/bc2d338231a58714a7b173c4596c8d7689bf7f9b/custom_components/wiser/manifest.json#L5

**Comment by asantaga** [comment]
yeah will fix these this weekend, minor tweaks to be honest.

The reason for the doc link  is that we/I was looking to publish  as a full blown HA component but then the HA guys wanted me to split it up and release it in like a 10 separate blobs..    I aint got time for that so I dropped it.. 

HACS works fine

**Comment by scooper1** [comment]
It would look a lot more confident to first time users if the read.me documents was formatted correctly for hacs to directly show nicely formatted text not just a text dump On 12 Mar 2021 12:32, Angelo Santagata ***@***.***> wrote:
yeah will fix these this weekend, minor tweaks to be honest.
The reason for the doc link  is that we/I was looking to publish  as a full blown HA component but then the HA guys wanted me to split it up and release it in like a 10 separate blobs..    I aint got time for that so I dropped it..
HACS works fine

**Comment by phixion** [comment]
@asantaga 

No worries, I well aware that the way they want component maintainers to work isn't very optimized. @scooper1 I do think it is very well documented

**Comment by asantaga** [comment]
fixed in dev, will be released as 2.6

**Comment by euinor** [comment]
The home assistant release that will kill this integration is now named. From my logs on updating to 2021.05 (emphasis mine):
2021-05-25 12:37:00 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'wiser'. **As of Home Assistant 2021.6** this integration will no longer be loaded. Please report this to the maintainer of 'wiser'

**Comment by asantaga** [comment]
thanks, I was going to wait for some more "features" to be added, but Ive released it now

**Comment by asantaga** [comment]
ReOpening to remind me tonight

**Comment by asantaga** [comment]
2.6beta released
