### ISSUE TITLE
Room deleted from Wiser App not removed from HA

### ISSUE THREAD

**Issue by LucidityCrash** [asantaga/wiserHomeAssistantPlatform#143]
I have a Wiser Plug which I use as a signal booster, I had a room added in the Wiser App that only had the plug in it.  This generated warnings in the log as the Room didn't have a Room Stat or a TRV, so I removed the room from the App.  However the room still shows in the devices list in HA and there appears to be no way to remove it, the best I can do is disable it.

**Comment by asantaga** [comment]
Im fixing bugs this weekend, I'll try and work out how to fix this. I thought it would disappear by itself.. I think you could delete it by going to the HA Configuration/Entities screen and removing all the old ITRVs.. I'll try it later

**Comment by LucidityCrash** [comment]
There was never any iTRV's in the Wiser Room only the Plug/Signal Booster.  When I removed the Plug/Signal Booster from the room in Wiser and removed the room from the app and I went to the entities list there was still climate.wiser_landing entity in which the delete option is greyed out.

That said this may all be a bit moot as I've just gone and had a look and the entity is no longer there.  I'd restarted HA multiple times before I raised the ticket so I don't think that some more restarts since then have removed it though I did do an upgrade of HA Core and Supervisor as well.  Very strange

**Comment by LucidityCrash** [comment]
Nope not strange ... I'd set it to filter out disabled entities :(

**Comment by asantaga** [comment]
One way you can remove the rogue entity is to edit the `core.entity_registry` file in the `.storage` directory.

Can u try this?

**Comment by LucidityCrash** [comment]
It shows as a device not an entity.  I suppose I could remove it from the appropriate file ... shouldn't the integration do that though ?

**Comment by asantaga** [comment]
When I next look at the code I'll have a look and see if I can work out how to delete old devices..  Or at least workout an easy way to delete old devices.....

**Comment by LucidityCrash** [comment]
Have you had any thoughts about this ... low priority task.  I could just remove and re install the integration I suppose 😀

**Comment by msp1974** [comment]
@LucidityCrash apologies for the radio silence but this is coming in a release very soon.  Doing a lot of rework on api and therefore integration and i do have this function built in as a service that can be called.  Keep an eye out, we will announce this release as it will be a big one with a number of new features.

**Comment by asantaga** [comment]
We've just released V3beta via HACS and we've fixed this as a custom service which you can call, 
![image](https://user-images.githubusercontent.com/2940224/147073442-cb361257-db08-4fa4-8228-b74eddb6bf30.png)

please test and if needed reopen this issue
thanks!
