### ISSUE TITLE
wiser.set_smartplug_mode service auto not changing control source

### ISSUE THREAD

**Issue by tombadog99** [asantaga/wiserHomeAssistantPlatform#146]
I noticed today while trying to create an automation that the wiser.set_smartplug_mode service will change the control source "From schedule" to "From manual Override" but not vice versa. This is either user error on my part or perhaps something has changed since the overhaul Drayton made to shedules?

**Comment by asantaga** [comment]
Hey , I just tested this out on my system and it appears to work fine. 

What service and payload are you using?

**Comment by asantaga** [comment]
Closing, @tombadog99 let me know if this is still an issue and what service/payload you are using
