### ISSUE TITLE
ER : Cancel a boost (per room / whole house)

### ISSUE THREAD

**Issue by PRich13** [asantaga/wiserHomeAssistantPlatform#147]
I've set up an automation that boosts all of my rooms by a delta of 2 for 60 minutes (I couldn't see a way to boost all rooms without an automation). I want to be able to toggle the input boolean to off to cancel the boost if it's still running but I can't see an obvious way of doing this i.e. a service to call as part of the integration or perhaps setting the TRV's to a different mode? Am I missing something?

**Comment by rlewis187** [comment]
You can set the device mode back to auto. This should cancel the boost.

device_id: redacted
domain: climate
entity_id: climate.wiser_living_room_heating
type: set_hvac_mode
hvac_mode: auto

**Comment by msp1974** [comment]
Have you tried the climate.set preset service and use 'Cancel Boost' as the mode?You'll have to do for each wiser climate device.

**Comment by asantaga** [comment]
We could add a "boost everywhere" service, but I wonder if that really  is needed?
a) you could create an automation which could can call all your TRVs, they dont change often right?
b) I think nodered can loop around entities..

**Comment by asantaga** [comment]
@PRich13 does the method ~@msp194 mentioned and my idea of an automation work for you?

**Comment by PRich13** [comment]
@asantaga Yes thank you! apologies for the late reply, life got in the way of my tinkering. I can call the boost function with the wiser.boost_heating service and then cancel it with the climate.set_preset_mode service i.e.:

service: climate.set_preset_mode
data: {entity_id: climate.wiser_living_room, preset_mode: "Cancel Boost"}

As I've automated the "Whole house" boost by calling each TRV in an automation I'm happy enough to cancel the boost in the same way (there's only 6!)

Thank you all for your suggestions

**Comment by asantaga** [comment]
Do me a favour, can u update Recipies.md with the approach you've taken so other people can take advantage then issue a doc PR and I'll merge it in.

Thanks :-)

**Comment by asantaga** [comment]
Hey @PRich13 how did you automate this in the end? a loop or just automation with multiple devices?

**Comment by PRich13** [comment]
Hi @asantaga it ended up being straightforward enough to call the climate.set_preset_mode service on multiple devices via the automations GUI:

![image](https://user-images.githubusercontent.com/17034674/145191409-20923b91-03ca-42ef-9a5e-d18d61099270.png)

**Comment by asantaga** [comment]
Cool
We're looking to have a boost all, cancel boost all in the code, this will be better as we can iterate through the devices in code, so its more generic. 

thanks again

**Comment by asantaga** [comment]
Changing to ER, boost all, cancel boost all
(Might be dupe - tho)

**Comment by asantaga** [comment]
This is now implemented in R3.0 , due out any day now
