### ISSUE TITLE
Boost instead of manual adjustment from Home Assistant/HomeKit

### ISSUE THREAD

**Issue by charlesomer** [asantaga/wiserHomeAssistantPlatform#148]
First of all, thank you for your work on this!👏

I am using the HomeKit integration with this to make TRVs appear in the Home app, and it works pretty well. I can adjust the current set point but it’s not possible to “boost” the heating in any way it seems from the Home app.

I was wondering if it might be possible to add an option somewhere so that when the heating is adjusted from the Home app or via Home Assistant, it boosts for x amount of minutes at the set temperature instead?

Thank you!
Charles

**Comment by mrvladis** [comment]
I am not sure about Home App, but this functionality fully available in Home Assistant, both Web and mobile app.
You can boost for preset durations (30, 60, etc)

**Comment by asantaga** [comment]
Im a little confused, so you want to be able to boost a trv for 'n' minutes and then return to its normal scheduled temp?

**Comment by charlesomer** [comment]
![2F9961C3-6D04-40E7-8EF8-5023863DC4A9](https://user-images.githubusercontent.com/32498151/119340497-7e92f100-bc8a-11eb-878f-c8c34a078f1e.jpeg)
![8B318FBE-EAA5-4768-8E73-E999B5274AA9](https://user-images.githubusercontent.com/32498151/119340504-805cb480-bc8a-11eb-8834-920b96259382.jpeg)

So when either of these dials are adjusted (as far as I’m aware, they are basically the same thing), at the moment the temperature is adjusted until the next scheduled event in Wiser. However, I’d like it to boost to that temperature for n minutes (this time could just be fixed to an hour or something, or adjustable in Home Assistant).

This is similar to how the integration with Alexa currently works, you can ask Alexa to set the temperature which is actually just a boost to that temperature for an hour I think.

**Comment by asantaga** [comment]
got it, 

but if you go into the details of a climate entry (click the top-right three dots), you have boots presets of 30min/1hr/3hr and cancel). Is this not what you want?

**Comment by charlesomer** [comment]
Not quite since this isn't accessible from HomeKit unfortunately it seems so anyone who uses HomeKit will be overriding the temperature until the next scheduled event instead of only boosting for an hour or so.

**Comment by asantaga** [comment]
Ahi get it, so its available in HA native  but not in HomeKit.. Can home kit fire Automations in HA?

**Comment by charlesomer** [comment]
I believe I could set up a switch in HomeKit which would activate an automation in HA, but for my use case I’d rather be able to use the nice looking thermostat HomeKit icon :)

**Comment by asantaga** [comment]
Not sure how we'd this then, if homekit doesnt support the extra actions then the only way of doing this is via an automation.... 

Anyone else forgot ideas?

**Comment by msp1974** [comment]
Hello all. Sorry been quiet for a while but my email was filled today with this and I thought I could help.I think the only way to do this would be to add an option to the integration to have a homekit mode.If this mode was enabled then instead of setting temp it would boost temp for a defined period.This would be quite a lot of work and only worth doing if there were a number of people interested .  So maybe we can have as a suggested enhancement and ask for level of interest.WDYT?Sent from my Galaxy

**Comment by asantaga** [comment]
> Hello all. Sorry been quiet for a while but my email was filled today with this and I thought I could help.I think the only way to do this would be to add an option to the integration to have a homekit mode.If this mode was enabled then instead of setting temp it would boost temp for a defined period.This would be quite a lot of work and only worth doing if there were a number of people interested .  So maybe we can have as a suggested enhancement and ask for level of interest.WDYT?Sent from my Galaxy

to be honest Im not even sure its possible....Has anyone tried this?

**Comment by msp1974** [comment]
We would put an option in config options (which will then show i  the integrarion options panel like for where we set default boost temp etc).  The cloud integration via either homekit, google or alexa calls the integrations set temp function in climate.py. There we call the wiser api set temp function and pass in the target temp the function is called with.  You could change that if the 'homekit' option is set on to call the api  boost function instead to the temp set on the function call with possibly the default boost time.

**Comment by charlesomer** [comment]
That sounds like what I'm looking for :)

**Comment by charlesomer** [comment]
I had a go at trying to add something to the configuration options myself but I've never developed an integration for Home Assistant before so haven't managed to get very far unfortunately 😂

**Comment by charlesomer** [comment]
Okay so I spent a little more time on this and I think I've managed to get something working, I've created a PR (#149) so let me know what you think! It might need adjusting etc.

**Comment by charlesomer** [comment]
For reference, I'm currently also using this script which is also why I'd like this option.
https://github.com/charlesomer/home-assistant-trv-opener

It basically sets all TRVs to a specified temperature (in my case 21 degrees) when it detects heating is active somewhere, thereby rooms get heated up without actually requesting heat themselves if you don't want them to be requesting heat on their own (e.g. spare rooms).

**Comment by charlesomer** [comment]
Ah okay, I've _kind of_ managed to do it... but it's messy. I'll push the code again to GitHub at some point but basically the pyscript sets a constant variable which is an array of the TRVs that it has set itself. It then uses this in future checks but it doesn't feel like the best way to do it 🤷‍♂️

**Comment by msp1974** [comment]
Closing this issue. Hope @charlesomer youre happy with your solution.  Reopen if not.
