### ISSUE TITLE
Heating Boost request

### ISSUE THREAD

**Issue by mrvladis** [asantaga/wiserHomeAssistantPlatform#15]
Hi,
It would be nice to have the ability not just to update the temperature of the Thermostat / iTRV, but to be able to call for a Boost, like you do in the app.
This would allow to use external sensors to adjust the temperature in the room without changing the actual configuration of the iTRV.
Thanks.

**Comment by asantaga** [comment]
Boost is a nice idea, I need to look at "how" to implement this in HA.. 

Also whilst Im here, when u say update the temperature of the TRV/Thermo, Im guessing/assuming adjusting it temporarily is good enough right?

**Comment by mrvladis** [comment]
Hi,
I may try to help with "how".
For the adjustments / boost - from my point of view  temporary should be completely fine, as per use case I see is just to trigger some heating when the room is getting cold an sensor in the iTRV itself doesn't reflect the actual temperature.
If this temporary heat request didn't warm the room enough - automation would trigger it again by the same rule.

**Comment by asantaga** [comment]
Implemented with version v1.3
