### ISSUE TITLE
Version Key missing from manifest file

### ISSUE THREAD

**Issue by PistolaPeteUK** [asantaga/wiserHomeAssistantPlatform#150]
Home Assistant is reporting the following:

No 'version' key in the manifest file for custom integration 'wiser'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'wiser'

**Comment by PistolaPeteUK** [comment]
Didn't realise it had already been raised>

**Comment by asantaga** [comment]
No worries, I was waiting for time and some more enhancements before releasing a new version..

Time (with a 7month+5yr) is short but people are asking for it..

Ive release 2.6beta which has the change , hopefully 2.6 proper later this week/next
