### ISSUE TITLE
Wiser Integration Times Out

### ISSUE THREAD

**Issue by leacho73** [asantaga/wiserHomeAssistantPlatform#152]
Hi,

I've moved my Home Assistant instance to another location over a VPN, and although the latency is still very low - at about 11ms - I am unable to connect the Wiser Component to my Hub - I just get the following error:

_Connection to the Wiser Hub has timed out. Check the IP address and try again._

I can see the calls being made from my Home Assistant server to the Hub on Port 80 - but I'm still unable to connect.

I have also tried using YAML with no luck.

Could changing the IP of my Home Assistant server messed with the auth key?

Thanks
Leacho

**Comment by asantaga** [comment]
Hey

I'm not home this week but I dont think changing the IP causes a secure key reset..  I think the real issue is the UDP packets arent flowing though the vpn....

Does it work locally?

**Comment by leacho73** [comment]
Hi @asantaga - thanks for your reply - that's a good point with UDP packets and the VPN - it 'shouldn't' be an issue, but I'll have a look - I can see the traffic on Port 80, but that was TCP - what port(s) are the UDP packets expected? I can confirm it worked locally no issues - it was only when I moved it the other day.

**Comment by leacho73** [comment]
Hi @asantaga - spot on with the UDP thought! - tweaked the VPN and all sorted now - thank you!!

**Comment by asantaga** [comment]
Pleasure, 

I'm leaving this open as I'm going to improve the error messages and add some troubleshooting tips to the readme.md

Namely
- Use sample script standalone to check UDP Packets are arriving
- try and put HA and link on same network
- If using VPN then ensure UDP is being passed through 
etc

what VPN were you using?

**Comment by leacho73** [comment]
I was using a standard IPSec VPN between 2 PFSense Boxes - but moved it to an OpenVPN setup which has worked fine ever since.

**Comment by asantaga** [comment]
Hey awesome, 

If its of interest, I moved away from openvpn to Wireguard, so much simpler and just "worked".. From what Im hearing people are leaving openvpn in droves due to its complexity.... (or stupidity!!)
