### ISSUE TITLE
integration broken in latest home assistant beta 

### ISSUE THREAD

**Issue by scooper1** [asantaga/wiserHomeAssistantPlatform#154]
breaking change  ruamel_yaml removed 

2021-09-30 20:26:21 ERROR (MainThread) [homeassistant.setup] Setup failed for wiser: Unable to import component: cannot import name 'ruamel_yaml' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)

**Comment by scooper1** [comment]
got it working again by  editing __init__.py commented out following lines 
line 36
"""from homeassistant.util import ruamel_yaml as yaml, Throttle"""
line 324
    """@Throttle(MIN_TIME_BETWEEN_UPDATES)"""

**Comment by msp1974** [comment]
Seems this has been removed from HA but not listed in release note changes.  It is used to managed the import/export of schedules so is needed.  Best option is to add into the manifest file and i'll try and get an update release done this week to put in there.  Manifest then needs to be:{  "domain": "wiser",  "name": "Wiser Heating Component for Home Assistant",  "config_flow": true,  "documentation": "https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/Recipes.md",  "dependencies": [],  "codeowners": ***@***.***", ***@***.***"],  "version": "2.6",  "requirements": ["wiser-heating-api==1.0.10.0", "ruamel.yaml==0.15.100"]
}Will require restart.Sent from my Galaxy

**Comment by scooper1** [comment]
tried the manifest route first but did not work for me

**Comment by msp1974** [comment]
Ok. I'll look at this over weekend.Sent from my Galaxy

**Comment by asantaga** [comment]
thanks guys,

Alas Im "mid"moving house and all my wiser stuff is disconnected on my shelf. 

Can you test, issue PR and then me or Mark will merge and re-release.

Thanks

**Comment by msp1974** [comment]
@scooper1 can you please update to R2.6beta4 and see if this is now sorted.

**Comment by scooper1** [comment]
Appears to working ok 
Thanks for quick fix
