### ISSUE TITLE
Entities ‘freeze’ when Wiser goes offline

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#155]
Hi there!
I get a wierd issue where my HeatHub will go offline for a long amount of time, according the graphs on Wiser's app. I was hoping I could set up an automation to let me know of this so I can fix the issue, but I've found that whenever it all goes offline, all of the entities freeze their states, the thermostat's battery/signal/temperature and the HeatHub's WiFi/Cloud/Heating/etc. 

I'm running the latest of the integration and HA 2021.9.7. 

Thanks!

**Comment by msp1974** [comment]
I suspect it is your heathub dropping off your wifi so it is no longer talking to wiser cloud.  As integration talks directly to heathub, this will also not be able to update and therefore keeps its last values.Sent from my Galaxy

**Comment by msp1974** [comment]
I need to make some updates this weekend for an issue raised by scooter1 which will break this integration with next HA release.  I'll add a last updated attribute to the hub entity then you will be able to create an automation to see if has not updated for x amount of time and notify you.  I'll try and add example for you too as to how to use this.Sent from my Galaxy

**Comment by LewisSpring** [comment]
Brilliant, thank you so much!
This makes sense. I expected for the values to have gone to Unavailable.

**Comment by msp1974** [comment]
@LewisSpring the lastest release R2.6beta4 now has an attribute on the wiser heathub entity to show last updated.  You can use in an automation / template sensor like below:

```
{% if ((as_timestamp(now()) - as_timestamp(state_attr("sensor.wiser_heathub","last_updated"))) | int ) > 900 -%}
    Not updating
{%- else -%}`
    Updating
{%- endif %}
```

**Comment by LewisSpring** [comment]
Thank you! I'll install that and let you know if it works.

**Comment by LewisSpring** [comment]
> Thank you! I'll install that and let you know if it works.

All Good! It works! Thank you!
