### ISSUE TITLE
Error when starting after 2021.10 upgrade

### ISSUE THREAD

**Issue by anthonywalker75** [asantaga/wiserHomeAssistantPlatform#160]
Hello

I just upgraded my home assistant to the the latest 2021.10 version, upon restarting the wiser integration fails to start.

This is the error logged.

ERROR (MainThread) [homeassistant.setup] Setup failed for wiser: Unable to import component: cannot import name 'ruamel_yaml' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)

Reverted installation back to 2021.09 version and integration works again.

Regards

Anthony

**Comment by msp1974** [comment]
Please upgrade ypur version of the i tegration to 2.6beta4.  This was released a few days ago to fix this issue.Sent from my Galaxy
