### ISSUE TITLE
"Exception in async_update_state when dispatching 'WiserHubUpdateMessage': ()" after update to latest HA

### ISSUE THREAD

**Issue by tslytsly** [asantaga/wiserHomeAssistantPlatform#161]
Hi,
I updated to the latest HA version this morning and am now seeing this in the logs:

```
[31m2021-10-11 09:05:57 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_state when dispatching 'WiserHubUpdateMessage': ()

Traceback (most recent call last):
File "/config/custom_components/wiser/climate.py", line 460, in async_update_state
await self.async_update_ha_state(True)
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 443, in async_update_ha_state
self._async_write_ha_state()
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 491, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/config/custom_components/wiser/climate.py", line 379, in state_attributes
attrs = super().state_attributes
File "/usr/lib/python3.9/site-packages/homeassistant/components/climate/__init__.py", line 261, in state_attributes
self.current_temperature,
File "/config/custom_components/wiser/climate.py", line 228, in current_temperature
return raw / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
[0m
```

Not sure if its a config error, I didn't change anything except the update to HA.

**Comment by tslytsly** [comment]
Hi,
it appears to be working, I can see temps and adjust them from HA.
Just getting this error in the log periodically.
Temp graphs are also working.

**Comment by msp1974** [comment]
Tom,I upgraded to 2021.10.3 this morning and have seen no errors all day.I wonder if your hub is periodically not returning a good output.  Why this would start with this upgrade I have no idea.If you have any more info or anyone else can chime in if they are seeing something similar.Mark

**Comment by msp1974** [comment]
@tslytsly i have also started to notice more update failures from the wiser hub.  Doing some work recently on a future version of this integration, have been using postman to interegrate the hub directly and i frequently get a failed response from the hub. It responds but not with the json message expected.

Im going to keep this issue open to remind me to look at whether we can have a better retry within the api if it sees this behaviour.

**Comment by tslytsly** [comment]
Thanks Matt,

If you need anyone to test stuff, I can help.

Tom

**Comment by tslytsly** [comment]
Hi @msp1974 ,

I'm seeing more and more failures.
Currently I see this a lot:
```
[31m2021-12-06 07:37:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WiserHeat##### for wiser

Traceback (most recent call last):
File "/config/.local/lib/python3.9/site-packages/wiserHeatingAPI/wiserHub.py", line 196, in refreshData
resp.raise_for_status()
File "/usr/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://192.168.#.###/data/domain/
```
I've inserted the "##" to redact some data.

It seems to get fixed if I restart the heat hub.

Any ideas?

**Comment by msp1974** [comment]
Tom,This is a little strange  to get a 401 error from your hub.  I presume it is when you restart HA as your log shows it setting up the integration, or does it happen randomly?  It's also weird that rebooting the hub resolves it.What software version is your hub running? I have seen a lot of software updates on my hub recently.Have you got any unusual setup with it? Is it linked to anything else through the wiser app? Have you tried connecting to it with postman when this happens?MarkSent from my Galaxy

**Comment by tslytsly** [comment]
Hi @msp1974 ,
It happens randomly, it will work for a day or 2, then I'll notice it's offline.
If I then restart HA, that is the log message I get.

Nothing unusual, 10 TRVs and 1 plug.

I have tried connecting via Postman.
I either get unauthorised or a malformed response.

So for example:
![image](https://user-images.githubusercontent.com/17383159/145021400-5c5a8d7a-4c97-40bd-8499-726b1074f326.png)

I've also tried a bearer token, same malformed response.

**Comment by asantaga** [comment]
@msp1974 , Do we need to strengthen the reliability of the REST calls to the hub, ie cope with errors?  If an error occurs we'll just have the error message and then it will retry.. not sure there is much else we can do, maybe raise an event which the user can trap, and send a push msg if they wish?

**Comment by asantaga** [comment]
Hey @tslytsly  (tom), 

We are about to release 3.0 which has a lot of new features and a better internal engine, Im going to close this ticket for now and if we still have the issue in 3.0 we can look at it again.
