### ISSUE TITLE
Missing humidity entity

### ISSUE THREAD

**Issue by dunxd** [asantaga/wiserHomeAssistantPlatform#162]
I can see from the code that the integration should pick up the humidity from the Room Stat, but I can't find it in entities for the room stat, or the room.

I have iTRVs in the same room as the stat.

**Comment by msp1974** [comment]
Sorry not at home to double check but think it is an attribute on the climate entity.  Have you looked in developer tools at your roomstat?Sent from my Galaxy

**Comment by msp1974** [comment]
Duncan,Just looked on my phone app and yes, appears not to be there.  Will issue a fix for this.MarkSent from my Galaxy

**Comment by dunxd** [comment]
Thanks @msp1974 I managed to get the humidity as a sensor as you described.
