### ISSUE TITLE
Version code must be x.x.x

### ISSUE THREAD

**Issue by tsh-xx** [asantaga/wiserHomeAssistantPlatform#163]
I just. updated to core 2021.10.5 and found wiser wouldn't load.

The version string in manifest.json needs to be "2.6.0", not just "2.6". With this change, it seems to work fine.

https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

**Comment by msp1974** [comment]
Thanks for the notice.  Will update and provide a release.Sent from my Galaxy

**Comment by msp1974** [comment]
Closing as was fixed in latest 2.6beta5 release.  Thanks
