### ISSUE TITLE
Change of Wiser Hub requires manual update to ./storage/core.config_entries

### ISSUE THREAD

**Issue by andynuk** [asantaga/wiserHomeAssistantPlatform#173]
In the circumstance where:

- Original setup the IP address and Secret in the configuration setup (not in a configuration.yaml file)
- The IP address of the wiser hub changes

The following happens:
- Adding a new IP address in the configuration.yaml file does not take priority over the saved configuration
- There is no GUI ability to change the IP address or Secret key from in the Configuraton, Integrations part of Home Assistant
- Only method is to manual edit the ./storage/core.config_entries file (which is not recommended)

But to say this is a really great integration.

Andy

**Comment by msp1974** [comment]
This is a standard complaint about HA as there is no function to edit the setup, only options.  I have not been able to find any way around this previously.  I did look at a fudge of being able to also set in options and override main settings but this is also not recommended.Couple of possible ways to do this (1st one i have not tested).1) dont use ip but use hostname of wiser hub.  This is WiserHeatxxxxxx.local.  as it supports mdns this should work and not be broken by change ip.  Replace x's with last 6 digits of mac for your specific hub.2) remove and re-add integration.  It should recreate all devices and entities with same names so any custom setup should still work.MarkSent from my Galaxy

**Comment by msp1974** [comment]
Closing this issue as a core HA problem not intefration.  Hope the suggestions helped.
