### ISSUE TITLE
Error loading schedules on latest beta

### ISSUE THREAD

**Issue by lwis** [asantaga/wiserHomeAssistantPlatform#174]
`Error loading schedule file /config/schedules/hotwater_schedule.yaml. Error is type object 'YAML' has no attribute 'load_yaml'`

Not sure if the HASS API has changed?

**Comment by msp1974** [comment]
Can you confirm version of integration and HA as I think we did fix this issue.  If not, we can look again.Sent from my Galaxy
-------- Original message --------From: Lewis Juggins ***@***.***> Date: 04/11/2021  07:24  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform ***@***.***> Cc: Subscribed ***@***.***> Subject: [asantaga/wiserHomeAssistantPlatform] Error loading schedules on latest beta (Issue #174) 
Error loading schedule file /config/schedules/hotwater_schedule.yaml. Error is type object 'YAML' has no attribute 'load_yaml'
Not sure if the HASS API has changed?
