### ISSUE TITLE
Smart Plug stats

### ISSUE THREAD

**Issue by dunxd** [asantaga/wiserHomeAssistantPlatform#175]
Just for fun I figured out how to add a Drayton Wiser Smart Plug to ZHA and it was detected as a Heiman Smart Plug, which Amazon used to sell. It included stats on power usage through the smart plug and they worked as far as I could tell. I did buy the smartplug to extend the Wiser ZigBee network, so I joined it back and haven't got any further.

I don't suppose in your development of this excellent integration you may have noticed any sign of the Wiser hub exposing these stats, or is it something Schneider/Drayton haven't implemented at all.

I also noted that when Drayton added "Moments" they included a lot of icons for lights and other smart home stuff which leaves me hopeful the HeatHub might become a more functional ZigBee controller than currently. Any thoughts on this?

**Comment by msp1974** [comment]
Duncan,

 

The Wiser Hub doesn’t expose any power usage stats unfortunately.  I also had previously played with this an noted it was a Heiman smart plug rebadged.

 

In regards to other types of devices (lights etc), the does show a capability list with a number of different device types.  However, some of these show as not capable (as below).  Whether the hub will be able to control these in the future, we may have to wait and see.

 

"DeviceCapabilityMatrix": {

        "Roomstat": true,

        "ITRV": true,

        "SmartPlug": true,

        "UFH": true,

        "UFHFloorTempSensor": true,

        "UFHDewSensor": true,

        "HACT": false,

        "LACT": false,

        "Light": false,

        "Shutter": false,

        "LoadController": true

    }

 

 

From: Duncan Drury ***@***.***> 
Sent: 04 November 2021 15:35
To: asantaga/wiserHomeAssistantPlatform ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [asantaga/wiserHomeAssistantPlatform] Smart Plug stats (Issue #175)

 

Just for fun I figured out how to add a Drayton Wiser Smart Plug to ZHA and it was detected as a Heiman Smart Plug, which Amazon used to sell. It included stats on power usage through the smart plug and they worked as far as I could tell. I did buy the smartplug to extend the Wiser ZigBee network, so I joined it back and haven't got any further.

I don't suppose in your development of this excellent integration you may have noticed any sign of the Wiser hub exposing these stats, or is it something Schneider/Drayton haven't implemented at all.

I also noted that when Drayton added "Moments" they included a lot of icons for lights and other smart home stuff which leaves me hopeful the HeatHub might become a more functional ZigBee controller than currently. Any thoughts on this?

**Comment by dunxd** [comment]
I noticed lights and shutters in the icon list, and in the "new features" screen that showed only once after the app upgrade to allow "Moments" so maybe its on the roadmap.  If it is I hope they embrace a wider zigbee ecosystem and not just their own brand stuff like the rather expensive smart plug.

I see Heiman Smart Plugs that look identical come up on EBay - tempted to buy one to see if it works as a cheaper range extender - although they are cheap because they are discontinued and got really bad reviews on Amazon!
