### ISSUE TITLE
Does this work with other trvs?

### ISSUE THREAD

**Issue by atv2016** [asantaga/wiserHomeAssistantPlatform#179]
Like tuya zigbee trvs? Or only Drayton wiser ones?

also, what Drayton wiser set do i need to get for this?

thanks!

**Comment by asantaga** [comment]
Only drayton wiser, it doesnt connect to zigbee it connects to the drayton hub

Any of the drayton wiser installs work

**Comment by atv2016** [comment]
Ah ok . Let me slightly reframe the question, so would there be a chance of other trvs communicating properly with the wiser hub? 

I guess one can try?

many thanks!

**Comment by asantaga** [comment]
Whilst the drayton trvs use zigbee  i am 99.999997% sure that he drayton hub would not work with other TRVs.. 

Give it a go, then update this ticket!
