### ISSUE TITLE
Allow functionality which boosts the entire house

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#180]
From https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/285

This can be done today via scripts, hard coding the rooms (or dynamically querying them?). 
FR to either
a) Add script to release
b) Add functionality to integration so that it loops around and boosts all  radiators
User can then bind a button to boost all

**Comment by asantaga** [comment]
fixed in 3.0

**Comment by toddstar** [comment]
> fixed in 3.0

Is there an option to set the temperature boost for this all rooms update? Just testing all my setup/automations for V3 so thought id have a look at new bits and for all rooms its set 1 hour & 0.5c boost, time is ok (although my be nice to also have a default boost time) but 0.5c seems pretty low

**Comment by asantaga** [comment]
you can set the boost temperature in the settings screen for the integration

![image](https://user-images.githubusercontent.com/2940224/147297015-97409ea2-1d77-429b-941e-875b191a3770.png)

**Comment by toddstar** [comment]
seems the boost all is ignoring the temperature set here (although time is working)

![Screenshot 2021-12-23 224701](https://user-images.githubusercontent.com/22575856/147297362-7d1694ec-36ae-43ec-a55e-5d7943a706de.png)
![Screenshot 2021-12-23 224701](https://user-images.githubusercontent.com/22575856/147297366-7bd8c8c0-9153-447e-8653-f34db7843c0a.png)

**Comment by msp1974** [comment]
Yes, this is a bug in the api.  Will be fixed in next release.

**Comment by toddstar** [comment]
> Yes, this is a bug in the api. Will be fixed in next release.

thanks!!

just an fyi, there appears to be an issues with set_heating_schedule on multiple climate zones at once (via node_red) too but still trying to debug it as doesn't always happen; code I have is https://pastebin.com/FLBbkbFF (was fine on v2) its changing the schedule temps of each climate fine but often its changing the first climate it finds (in my house living room) to +5c for 300mins (although not always)

**Comment by toddstar** [comment]
so found the issue, wiser.boost_heating is now only a boost only settings rather than allowing for a target temp to be set even if its lower than current temp; a few of my current automations are along the lines of "if door is open then 'boost' room temp to 5c." (to kill the radiator) which is now being read a 'current temp + 5c'.

guest best way forward is requesting a wiser.set_target_temp service? (as I assume the wiser.boost_heating changes have been reduplicated/replicated/called into all the other actions? i.e. 'boost for X mins)

**Comment by msp1974** [comment]
Maybe not very clear in documentation but you can use a number of the climate services, the wiser ones are only for additional functions not built into standard climate device. There is a climate.set_temperature service which will do exactly what you are asking.  Only difference is that it does not do it for a specified time, just until next schedule change. You could also call the climate.set_hvac_mode and set to off if you just want to kill the radiator.

As a side note, there is a window/door open function on the trvs (which can now be enabled in v3). Never really tested it so not sure if works well or not but think it is designed to stop heating if it detects a sudden drop in temp.

Mark

**Comment by toddstar** [comment]
climate.set_temperature seems to work thanks :+1:

window/door open within wiser is shite lol

**Comment by msp1974** [comment]
Issue with boost all rooms not honouring the temp setting is fixed in 3.0.15, which I have just released.

**Comment by msp1974** [comment]
This should now be fixed, so closing issue.

**Comment by toddstar** [comment]
> This should now be fixed, so closing issue.

yeah working fine now mate! (apologies thought i'd already replied confirmed working with the update)
