### ISSUE TITLE
allow override of HW current state without affecting schedule following.

### ISSUE THREAD

**Issue by a346534545** [asantaga/wiserHomeAssistantPlatform#181]
posts here refer:-

https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/288?u=a345623456
https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/291?u=a345623456

**Comment by msp1974** [comment]
This is included in v3 with the button to toggle hot water. If in auto mode it will override the hotwater until next schedule time.
