### ISSUE TITLE
device_state_attributes is deprecated

### ISSUE THREAD

**Issue by dunxd** [asantaga/wiserHomeAssistantPlatform#182]
With the update to HA 2021.12, a warning is logged for each entity used in this platform:

> Entity sensor.wiser_itrv_hallway_battery_level_2 (<class 'custom_components.wiser.sensor.WiserBatterySensor'>) implements device_state_attributes. Please report it to the custom component author.

According to [the docs](https://dev-docs.home-assistant.io/en/master/api/helpers.html):

> property `device_state_attributes`
> Return entity specific state attributes.
> 
> This method is deprecated, platform classes should implement `extra_state_attributes` instead.

**Comment by dunxd** [comment]
I changed device_state_attributes to extra_state_attributes in custom_components\ wiser/sensor.py and switch.py in my own install and seems to have resolved the warning message. Not sure how to submit pull requests in github to save you the five minutes to search/replace.

**Comment by msp1974** [comment]
Resolved in v3. Now uses extra_state_attributes.
