### ISSUE TITLE
[Feature Request] Power usage on wiser smart socket

### ISSUE THREAD

**Issue by PRich13** [asantaga/wiserHomeAssistantPlatform#185]
Hi, I've noticed in the wiser app that I now see the current power usage in watts on the smart socket. Are there any plans to bring this into HA?

**Comment by msp1974** [comment]
Yes its in the next release.  ThxSent from my Galaxy
-------- Original message --------From: PRich13 ***@***.***> Date: 14/12/2021  20:50  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform ***@***.***> Cc: Subscribed ***@***.***> Subject: [asantaga/wiserHomeAssistantPlatform] [Feature Request] Power usage on wiser smart socket (Issue #185) 
Hi, I've noticed in the wiser app that I now see the current power usage in watts on the smart socket. Are there any plans to bring this into HA?

**Comment by PRich13** [comment]
Awesome, thanks!
