### ISSUE TITLE
v3 - Entering secret key does nothing when setting up integration

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#189]
Hello,
I decided to move to v3 and start updating all of the entities and automations etc.

When I try to re-add the HeatHub via the Integrations menu, when I press Submit with the secret key, the box just refreshes.
I can't see any log lines relating to the issue.

Thank you

https://user-images.githubusercontent.com/40576482/147090280-5fa9833a-7c3e-4994-842c-44f182b12e55.mov

**Comment by LewisSpring** [comment]
I just reverted to 2.7FINAL, when I submit the integration parameters to add the integration,
I get this.
<img width="481" alt="Screenshot 2021-12-22 at 12 08 30" src="https://user-images.githubusercontent.com/40576482/147090709-dd3f6a78-660f-4aec-8461-03a9b8409b78.png">

**Comment by msp1974** [comment]
Presume you have rebooted.  You could try turning on debug for the i tegration in configuration.yaml .  Are you sure your key is correct.  I have not tested adding an incorrect key so it maybe missing a correct error alert.  If younturn on debug you should see if it is failing to authenticate.Sent from my Galaxy

**Comment by msp1974** [comment]
Under logger in your configuration.yaml add custom_components.wiser: debugIf that doesn't show anything then can you try running the test_api_methods.py on the api githubhttps://github.com/msp1974/wiserHeatAPIv2/tree/master/testsYou will need to create a params.py file with below entries and put in it in the same directory as the test file.  This may give you a better output of the issue.HOST="192.168.0.50"KEY="[yourkey]"

**Comment by LewisSpring** [comment]
Hi, thanks for your reply.
I enabled logging and then tried adding the integration.
It didn't autodetect it, so I added with IP manually.

It worked perfectly fine.
The only diffence is that I'm not using my laptop, so no idea why it works now!
Thanks for your help!

**Comment by msp1974** [comment]
Great to hear. I'll close this issue.
