### ISSUE TITLE
Feature suggestion - service to change away mode temperature

### ISSUE THREAD

**Issue by tombadog99** [asantaga/wiserHomeAssistantPlatform#190]
Loving all the additions in v3 so far. The only thing that is missing that would be useful to me is the ability to change the setpoint of the away mode temperature. If this was possible via a service, it would be a great addition.

**Comment by msp1974** [comment]
I was going to add a number slider in the UI for this (then it can use the default service for number sliders too) but ran out of time to add before releasing.  Will add to next update (or maybe next but one if we get any urgent issues)

**Comment by msp1974** [comment]
Just added to latest release.

![image](https://user-images.githubusercontent.com/11211952/147263280-5402c7bc-3d13-425f-9ef5-733aa50e5a53.png)

**Comment by tombadog99** [comment]
Wow, incredibly fast. Many thanks!
