### ISSUE TITLE
v3 - Missing HeatHub sensor

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#191]
Hello,
Now I've got V3 working, I can't seem to find the HeatHub sensor with the Zigbee channel.
I was hoping to get a connected/disconnected state from it.

These are the only entities I can see from the HeatHub Device.
![image](https://user-images.githubusercontent.com/40576482/147166818-42e25183-4501-435c-a2f3-3099c21853ff.png)

Really liking V3 so far,
Thank you!

**Comment by msp1974** [comment]
Yes, the hub zigbee sensor was removed in v3 as it didnt really make too much sense.  All the devices have a signal sensor which shows zigbee channel, strength plus more.  Explain more to me your use case you are trying to solve and more about the connected/disconnected status as i saw this as being more from a device side than the hub side.

Mark

**Comment by LewisSpring** [comment]
Hi Mark,
I should have clarified better that I didn't need the Zigbee information, but instead would like a binary sensor that senses if the HeatHub is connected or disconnected to Home Assistant. My use case is a notification if it drops off the network so I can fix it. I had issues with it disconnecting for a while - this would have been really helpful before someone helped me create a template.

**Comment by msp1974** [comment]
I have pushed an update just now to the integration to fix/update from the feedback.  Thinking about your use case, I added some additional attributes to the Heating Operation Mode Sensor.  Let me know if this works for you.  

![image](https://user-images.githubusercontent.com/11211952/147263056-77406435-81d0-4d66-8f30-78045801679b.png)

**Comment by LewisSpring** [comment]
> I have pushed an update just now to the integration to fix/update from the feedback. Thinking about your use case, I added some additional attributes to the Heating Operation Mode Sensor. Let me know if this works for you.
> 
> ![image](https://user-images.githubusercontent.com/11211952/147263056-77406435-81d0-4d66-8f30-78045801679b.png)

Hello, 
That absolutely works.
Thank you very much for doing this.

**Comment by msp1974** [comment]
Should not, if the integration failed to be able to update from the hub, the last update status will say 'Failed' and the minutes will start to show how long it has been failing (assuming your hub is updating every min or less).

You can add this to a template sensor or even use in an automation to repower your hub if you have it connected to some sort of wifi power plug.

**Comment by LewisSpring** [comment]
That works quite well, since I can do
"If the LastUpdateStatus is "Failed" and It's been 5 minutes since last update, send a notification."

**Comment by msp1974** [comment]
Great.  Glad this works for you and hopefully others.  I have notice my hub drops off the network almost daily for about 5 mins but then comes back on.  No idea why it has started doing that but did help me code v3 to handle it well! :-)

Will close this issue if that's ok.
