### ISSUE TITLE
v3 - Wiser Plug not appearing in Energy configuration.

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#192]
I was trying to add the consumption statistics of the Wiser Plug to the energy dashboard, but HA doesn't detect it.
![image](https://user-images.githubusercontent.com/40576482/147167302-ccbd7975-2ba3-4d01-8540-a5c3c1c491bc.png)

I think this is something to do with the plugin's side.

Thank you!

**Comment by msp1974** [comment]
Yes the sensors need to be of device class energy for this to work and they are set to power as LTS sensors cannot be set to energy according to documentation.  Not sure i fully understand what that means but I'll look at this for next update.

**Comment by msp1974** [comment]
Actually scratch that. I can see a bug in the code that is setting the total power sensor to the wrong state class. Will fix in next update.

**Comment by LewisSpring** [comment]
Great. Thank you!

**Comment by msp1974** [comment]
Fix in latest 3.0.14 update just pushed now.

![image](https://user-images.githubusercontent.com/11211952/147263457-e0d5556a-e25d-47a7-9d00-a65a37258eaf.png)

**Comment by LewisSpring** [comment]
> Fix in latest 3.0.14 update just pushed now.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/11211952/147263457-e0d5556a-e25d-47a7-9d00-a65a37258eaf.png)
> 
> 

Just tested. The kWh sensor appears in the Energy configuration. 
Thank you!

**Comment by msp1974** [comment]
Great.  Will close this issue
