### ISSUE TITLE
v3 - multiple iTRV in same room

### ISSUE THREAD

**Issue by jamesmyatt** [asantaga/wiserHomeAssistantPlatform#194]
When there are multiple iTRVs in the same room, then they are registered in HA as one device with duplicated entities rather than two separate devices. How can I fix this? I'm using v3. I can't remember what the behaviour with v2 was.

**Comment by msp1974** [comment]
I'm not sure whether v2.7 supported this either.  Anyhow, v3.0.14 does not create separate devices for your scenario.  I have a fix for this to name them Wiser iTRV Lounge-1 and Wiser iTRV Lounge-2 etc for the next release.  May be able to push this tonight or tomorrow for you.

If this works, you will have an orphaned device for your original one with duplicated entries (except it will now have no entries).  You will now be able to use the Remove Orphaned Devices service to remove this once you have updated to 3.0.14.

**Comment by jamesmyatt** [comment]
I've updated via HACS to 3.0.14, but it looks the same.

One issue with your fix is that, if another iTRV is added to a room that already has 1, then they will get renumbered. I guess there's also the question of whether the order might change too if one is added when there's already 2 or more too.

**Comment by msp1974** [comment]
Sorry James, this was a typo in my comment - it should have said that 3.0.14 does not accomodate multiple TRVs in a room but 3.0.15 will.

I have just released 3.0.15 and yes, it is possible that if you add another TRV to a room then the order could changed.  However, I am numbering them by device ID order so for this to occur it would have to be an existing one moved into a room with an existing one already.  I think this maybe an edge scenario and it looks more logical to number 1,2,3 etc than the device ID.

Anyhow, update to 3.0.15, use the remove_orphaned_devices service to remove your now defunct device and let me know how you get on.

Thx Mark

**Comment by jamesmyatt** [comment]
Perfect. Thanks! (No problem about the typo)

And I agree about the edge case. Doesn't seem serious enough to do anything about specifically unless people complain.
