### ISSUE TITLE
Support Wiser electric heating actuator

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#199]
Copied from PR #198 by @LGO44

I have a electrical heatingwith Heating Actuators
This release doesn't take these systems in account

Here are the information provided by the WiserHeat Hub (got with wireshark traces)

    _Member: HeatingActuator
        Array
            Object
                Member: id
                    [Path with value: /HeatingActuator/[]/id:6]
                    [Member with value: id:6]
                    Number value: 6
                    Key: id
                    [Path: /HeatingActuator/[]/id]
                Member: OutputType
                    [Path with value: /HeatingActuator/[]/OutputType:Relay]
                    [Member with value: OutputType:Relay]
                    String value: Relay
                    Key: OutputType
                    [Path: /HeatingActuator/[]/OutputType]
                Member: MeasuredTemperature
                    [Path with value: /HeatingActuator/[]/MeasuredTemperature:184]
                    [Member with value: MeasuredTemperature:184]
                    Number value: 184
                    Key: MeasuredTemperature
                    [Path: /HeatingActuator/[]/MeasuredTemperature]
                Member: OccupiedHeatingSetPoint
                    [Path with value: /HeatingActuator/[]/OccupiedHeatingSetPoint:195]
                    [Member with value: OccupiedHeatingSetPoint:195]
                    Number value: 195
                    Key: OccupiedHeatingSetPoint
                    [Path: /HeatingActuator/[]/OccupiedHeatingSetPoint]
                Member: CurrentSummationDelivered
                    [Path with value: /HeatingActuator/[]/CurrentSummationDelivered:6]
                    [Member with value: CurrentSummationDelivered:6]
                    Number value: 6
                    Key: CurrentSummationDelivered
                    [Path: /HeatingActuator/[]/CurrentSummationDelivered]
                Member: InstantaneousDemand
                    [Path with value: /HeatingActuator/[]/InstantaneousDemand:0]
                    [Member with value: InstantaneousDemand:0]
                    Number value: 0
                    Key: InstantaneousDemand
                    [Path: /HeatingActuator/[]/InstantaneousDemand]
            Object
                Member: id
                    [Path with value: /HeatingActuator/[]/id:12]
                    [Member with value: id:12]
                    Number value: 12
                    Key: id
                    [Path: /HeatingActuator/[]/id]
                Member: OutputType
                    [Path with value: /HeatingActuator/[]/OutputType:FilPilote]
                    [Member with value: OutputType:FilPilote]
                    String value: FilPilote
                    Key: OutputType
                    [Path: /HeatingActuator/[]/OutputType]
                Member: MeasuredTemperature
                    [Path with value: /HeatingActuator/[]/MeasuredTemperature:-32768]
                    [Member with value: MeasuredTemperature:-32768]
                    Number value: -32768
                    Key: MeasuredTemperature
                    [Path: /HeatingActuator/[]/MeasuredTemperature]
                Member: OccupiedHeatingSetPoint
                    [Path with value: /HeatingActuator/[]/OccupiedHeatingSetPoint:40]
                    [Member with value: OccupiedHeatingSetPoint:40]
                    Number value: 40
                    Key: OccupiedHeatingSetPoint
                    [Path: /HeatingActuator/[]/OccupiedHeatingSetPoint]
                Member: CurrentSummationDelivered
                    [Path with value: /HeatingActuator/[]/CurrentSummationDelivered:2]
                    [Member with value: CurrentSummationDelivered:2]
                    Number value: 2
                    Key: CurrentSummationDelivered
                    [Path: /HeatingActuator/[]/CurrentSummationDelivered]
                Member: InstantaneousDemand
                    [Path with value: /HeatingActuator/[]/InstantaneousDemand:0]
                    [Member with value: InstantaneousDemand:0]
                    Number value: 0
                    Key: InstantaneousDemand
                    [Path: /HeatingActuator/[]/InstantaneousDemand]
        Key: HeatingActuator
        [Path: /HeatingActuator]_

**Comment by msp1974** [comment]
@LGO44, please can you provide a full postman output from your hub for the /data/v2/domain/ path in order for us to look at whether this can be implemented into the integration.

**Comment by LGO44** [comment]
Here is a file with my configuration (extracted by wireshark) and another Excel file where I began to investigate
[wiser hub For investigation.xlsx](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7775817/wiser.hub.For.investigation.xlsx)
[Description WiserHeat_json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7775822/Description.WiserHeat_json.txt)

**Comment by LGO44** [comment]
Of course , I could test the improvements all along the development if needed

**Comment by msp1974** [comment]
ok @LGO44 , I have used the WireShark output you provided to add support to the api (not the integration for HA yet) for Heating Actuators, Shutters (basic - no control) and Lights (basic - no control).

At present, none of these things are available in the UK, although it looks like the heating actuators are coming soon but no sign of plans yet for the shutters and lights.

I need you to do the following for me to test:

1) Clone the api from my repo [WiserHeatAPIv2](https://github.com/msp1974/wiserHeatAPIv2)
2) Create a file called params.py in the tests directory of this clone
3) Run the test_api_properties.py file
4) Send me the output of this

Not sure of your level of comfort in python/HA but, I think (but not 100%) that this update to the api will create devices now for your actuators, lights and shutters.  It will not allow you to control the shutters/lights yet (as I will need more info from you to be able to add that).  So if in your HA environment, you clone this repo over the installed version of the api you can see how it works.

**Comment by LGO44** [comment]
Mark,
First I would like to thank you for your job.
I've tried to install the new API without any positive result. I'm sorry I'm not very comfortable with python, HA ...
Could you give me a procedure to install the API and to run the test.
In HA i have already installed Samba share and Terminal&SSH.

For your information the Drayton Wiser system is sold over the Schneider Electric brand. The shutter and light are also product that come for my knowledge from Merten another company of Schneider Electric...As i 'll get informations I'll share them.

**Comment by msp1974** [comment]
So, initially don't worry about HA.  You need a basic ssh session to your linux box.In your home directory, do the following:git clone https://github.com/msp1974/wiserHeatAPIv2.gitthen type:cd wiserHeatAPIv2/testsnow create a file params.py and in it enter the following:HOST = "your hub IP"KEY = "your hub secret key"Save this file.  Now type the below to run the api:python3 test_api_properties.pyThis will produce a large screen output ofthe api data structures (or an error if there is a problem). Please provide this to me to check the api changes are correctly picking up the correct info from the hub.  If this is working ok, I will update the integration to use the updated api and provide a release that should show your heating actuators, shutters and lights as devices.  However, as stated before, we will need to do more research and coding to be able to control the lights and shutters / know if we can do this.MarkSent from my Galaxy

**Comment by LGO44** [comment]
I'm sorry for being so bad at Linux and HA.
I am  realizing the requested tests.
I cloned the wiserheatAPIv2 
, created the tests directory 
and created the params.py file.
When I want to run the python3 test_api_properties.py command I get the response
_bash: python3: command not found_
 screen shot
![image](https://user-images.githubusercontent.com/95585425/147478163-49fe7b7b-2461-4da4-a1f8-d12ee30ca4fb.png)

I work with a Virtual Machine (virtual box got on HA )

**Comment by msp1974** [comment]
You are using the terminal and ssh addon in HA (provided by HA version).  This does not contain python.  Either access you linux VM directly using putty or something (ie not via HA addon) or use the community SSH Terminal addon that does include python.Sent from my Galaxy

**Comment by LGO44** [comment]
Here are the results got with an SSH connection with Putty or with "SSH  and Web terminal" screen shot

I modify the line of the file "/config/wiserHeatAPIv2/tests/test_api_properties.py" to solve an error on the first try :

from params import HOST, KEY

import sys
"""sys.path.append('/home/mark/development/wiserHeatAPIv2/')"""
sys.path.append('/config/wiserHeatAPIv2/')

the screen shot of the results
![image](https://user-images.githubusercontent.com/95585425/147506981-7015b611-4961-408d-b7ff-efc96b0c4fdd.png)

**Comment by msp1974** [comment]
@LGO44 - ok I think this may not be the best way to proceed.  I have used the data you sent me to test and integrate this into the HA integration.

If you update the Wiser Integration in HA to 3.0.16 and see if that now shows devices for your Heating Actuators, Shutters and Lights.

Mark

**Comment by LGO44** [comment]
@msp1974  Thanks for this integration.
sorry for not beeing to help you much more with the API.
here are the data got for the Heating Actuator, the shutter, and the light

Wiser HeatingActuator

vendor: Drayton Wiser
product_type: HeatingActuator
model_identifier: CCTFR6700
displayed_signal_strength: Online
firmware: '01000000'
serial_number: 000D6FFFFE9D2ADD
zigbee_channel: 25
node_id: 31122
device_reception_RSSI: -61
device_reception_LQI: 0
controller_reception_RSSI: 0
device_class: power_factor
icon: mdi:wifi-strength-4
friendly_name: Wiser HeatingActuator Cuisine Signal

Wiser shutter

vendor: Drayton Wiser
product_type: Shutter
model_identifier: Shutter
displayed_signal_strength: VeryGood
firmware: 020519ff
serial_number: 000D6FFFFE3F82E5
zigbee_channel: 25
node_id: 18854
device_reception_RSSI: -55
device_reception_LQI: 240
controller_reception_RSSI: -40
device_class: power_factor
icon: mdi:wifi-strength-4
friendly_name: Wiser Shutter Côté  Signal

Wiser light

vendor: Drayton Wiser
product_type: DimmableLight
model_identifier: DimmableLight
displayed_signal_strength: VeryGood
firmware: 020519ff
serial_number: 000D6FFFFE3BA706
zigbee_channel: 25
node_id: 43801
device_reception_RSSI: -65
device_reception_LQI: 200
controller_reception_RSSI: -50
device_class: power_factor
icon: mdi:wifi-strength-4
friendly_name: Wiser DimmableLight Lustre Signal

a lovelace that show all the data for a room (kitchen)
![image](https://user-images.githubusercontent.com/95585425/147561061-b1e94ed6-071e-4ea6-9c0f-e78a90b37a2a.png)

the log with an error signaled in the climate .py file
[home-assistant.log](https://github.com/asantaga/wiserHomeAssistantPlatform/files/7784377/home-assistant.log)

**Comment by msp1974** [comment]
Ok looks like you have no schedule attached to your room.  Didnt know you could do that.  If you temporarily comment out lines 303 and 304 
```
attrs["next schedule change"] = str(self._room.schedule.next.time)
attrs["next_schedule_temp"] = self._room.schedule.next.setting
```

And see if the climate device loads.  Alternatively, add a schedule to that room using the app.

**Comment by LGO44** [comment]
OK with the release v3.0.17
Thank you

**Comment by msp1974** [comment]
Great. Closing issue.
