### ISSUE TITLE
Issue when executing REST call to get HeatHub secret key

### ISSUE THREAD

**Issue by brahmlategan** [asantaga/wiserHomeAssistantPlatform#200]
I get the following when executing REST call.

From Windows Powershell:

Invoke-RestMethod : Unable to connect to the remote server
At line:1 char:1
+ Invoke-RestMethod -Method Get -UseBasicParsing -Uri http://192.168.50 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Please assist.

Many thanks.

**Comment by msp1974** [comment]
Please try this method instead.

## Find your HeatHub Secret key

Before you can use the component you need to find the HeatHub secret key, this involves a couple of steps.

On your hub, press the setup button and the led should flash.

Use your pc, phone or tablet and connect to the wifi SSID (you should now see available) that is Wiserxx_xxxxxx

Once connected to this wifi network, open your browser and go to http://192.168.8.1/secret

You can then copy your key and paste into the integration setup screen.

**Comment by msp1974** [comment]
@brahmlategan did you resolve this?

**Comment by brahmlategan** [comment]
Yes, thank you very much. Used the wrong IP in the first place, silly me.
