### ISSUE TITLE
R3.0.17RC1 - Humidity sensor removed

### ISSUE THREAD

**Issue by toddstar** [asantaga/wiserHomeAssistantPlatform#203]
R3.0.17RC1 seems to have removed the humidity level sensor/attribute from the roomstats signal entities. Can you add it back please?

V16
![IMG_20211229_045300](https://user-images.githubusercontent.com/22575856/147628600-0b842aa5-7b63-4958-a3dc-8a5b68e59b3d.jpg)

V17
![IMG_20211229_045607](https://user-images.githubusercontent.com/22575856/147628716-258979a6-7b53-42da-b739-7f29f67cd58a.jpg)

**Comment by msp1974** [comment]
Apologies @toddstar. Possible copy paste error.  This will come back in next update.

**Comment by msp1974** [comment]
v3.0.18 released which reinstates these attributes.

**Comment by toddstar** [comment]
> v3.0.18 released which reinstates these attributes.

Thank you :-)
