### ISSUE TITLE
Smart Plug Switch is unavailable when it's has an unassigned location in Wiser App

### ISSUE THREAD

**Issue by robtesch** [asantaga/wiserHomeAssistantPlatform#209]
Hi there,

With the latest version (v3.0.18), I had a bunch of issues with duplicate entities after HA prompted me that is had "found new stuff". It resulted in me removing all of the wiser stuff, and re-adding it again completely fresh.

Anyway, after doing all of that, I noticed that my smart plug was working, except for the actual switch to turn it on and off. After reading the error below, I realised that my plug had not been assigned to a location in the wiser app. Assigning it to a location in the wiser app solved the issue and the switch became usable again. I don't like to have it assigned to any specific room because I regularly move it around as needed. Could the code be changed here so that it does not assume that every entity has been assigned to a room?

```
Exception in async_update_state when dispatching 'WiserHeat037599-HubUpdateMessage': () Traceback (most recent call last): File "/config/custom_components/wiser/switch.py", line 182,
in async_update_state await self.async_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492,
in async_update_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541,
in _async_write_ha_state extra_state_attributes = self.extra_state_attributes File "/config/custom_components/wiser/switch.py", line 420,
in extra_state_attributes attrs["room"] = self._data.wiserhub.rooms.get_by_id(self._smartplug.room_id).name AttributeError: 'NoneType' object has no attribute 'name'
```

Thanks for your great work!

**Comment by msp1974** [comment]
Rob,Yes we can sort that. Have done so for all other devices but missed smartplug.  Will be in next update.Sent from my Galaxy

**Comment by robtesch** [comment]
Amazing work, thanks!

**Comment by asantaga** [comment]
just fixed this in V3 (https://github.com/asantaga/wiserHomeAssistantPlatform/commit/cf0d2bebcf6d2e387915093b974e62f00f327aa6), it will go out in the next release.

**Comment by asantaga** [comment]
Fixed in latest V3
