### ISSUE TITLE
RoomStat and iTRV temperature

### ISSUE THREAD

**Issue by dunxd** [asantaga/wiserHomeAssistantPlatform#211]
I'm trying to establish the difference between iTRV measured temp, and the more accurate measurement from a room stat.

Prior to v3 the roomstat temperature was available separately from the room (although I don't recall if the figures were different, or if the iTRV temp was available).

It would be useful to be able to access each iTRV measured temperature, the room stat measured temperature, and the calculated temperature for rooms with multiple devices capturing the temp in order to see if there is a significant difference. This would help with calibration, if there is indeed a need for it.

**Comment by msp1974** [comment]
The roomstat temp is still available on the roomstat signal entity as an attribute (providing you are on v3.0.18).  Not the most obvious place but where it was previously.  It may change in future versions.

The TRV temps are not attributes on the trv signal but we could add in next release (think only applicable if more than one device in a room)

**Comment by asantaga** [comment]
Makes sense to put it on the  trv signal..

Marking as ENH, may do this later

**Comment by LGO44** [comment]
Regarding the temperature in the iTRVs, it seems to me that it is supplied by the thermostat to which it is linked, the iTRV modules do not have their own temperature measurement system.
Wiser Heat Hub copies the setpoint and temperature from the thermostat to the iTRV.
In the case of Heating Actuator the mecanism is the same.

**Comment by asantaga** [comment]
if the iTRV is not linked to a roomstat then it will report the temperature at the trv, if there is a linked roomstat then yes the room temperature is from the roomstat
