### ISSUE TITLE
Plug energy use error  

### ISSUE THREAD

**Issue by rlewis187** [asantaga/wiserHomeAssistantPlatform#223]
I noticed this morning that my Wiser plug somehow  used 472 kWh of energy yesterday. Bit shocked as it's only powering an Echo show, a lamp and a phone charger and would have turned off at 08.00 when we left for school.
![wiser](https://user-images.githubusercontent.com/80640955/150483074-dfb0f2a0-93d1-402b-ba2d-df8aaca48893.png)

My total home energy use was according to Hildebrand Glow integration was a more realistic sounding 9.29 kWh.

We had an engineer round trying to repair faults on my broadband line yesterday afternoon (may or may not be related) and saw quite a lot of internet down and back up again, although I did check and everything was working just fine locally while the internet was out.

Looking at the power consumption history for the plug, there are 7 dips where HA recorded the total power consumption as 0, but then it went back to around 67 kWh:
![Total History](https://user-images.githubusercontent.com/80640955/150483747-b3c0bd94-1321-45ba-8939-317d72c2a343.png)

This is interesting because 7 * 67 = 472 (roughly), the numbers may have changed slightly as the day went by.

What I think has happened is the Wiser integration reading for some reason drops to 0, and then the recovers the correct value,  energy monitor then records the difference between 0 and the correct value. After doing it 7 times, we end up with 472ish kWh.

**Comment by rlewis187** [comment]
The engineer has just completed the repair of my broadband which required a disconnect again. The same thing has happened, I have another 67.52 kWh usage on that plug again today. It lines up with my broadband coming back on again.

**Comment by asantaga** [comment]
oooo how much fun! 

This is a wiser bug  :-( , we just report the data from the plug itself  (see line 501 of sensor.py)

Not a lot we can do alas... :-( 

Mark?

**Comment by msp1974** [comment]
This is to do with how HA does long term sensors.  It is an increasing value from the hub and therefore if it goes to 0, HA adds the next value to the historic count.Not really sure why you would have got a zero reading from the hub as if integration couldn't get update it will not update sensors so hub must have provided a 0 reading.  Think this is more a hub issue as such but will think if there is some adjustment that could be made to prevent this.Otherwise, I think you can clear the LTS data but not sure how. See if there is anything on Google.Sent from my Galaxy

**Comment by asantaga** [comment]
What about if we dont report 0 figures? ie ignore them?

**Comment by msp1974** [comment]
Not sure how we can ignore 0 values as we have to give it some value as the sensor will update its state with a valid hub update.I think we would have to hold the previous value and validate any new value against it. Given that this should only increase, any lower value must be wrong.  So a long as you don't get a zero value when you restart HA this would prevent it doing this.Sent from my Galaxy

**Comment by rlewis187** [comment]
I don't know anything about coding tbh so not really going to be much help, but could you convey a zero to a null value? 
HA long term statistics have to work the way described, my total energy use resets every year so effectively returns to zero at midnight nye

**Comment by rlewis187** [comment]
Sorry, typing on my phone and accidentally hit close.

**Comment by asantaga** [comment]
I'll look into if we can access historical data from the integration.. best approach is to check 
if previous value is lower than new value AND date is the same (So that midnight it resets normally).. might be tricky..

**Comment by msp1974** [comment]
This has a fix in v3.0.20 but does not factor reset at midnight NYE.  Will amend this in next version - but think we have time until next NYE!

**Comment by msp1974** [comment]
@rlewis187 this should now be resolved.  I amended the api to return -1 if the hub does not return a value and only update the sensor value if the api value is greater than -1.  This is in v3.0.21.  Not sure if you can test the scenarios you have previously to see if now resolved?

I'll close for now, but please re-open if you can still recreate/see the issue.
