### ISSUE TITLE
Only boost from set point when in Auto mode

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#225]
Good evening,

I was wondering if you could stop the automatic boost when the setpoint is changed in "Heat" mode? It doesn't seem to make sense as it stops following the schedule. 

Cheers!

**Comment by msp1974** [comment]
Not 100% clear on what you mean.  Can you explain, maybe with a screenshot.  AFAIK we dont have anything that does an auto boost in heat mode.  The climate device shows what the hub says.

**Comment by LewisSpring** [comment]
Here's a video. 
https://user-images.githubusercontent.com/40576482/152305435-80f0ec79-553e-449d-96fd-9cd47acbe42d.MOV

**Comment by asantaga** [comment]
Lewis, I just tested this out on both 3.0.19 and 3.0.20. and in both cases it went to idle - override (which is correct).

Do you by any chance have an automation running ?

Check the log files see if there is anything there which can shed light on this.

**Comment by LewisSpring** [comment]
Hi @asantaga , no automations or logs. I'm running 3.0.20

**Comment by msp1974** [comment]
Ok this is a little weird, particularly that the 3.0.20 version included an update to the api which cancels any overrides (of which boost is just a timed override) when changing mode.  I see in your video when you select off mode, it still shows boosted.

Also, it registers that the room is boosted when the setpointorigin value from the hub shows FromBoost.  As such, your hub must be returning this for some reason.

Think we need to start with some basics:

1) Can you confirm the version of firmware on your hub
2) Can you confirm what version was last working correctly.
3) Can you get a json output form the hub for each of the different changes in your video so we can see what the hub is showing.
4) Also, set your default boost time to 30 mins in the integration config and try the same tests again as in your video and tell me if the boost time is still 60 mins.

**Comment by asantaga** [comment]
Another idea, is to install an older version of the integration and see if this changes anything

**Comment by LewisSpring** [comment]
1. Heathub is running 3.8.8
2. I've followed asantaga's idea, and tested all v.3 versions
- v.3.0.20 - Affected 
- v.3.0.19 - Affected 
- v.3.0.18 - Affected
_I've oberserved the same thing for all of these versions:
Switching from heat (with boost) to auto cancels the boost.
Turning the temperature down/up while in heat mode still boosts (my feature request). 
Switching from auto (with boost) to heat does not cancel the boost._

3. Could you tell me how to get the JSON output please?
4. Same behavior as before, **even if boost time is 30 minutes.**

**Comment by msp1974** [comment]
See this link to get json output.
https://github.com/msp1974/wiserHeatAPIv2/blob/master/docs/info.md#command-line-interface

**Comment by msp1974** [comment]
Just had a late night moment of clarity.  I think you have the setpoint mode set to boost instead of normal in the integration config.  This was created for a specific use case for google home and for most people this should be set to normal.

I also have to correct a previous mis-statement.  The cancel all overrides when changing mode is in the next version of the api not the one released with v3.0.20.  It will cancel boost if you click auto mode but not if you select heat or off while boosted.  This will be fixed in next release.

**Comment by asantaga** [comment]
@msp1974 mis-statements to our users.... ... tut tut tut :-) :-) :-)

Lewis does Marks suggestion work?

**Comment by LewisSpring** [comment]
Ah, I do have the set point mode as boost, I wasn't aware it was for Google Home users.
I thought it was a useful feature. I noticed that because "heat" mode turns off the schedule, it didn't make sense to boost when changing the temperature, so I made this issue/feature request. 

Would implementing my feature request cause issues for Google Home, or be possible?
If either, then It's not that much of a deal. 

Glad the API fix will be implemented, that fixes that bug.

**Comment by msp1974** [comment]
The issue with Google home is that it doesn't support auto mode, so the setpoint is actually designed to boost in heat mode to give something close (he says with a grimace!) to increasing the setpoint in auto mode where it will go back at next schedule event.  As such, yes it will break this.

If you give us some more info on why you like this and what you are trying to do, there may already be another way to do this or we could come up with a possible solution.

**Comment by msp1974** [comment]
@LewisSpring I had an idea to have another setpoint mode to allow to boost only in auto mode.  Next release will have this option for you.

**Comment by LewisSpring** [comment]
Please accept my apologies for my late response.

Thanks for clarifying about Google Home, that makes sense.
Your idea is exactly what I was thinking of, many thanks for doing that for me!

Cheers, both.

**Comment by msp1974** [comment]
Lewis,  just released v3.0.21 that adds a boost only in auto setpoint mode.  Let me know how you get on.

**Comment by LewisSpring** [comment]
That works exactly how I was thinking, Thank you so much for your time!
