### ISSUE TITLE
Unable to set temperature?

### ISSUE THREAD

**Issue by mzealey** [asantaga/wiserHomeAssistantPlatform#227]
I have looked at all 3 devices listed (hub, and 2 for the room thermostat) but I'm unable to see an entity that allows me to actually set the currently requested temperature?

![image](https://user-images.githubusercontent.com/6083471/152496733-9636c6ba-470d-44d2-984a-b004707cab9f.png)

Additionally, in the hub page I see the options to boost heating/hot water which work great. I also see option to set the away temperature etc.

Perhaps I'm missing something obvious or need to config a new entity, but it's a little strange if this doesn't auto-appear. 
I'm running 3.0.19

**Comment by msp1974** [comment]
You need to add the top one in your images to a thermostat card on a Lovelace dashboard.

**Comment by asantaga** [comment]
If you add the top one to your lovelace Ui (click add to love lace) you can then click on the TRV and set the temperature
Alternatively add a "climate" card, bound to the trv and voila job done.

will close, let us know if you need more help

**Comment by mzealey** [comment]
Yes this is great thank you, I wasn't aware that HA would be showing it so different in entities compared to lovelace.
