### ISSUE TITLE
Define Events integration can fire

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#228]
As part of a future release we plan to fire "events" from the integration. This issue is to gather what events would be useful to integrators
Each event will have the entity_id which has triggered the event and the state.

Whilst you could monitor these changes using automation, its tedious to write an automation which says, let me know when a trv needs a battery, as you need to query each trv, events, coded in python, will solve this and make automations simpler.

- TRV battery reached low value
- TRV network changes from direct to repeater (be good to know this so you can check if the repeater is still in the right place)
- TRV state changes from Idle to Heating
- TRV boosted (for Richard )

**Comment by rlewis187** [comment]
I'd like an event for 'the Mrs just boosted the heating again' 😂
