### ISSUE TITLE
Wiser HeatHub discovered multiple times

### ISSUE THREAD

**Issue by Stealthii** [asantaga/wiserHomeAssistantPlatform#229]
Before  setting up the Wiser HeatHub, the integration is constantly adding new discoveries of the HeatHub to my integration dashboard.

<img width="1716" alt="Screenshot 2022-02-12 at 20 19 36" src="https://user-images.githubusercontent.com/998920/153727103-a328f0ae-51d0-4bee-962b-787f0b81c422.png">

Home Assistant and the HeatHub are on the same VLAN and network. No other networks are configured on either system.

Once I configured the system using hostname directly (avoiding these), no more discoveries were added to the list.

**Comment by asantaga** [comment]
Sounds like autodiscovery is going bonkers.. 
DId u upgrade from 2.x?

**Comment by Stealthii** [comment]
This was a fresh install of Home Assistant, I'd previously used 2.x!

However, I've verified this bug is not with this integration or HASS - turns out there was a mis-configuration in my mDNS setup that led to these repeated bounces. Addressing that solved the issue.

**Comment by jacekowski** [comment]
I have a similar issue that has appeared recently, already configured HA and hub working for months and now i seem to always have one discovered (with -XX added to name, where XX is a number that seems to be incrementing)
