### ISSUE TITLE
Humidity + LTS humidity from room sensor

### ISSUE THREAD

**Issue by mzealey** [asantaga/wiserHomeAssistantPlatform#230]
Hi there, is it at all possible to get humidity as an entity + LTS entity from the room sensor? I'm on 3.0.19 and I don't see any hints about it even though I see in the source code that this should be possible.

Thanks!

**Comment by msp1974** [comment]
The humidity value available from a roomstat is an attribute on the roomstat device signal entity (i know that doesn't make a lot of sense but it was historically there and it is on the list to do something that does make more sense - just not yet  done).  As such, you can add this to an entity card by choosing the roomstat signal entity and the current_humidity attribute.

Not sure exactly what you are asking re LTS entity.  Do you mean in general - in which case there is a switch on the integration configuration to enable them.  If you mean on the humidity - this is not there at present.

**Comment by mzealey** [comment]
> Not sure exactly what you are asking re LTS entity. Do you mean in general - in which case there is a switch on the integration configuration to enable them. If you mean on the humidity - this is not there at present.

Yes exactly - I have it switched on for temperature etc so it would be very nice to have it for hum as well.

**Comment by msp1974** [comment]
OK, will look to include that in a future release.  For now though, you can use an entity card with attribute to see and have history in HA as below - obviously change the entity to match yours.

```
type: entity
entity: climate.wiser_lounge
attribute: current_humidity
unit: '%'
```

**Comment by msp1974** [comment]
This has been fixed in v0.3.22beta which got released last night.  I am awaiting test results from the community on the main issue this was updated to fix but if you want to download and test it then please feel free.  Likely this will be a full release later in the week.

**Comment by msp1974** [comment]
v3.0.22 has now been released that provides a Humidity LTS sensor on roomstat rooms.

**Comment by mzealey** [comment]
This is working great thank you!

**Comment by mzealey** [comment]
Out of interest, does anyone have stats of how well the wiser humidity sensor performs compared to a normal one? I'm testing with a zigbee sensor which seems pretty accurate, have placed it next to the wiser sensor for the past day and temperature readings are identical, however the wiser is reporting about 10 percentage points higher rel-humidity than the temp+hum sensor - 65% vs 55% which is a pretty significant difference.
