### ISSUE TITLE
Support for Wiser Under Floor Heating Controller

### ISSUE THREAD

**Issue by murrayb8** [asantaga/wiserHomeAssistantPlatform#234]
If possible could support please be added for the wiser underfloor heating controller device type as it currently is not found in home assistant when using this integration. All other wiser heating entities(trvs, range extender plugs, thermostats) are correctly identified.
Attached is the json response output relating to the underfloor heating controller running in my home heating system.
[wiser_underfloor_heating_json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8136979/wiser_underfloor_heating_json.txt).

**Comment by msp1974** [comment]
Brendan,

 

We can certainly look at adding this.  Just for clarity, how do you expect to see this in HA.  I am assuming you can control the heating/schedule in the kitchen but I do not have one of these to understand fully how it links into the Wiser system, so some detail would be very helpful in the form of… I would like to see sensors for this, can you include attributes on existing x entity for that, I want to be able to control that etc.  

 

Thx Mark

**Comment by murrayb8** [comment]
Hey Mark, 

I am using HA for monitoring purposes only at the moment but yes I assume I can control the rooms/thermostats which utilise the underfloor heating controller. What would be great is to get the underfloor heating controller show up as an entity which is similar to the "Wiser HeatHub Signal" type used for the wiser heating hub. Things like signal strength should be available. I can do a pull request for this if this limit functionality addition sound reasonable to start with? I have attached a full json output with all rooms and devices. 
[wiser_underfloor_heating_json_full.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8144294/wiser_underfloor_heating_json_full.txt)

Brendan

**Comment by msp1974** [comment]
Brendan,Yes this sounds fine.  Will need an update to the api to include UFH as a device type and then a tweak to the integration to include its signal sensor and various attributes but not too big a job.  Also nice to find someone who has this to be able to include it.Im away this weekend (going to the England Wales game - v excited!) but can have a look at adding to the api as i have a few issues now to make changes for and then if you want to do a PR for the integration that would be great.Will let you know when api available.MarkSent from my Galaxy
-------- Original message --------From: Brendan Murray ***@***.***> Date: 25/02/2022  20:12  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform ***@***.***> Cc: Mark Parker ***@***.***>, Comment ***@***.***> Subject: Re: [asantaga/wiserHomeAssistantPlatform] Support for Wiser Under Floor Heating Controller (Issue #234) 
Hey Mark,
I am using HA for monitoring purposes only at the moment but yes I assume I can control the rooms/thermostats which utilise the underfloor heating controller. What would be great is to get the underfloor heating controller show up as an entity which is similar to the "Wiser HeatHub Signal" type used for the wiser heating hub. Things like signal strength should be available. I can do a pull request for this if this limit functionality addition sound reasonable to start with? I have attached a full json output with all rooms and devices.
wiser_underfloor_heating_json_full.txt
Brendan

**Comment by msp1974** [comment]
@murrayb8 I have been working on adding UFH support to the api but need a full hub output to properly test this.  Please could you follow the below instructions and provide your full outputs to this issue.

https://github.com/asantaga/wiserHomeAssistantPlatform/blob/dev/Readme.Md#providing-your-hub-output-as-json-files

**Comment by murrayb8** [comment]
Hey Mark, I hope you had a good weekend at the rugby! Please find attached the 3 files. I made a small change to anonymise the geo position. 
[schedules-20220301-220320.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8165117/schedules-20220301-220320.json.txt)
[network-20220301-220320.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8165118/network-20220301-220320.json.txt)
[domain-20220301-220319.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8165119/domain-20220301-220319.json.txt)

**Comment by msp1974** [comment]
Thanks - that was so much easier to test and fix bugs.  As a note - the geo position is not yours in the file - it is the lat long of the hottest place on earth - just my little joke! ;-)

I have now updated the api to support UFH and the dev branch has v3.0.23 of the Wiser integration that will now show your UFH device with usual switches and signal sensor.  Are you able to update from dev branch in your HA and test this?  Ie not via HACs but via a git pull?

**Comment by msp1974** [comment]
@murrayb8 any update on this?

**Comment by murrayb8** [comment]
Hey Mark, apologies for the delay in testing this. For testing this is it possible for me to install the dev version of the Wiser integration manually in parallel with my existing HACS installation or does it need to replace my HACS installation?

**Comment by asantaga** [comment]
Installing two versions (dev/prod) in the same HA instance isnt (easily) possible. I recommend installing another HA instance for testing, just start it up on a different port.

**Comment by msp1974** [comment]
@murrayb8 - unfortunately, there is now other changes in the dev branch which needs to later version of the api (which isn't published yet).

I will finish off the work I am doing over the next few days and maybe release a beta version of 3.0.23 which you can download via HACs and test.  If there are issues, you can then go back to 3.0.22 in HACs.

Will let you know.

**Comment by msp1974** [comment]
@murrayb8 - just release v3.0.23 that has support for UFH.  Can you upgrade to this version and let me know if all working ok.

**Comment by murrayb8** [comment]
I have upgraded to v3.0.23 and the UFH Heating entity shows up correctly and the fields look good to me. Thanks for the prompt change to make this available, while it does not have many controllable fields it is useful for monitoring the connection/signal strength over time along side the other Wiser devices.

**Comment by msp1974** [comment]
Great. Will close issue but feel free to raise any probs you find or new features desired.
