### ISSUE TITLE
Error when Room has no Schedule

### ISSUE THREAD

**Issue by walshtj** [asantaga/wiserHomeAssistantPlatform#236]
I'm on the latest version (v 3.0.21). Wiser Hub firmware v3.8.8
If a room has no associated schedule I get the following error. 

```
2022-02-27 18:24:00 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.wiser_spare_room fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/config/custom_components/wiser/climate.py", line 167, in async_update
    await self.async_fire_events()
  File "/config/custom_components/wiser/climate.py", line 379, in async_fire_events
    "scheduled_temperature": self._room.schedule.current_setting,
AttributeError: 'NoneType' object has no attribute 'current_setting'
```
If I attach a schedule to the room there are no errors.

**Comment by asantaga** [comment]
bug :-( 
The hubapi shouldn't be returning null, i'l try and look at that later

**Comment by walshtj** [comment]
If I can help with any tests or anything please ask.

I'm not sure if this is relevant but there was a [commit](https://github.com/asantaga/wiserHomeAssistantPlatform/commit/822213fb1a8ab50525588c7fffc599ede83dc151) on 28/Dec/21 related to rooms with no schedule. It was in the `extra_state_attributes` function while this error seems to originate from the `async_fire_events` function.

Thanks for an amazing integration!

**Comment by msp1974** [comment]
This has been fixed in v0.3.22beta which got released last night.  I am awaiting test results form the community on the main issue this was updated to fix but if you want to download and test it then please feel free.  Likely this will be a full release later in the week.

**Comment by msp1974** [comment]
v3.0.22 has now been released to fix this issue.  Thanks for raising.

**Comment by walshtj** [comment]
thank you for fixing the issues so quickly.  Much appreciated.
