### ISSUE TITLE
API-WiserAPI from Feller/Schneider useful?

### ISSUE THREAD

**Issue by james-cook** [asantaga/wiserHomeAssistantPlatform#241]
In the discussion/issues on light and shutter controllers etc. I get the impression that the API is reverse engineered (postman, wireshark...). 

Is this the case or is this software based on an official API in the public domain?

**Comment by msp1974** [comment]
It is reverse engineered

**Comment by james-cook** [comment]
> It is reverse engineered

I was "researching" my recent problem of not being able to download the Wiser app (https://github.com/asantaga/wiserHomeAssistantPlatform/issues/217) and although I could not  even see (let alone download Wiser Heat/Home) I noticed Wiser apps were being offered to me by Feller AG in the playstore.

I also noticed the issues here on light and shutter controllers which also led me back to Feller AG. 


The reason I asked the question is that Feller AG publish a/the WiserAPI on github: https://feller-ag.github.io/wiser-api/

Useful?

**Comment by msp1974** [comment]
Not sure how this relates to the wiser heat hub in UK and wiser gateway in Europe but dont recognise any of this api per your link.

**Comment by james-cook** [comment]
Oh well 😀

I had hoped this would open up access to more Wiser devices.

Feller AG/Schneider is the Swiss Drayton  - they supply "Wiser" light and shutter controllers but other devices too...  In Germany it is Merten/Schneider.

They all have a "wiser hub" and the issues here on shutters and light suggested to me that the heat hub can schedule these devices too...

I'll try and pick up some Feller Wiser devices when  I'm back in Switzerland.

**Comment by james-cook** [comment]
This API might prove useful at some point. Schneider Wiser products may converge.
