### ISSUE TITLE
Next Schedule Change attribute missing underscores

### ISSUE THREAD

**Issue by gooberstank** [asantaga/wiserHomeAssistantPlatform#243]
Love this integration, however, I've noticed the "next schedule change" attribute doesn't have any underscores like the other attributes so I can't return it to show in a widget.

I've manually found the issue myself and updated it on my local install but it would be great to resolve at source so when updated it doesn't revert back to being broken.

Thanks again for all of your work on this.

**Comment by msp1974** [comment]
This will be fixed in the next release however, not sure why this stops you using it on a widget - can you explain?  Thx

**Comment by msp1974** [comment]
Fixed in v3.0.23
