### ISSUE TITLE
Battery States

### ISSUE THREAD

**Issue by charlesomer** [asantaga/wiserHomeAssistantPlatform#251]
Hi,

Not sure if this is expected behaviour or not but when a TRV reaches critical it has a state of -20 instead of 0. Low represents a state of 0 instead. I was expecting 0 to represent critical and not functioning correctly? Apologies if this is mentioned somewhere!

Thank you
Charles

**Comment by asantaga** [comment]
We get this info from the trv itself.  We could tweak it/enrich it in the integration but what would you want it to be?

**Comment by charlesomer** [comment]
Hmm, to be honest I think Wiser doesn't do a very good job at reporting and handing battery status. I don't know if this is just my setup but I've noticed that when a TRV reaches "critical" status, it's actually so drained it won't move at all so should probably be the same as the room thermostats which go to "no signal" or something similar. As a result, when a TRV is at the critical level the Wiser system can get stuck in a situation instantly where it is calling for heat all the time (very expensive!) because it can't heat a room up as it thinks the TRV is open when it isn't. I've reported this a few times but it still exists :( Hence wanting to set up battery monitoring in HA.

But anyway! I think "Low" does actually represent 20% when the TRV is at 2.6v but once it gets to 2.5v it goes to 0 maybe? So 2.5v could be 10% perhaps. Unless I've got that wrong! :)

**Comment by msp1974** [comment]
I have now seen this myself.  It is to do with our value for min battery voltage. I think this may have changed on the hub over time to be 2.4v now instead of 2.5.  This needs correcting in the api.  Will add to todo list.

**Comment by msp1974** [comment]
This is fixed in v3.0.24 released today.

**Comment by charlesomer** [comment]
Fantastic thank you!
