### ISSUE TITLE
EU Version - Lights and Shutters support

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#252]
As this version run completly fine on my dev platform,  I want to deploy this version on my Raspberry PI platform:

Initial situation : 
wiserplatform : V3.0.22
wiserHeatAPIv2: V0.0.25

- Installation of Wiserheat API V0.0.27 by clone the github repository (dev branch) and install it

![image](https://user-images.githubusercontent.com/95585425/162395134-763cc7fd-f3cc-45e5-8028-17cbfc6d40fb.png)

- update the manifest.json in custom-componenets/wiser : 
{
  "domain": "wiser",
  "name": "Drayton Wiser Integration for Home Assistant",
  "iot_class": "local_polling",
  "config_flow": true,
  "documentation": "https://github.com/asantaga/wiserHomeAssistantPlatform/blob/v3/Readme.Md",
  "dependencies": [],
  "codeowners": ["@asantaga", "@msp1974"],
  "version": "3.0.22",
  "requirements": ["wiserHeatAPIv2==0.0.27"],
  "zeroconf": [{"type":"_http._tcp.local.","name":"wiser*"}]
}

- restarts HA, the integration doesn't start...
 2022-04-07 14:58:32 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.27: ERROR: Could not find a version that satisfies the requirement wiserHeatAPIv2==0.0.27 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26)
ERROR: No matching distribution found for wiserHeatAPIv2==0.0.27
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

-  To control my installation process I do the same with the version 0.0.26 of wiserHeatAPI
 
![image](https://user-images.githubusercontent.com/95585425/162396749-773b2468-479a-4457-982e-10162c19b627.png)

 Installation of Wiserheat API V0.0.26 by clone the github repository  and install it

![image](https://user-images.githubusercontent.com/95585425/162397028-5392e06c-3a55-4114-9e18-84c51ee52470.png)

update the manifest.json with the version 0.0.26
Everything run fine ( with the features of the version 0..26)
Then I update the Wiser platform with the version 3.0.24
![image](https://user-images.githubusercontent.com/95585425/162397808-d4f63eb1-5a7a-4211-a299-f1d2dbdbf350.png)

Everything run according to the version V0.0.26 of wiserHeatAPIv2.

For me at this time the installation process of wiserHeatAPI is OK .

**Comment by msp1974** [comment]
v0.0.27 has just been published.  It has a lot of changes in it and I wanted to test it before doing so.  If you repeat what you have done previously, it should now work.

**Comment by msp1974** [comment]
I have also moved 3.0.24 into the dev branch now so that we can do a beta release and then ultimately a final 3.0.24 release with all the new lights and shutters functionality.

Please checkout the dev branch going forward for all testing.  Thx

**Comment by msp1974** [comment]
@LGO44 - I have now released this as a 3.0.24Beta release.  You should just be able to install this in your production environment via HACs.  Let me know how you get on.

Thanks for all your help on this big change.
Mark

**Comment by LGO44** [comment]
@msp1974 
Thanks for all your job.
I have installed the wiserHeatAPIv2 (0.0.27) 👍 
I have installed the wiserPlatform v3.0.24 beta : the installation is OK 
I am testing the schedules, now. very good idea to provide the name of the schedules (I think the a user the scheduleId , very usefull to manage the schedules inside the integration of course, doesn't mean anything ).
We have an issue with the assign service , I am testing it deeper and I'll come back to you later today.
Christian

**Comment by LGO44** [comment]
As I promised, here are:
 a report of the tests made 
 a file with the commands for light and shutters updated by the creation and the assignement of a schedule to a devic
[test schedule services 3 0 24 beta.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8474395/test.schedule.services.3.0.24.beta.pdf)
[Wiser light commands 2022 04 12 .pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8474397/Wiser.light.commands.2022.04.12.pdf)
e
@msp1974 If something is not clear for you feel free to ask some precisions
Christian

**Comment by LGO44** [comment]
@msp1974 
the schedules are very interesting for my point of view, what do you think about an entity "schedule" that could show the schedule id, the schedule name, the device following this schedule, and the next stage...?

**Comment by RPI-PMK** [comment]
How easy would it be to have the Wiser integration use scheduler-card (https://github.com/nielsfaber/scheduler-card) ??

I am using this card for Hue light and other controls. Is it just a case of getting the format correct or a big job??

**Comment by msp1974** [comment]
@LGO44 I have been looking at something similar.  Since we built this integration, how Wiser/Schneider deal with schedules has changed and now you can attach 1 schedule to multiple rooms/devices, whereas before it was a schedule for the room/device.

HA doesn't really have a good way of handling this but I am planning more functionality/improvements to make it easier to manage - including some way to see what is attached to what and what other shceuldes exist that are not attached.  Stay tuned!

**Comment by msp1974** [comment]
@RPI-PMK there is an open issue relating to be able to have a UI capability to manage schedules but, yes this is a big job and Angelo and I are not adept at UI coding.

The scheduler-card, I don't think is suitable for this purpose as it is designed to manage the schedule itself and not pass this onto something else (the Wiser hub) to manage.

As per the open issue, we are very happy to take a PR for anything relating to this.

**Comment by msp1974** [comment]
> As I promised, here are: a report of the tests made [test schedule services 3 0 24 beta.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8474395/test.schedule.services.3.0.24.beta.pdf)
> 
> a file with the commands for light and shutters updated by the creation and the assignement of a schedule to a device [Wiser light commands 2022 04 12 .pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8474397/Wiser.light.commands.2022.04.12.pdf)
> 
> @msp1974 If something is not clear for you feel free to ask some precisions Christian

@LGO44, Thanks for your testing of this.  I have found 2 issues relating to this.

1) An update in the code in the v3.0.24Beta version to better handle the assign - already pushed to dev branch
2) An update in the wiserHeatAPIv2 code as it seems you need to use the type as Level and not Shutter or Lighting if you assign an existing schedule but use Shutter/Lighting if you are creating one.  This will need me to push an update to v0.0.28 which I will do over the weekend, so you can test the dev branch against it.

**Comment by LGO44** [comment]
> 1. An update in the code in the v3.0.24Beta version to better handle the assign - already pushed to dev branch

@msp1974 , sorry but I don't see the modification

**Comment by msp1974** [comment]
Sorry I hadn't pushed it.  Have done a lot more rework on the assign function today and also updated the wiserHeatAPIv2 to 0.0.28.

Testing notes:
The assign schedule service can do 3 things:
1) Assign existing schedule from an entity to another (ie link them to same schedule) - select entity in service call
2) Assign a schedule by id to and entity - select Schedule Id in serivce call
3) Create a new schedule and assign to an entity - do not select entity or schedule id in service call

There is a little bit of further tidying up to do but I think it all now works.

**Comment by msp1974** [comment]
@LGO44 did you get chance to test this?

**Comment by LGO44** [comment]
@msp1974 , sorry Mark I am away from home this week, I'll test the modifications next Monday and Tuesday.

**Comment by LGO44** [comment]
@msp1974 
I've tested your last improvement on Zigbee netmap : Grate!
only one small remark if you use Home assistant with the dark background it's ok , bit if you use it with a white background you cannot read anything.
The solution is in the settings **zigbee2mqtt-networkmap-label-color: rgba(255, 255, 255, 1);**  but is static.

**Comment by msp1974** [comment]
Yes. This is really a limitation of the card (which don't really have an intention of creating our own) but the instructions say to modify these to suit.

As a side note, I will get to look at the previous test results and resolve those issues next weekend.  Thanks

**Comment by msp1974** [comment]
@LGO44 - I have made a number of changes to the copy and assign schedule services based on your testing feedback.  Would you please be able to test again for me and let me know of any issues that still remain.  Thanks

**Comment by LGO44** [comment]
@msp1974 ,
here are the results of the tests of the last version of wiserHeatApi 0.0.29 and wiserplatform 3.0.24 beta2 .
We have always some issues with the assign feature on lights and shutters.
 I want to assign a schedule to an entity and it's another entity that is modified. 
According to the logs, it seem to run well.
 see the results in the pdf file
I also join the wiser_data 
[wiser_data 2022 05 07.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8645690/wiser_data.2022.05.07.zip)
[test schedule services 3 0 24 beta 2022 05 06.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8645692/test.schedule.services.3.0.24.beta.2022.05.06.pdf)

**Comment by msp1974** [comment]
Sorry i know this is painful but it seems the way you need to handle level schedules is a bit strange.  Would you be able to repeat each of the tests that did not work with the wiser app and capture the commands with http canary so i can see exactly what should be sent to the hub.  Thanks

**Comment by LGO44** [comment]
> Sorry i know this is painful but it seems the way you need to handle level schedules is a bit strange. Would you be able to repeat each of the tests that did not work with the wiser app and capture the commands with http canary so i can see exactly what should be sent to the hub. Thanks

I wan't be at home next week , of course I 'll make the tests with canary.

**Comment by LGO44** [comment]
@msp1974 ,
here are the  results of my tests with the traces.
 
There is a mismatch between the deviceId and the id of each device category.
I hope that all will be understandable , if not feel free to ask any question that should help you.
[test schedule services 3 0 24 beta 2022 05 12.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8681024/test.schedule.services.3.0.24.beta.2022.05.12.pdf)

**Comment by msp1974** [comment]
@LGO44 this is fantastic thank you.  Seems that the issue relates to what device id to use.  Seems these lights and shutters were coded by someone completely different form the rest of the hub firmware as it all works so differently.  I will work on sorting this over the weekend - I think I have got my head around it now.

**Comment by msp1974** [comment]
@LGO44 right, after some head scratching I think this should now work correctly.  The use of 2 different device ids for these lights and shutters depending on what you want to do is crazy poor!

It should now be using the correct device Ids in the schedule functions.  If you can test again for me.  

If this works, think I will cut off development of this 3.0.24 version and release it as there is lots of goodies in it now.

Thanks

**Comment by LGO44** [comment]
> @LGO44 this is fantastic thank you. Seems that the issue relates to what device id to use. **Seems these lights and shutters were coded by someone completely different form the rest of the hub firmware as it all works so differently.** I will work on sorting this over the weekend - I think I have got my head around it now.

Sure, the hub is used for a home automation platform for the Schneider group and the different parts customize the platform

**Comment by LGO44** [comment]
@msp1974 i won't be at home next week so I'll make the test on next friday or saturday, sorry for the delay

**Comment by msp1974** [comment]
Apologies, i have been very busy with other things the last few weeks. I was hoping to do last weekend but thi k i may ger time this weekend to do.  Appreciate your patience.

**Comment by msp1974** [comment]
Ok released v3.0.24.  Will do something about the lights and shutters assign issue in another release.

**Comment by msp1974** [comment]
Christian,  I have now added a 3.0.25beta in the dev branch that includes the schedule card.  I have had to make quite a lot of changes to existing code in the api and integration to support this. Would you be able to test existing functionality with lights and shutters as well as the services and the new card?  Let me know of any issues and also anything you think can be improved on the card. Thanks

**Comment by msp1974** [comment]
Should add, one of the outstanding items is to make it multi lingual.  So, at the moment it is just in English.  I know that's why we get a bad name with the French! ;-)

**Comment by LGO44** [comment]
> 

Mark of course I will make all the tests, It will on next week as I'm not at home this week.

**Comment by LGO44** [comment]
@msp1974 , what a very good job!
Here are the results of my first tests and use

If you need more informations or if you need more test feel free to come back to me
Christian
[Wiser test v 3 0 25 beta.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8994030/Wiser.test.v.3.0.25.beta.pdf)

**Comment by msp1974** [comment]
@LGO44 - Christian,  I am going to close this long issue now.  Let me know if you think we have anything outstanding.
