### ISSUE TITLE
OpenTherm integration

### ISSUE THREAD

**Issue by psblah** [asantaga/wiserHomeAssistantPlatform#256]
It would be good to get OpenTherm statistics from the hub when this connection method is used.

example output from endpoint:

```
{"chFlowActiveUpperSetpoint":800,"chFlowActiveLowerSetpoint":350,"dhwFlowSetpoint":550,"dhwEnable":true,"featureActions":{"ModulationOnboarding":true},"Enabled":true,"transmitter":{"messagesSentCount":51728},"receiver":{"decodingErrorsCount":615},"operatingMode":"OTplus","preDefinedRemoteBoilerParameters":{"dhwSetpointTransferEnable":true,"maxChSetpointTransferEnable":false,"dhwSetpointReadWrite":true,"maxChSetpointReadWrite":false,"dhwSetpointUpperBound":650,"dhwSetpointLowerBound":350,"dhwSetpoint":2560,"maxChSetpointUpperBound":750,"maxChSetpointLowerBound":200},"ch1FlowSetpoint":350,"ch1FlowEnable":false,"ch2FlowSetpoint":350,"ch2FlowEnable":false,"operationalData":{"RelativeModulationLevel":0,"ChPressureBar":13,"Ch1FlowTemperature":330,"ChReturnTemperature":320,"Dhw1Temperature":275,"SlaveStatus":0},"roomTemperature":191,"roomSetpoint":190,"TrackedRoomId":7}%
```

api endpoint:  `/data/opentherm/`

**Comment by msp1974** [comment]
@psblah I have reworked your PR on the api a little bit to fit more into the structure of the api and then added attributes for ch_flow_temperature, ch_pressure_bar and ch_return_temparture to the Wiser Heating sensor.

This is currently in the dev branch but will let you know when this is released.  Hopefully in the next week or so.

**Comment by psblah** [comment]
it works :D thank you for the quick implementation!

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/11039928/167224556-12ff1b3c-5a8d-4b96-a7f1-52568f99ee97.png">

**Comment by asantaga** [comment]
NICE.. I wish my boiler was opentherm compliant

Curiosity, can you post charts of the ch_flow,pressure and return temp etc.. curious to see what he data looks like...

**Comment by asantaga** [comment]
Closing issue as marks already merged into dev
