### ISSUE TITLE
IP Address changed to static, how to update ?

### ISSUE THREAD

**Issue by diginfo** [asantaga/wiserHomeAssistantPlatform#258]
Probably all said in the title - I needed to set a fixed IP address and now the wiser hub cannot be found.

How can I update the IP address, or preferably use the device's mac address instead ??

Many Thanks

**Comment by asantaga** [comment]
The hubs address will be in ~/.homeassistant/.storage/core.device_registry
Go into this file hunt the old one down and change it

**Comment by diginfo** [comment]
Thanks very much.

I just looked through the config, and the device is actually setup by it's mac address and not it's IP.

but when I look at the ha logs I see:

```
2022-06-03 11:22:39 ERROR (MainThread) [custom_components.wiser] Connection error trying to update from Wiser Hub 192.168.1.109.  Error is HTTPConnectionPool(host='192.168.1.109', port=80): Max retries exceeded with url: /data/v2/domain/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7f6fd910>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

I have restarted ha several times and also restarted the dns but it's still picking up the old IP address.

```
ha dns restart
```

Any suggestions ??

**Comment by msp1974** [comment]
Did you solve this?  2 ways to do.
1) Remove the integration and readd (easiest way)
2) Edit the config entry file at ~/.homeassistant/.storage/core.config_entries.  This is where ip i fo is held.

**Comment by msp1974** [comment]
@diginfo did you resolve this?

**Comment by diginfo** [comment]
This was never really fixed.

The only solution was to uninstall and re-install from scratch, loosing all previous configurations.

**Comment by asantaga** [comment]
In my setup I have the IP address in my core.config_entries

![image](https://user-images.githubusercontent.com/2940224/175276797-c0804dfa-58f4-4327-a17a-91079bc84ac8.png)

Ive always set up the integration via IP address and not mDNS (AutoDiscovery) due to weirdness in my lan setup...

The alternative was to reinstall from scratch but that shouldnt loose your current config as the integration creates the entities with the same name...

**Comment by asantaga** [comment]
Did you also reset the hub?

**Comment by diginfo** [comment]
Thanks for helping.

No I did not need to reset the hub, just had to remove and re-add the integration and yes it was discovered by mDns, I wish now that I had added it manually.

But I guess that I can edit the core_config and manually add the IP address, I have added entries to this before, it seems to be OK ?

**Comment by asantaga** [comment]
Strange it shouldnt have lost your config though as the names of the entities is based on the trv names etc..

yeah, do you want a fuller version of the config file or do you have enough in my screen grab?

**Comment by asantaga** [comment]
I think this issue is resolved, closing for now, @diginfo  let me know if there is something else we should be doing here.
