### ISSUE TITLE
Request - Humidity

### ISSUE THREAD

**Issue by majones319** [asantaga/wiserHomeAssistantPlatform#259]
Hello. I used to be able to get humidity from my roomstat, but I can't seem to see it anymore. Can you please advise what to do? Many thanks.

**Comment by msp1974** [comment]
Its an attribute on the roomstat signal sensor.  You can use the entity card to show it by selecting the roomstat signal entity and the humidity attribute.

Know this doesnt make total sense and is on todo list to maybe make own sensor entity.
