### ISSUE TITLE
add new device update HA

### ISSUE THREAD

**Issue by motclem** [asantaga/wiserHomeAssistantPlatform#260]
If I add a new device to the wiser set up for example I knew TRV how do I update the integration so that it picks it up?

**Comment by msp1974** [comment]
Just restart HA and it will be there.

**Comment by motclem** [comment]
> Just restart HA and it will be there.
I renamed a device and restarted expecting it orefresh but didn't in the end I have removed and reinstalled the integration

**Comment by msp1974** [comment]
Assuming this is resolved. Will close for now.
