### ISSUE TITLE
TRV battery sensor falsely reporting 0% after upgrade to v3.0.24 

### ISSUE THREAD

**Issue by Duke-Box** [asantaga/wiserHomeAssistantPlatform#265]
After upgrading from 3.0.23 to 3.0.24 I noticed SOME of my TRV battery sensors reported 0%, even though the attributes showed the voltage was above 3.0 volts and the status attribute was "normal"

I have four TRV's, the other 2 are reporting correctly, however each time revert and then upgrade the affected sensors are random

When I reverted to 3.0.23 all is correct

I m on hassio V 8.2
Supervisor 2022.5.03
core 2022.6.6
pi4 64bit

first example

![conserv-1-battery-sensor after upgrade](https://user-images.githubusercontent.com/38861692/174890419-480c848c-77f4-4983-bb0a-60c67cd1396a.png)

2nd 

![battery sensor kitchen 2](https://user-images.githubusercontent.com/38861692/174890542-38f0173e-9e5e-468d-98b6-3726dbff23c1.png)

EDIT:

is it because they are above 3Volts? 
The 1st example didn't appear until i replaced the batteries with ne ones ( as you can see in the screenshot)

**Comment by msp1974** [comment]
Thanks @Duke-Box. This was raised and will be fixed in next release. It is only issue if your batteries report over 3v.  We made a change in 3.0.24 to fix another issue with these batteries and dint factor over 3v as a scenario.

**Comment by msp1974** [comment]
Fixed in v3.1.0 which has just been released.  Thanks
