### ISSUE TITLE
Wiser Schedule Card - Beta Issues

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#267]
For discussion on wiser card development beta testing

**Comment by msp1974** [comment]
@msp1974 , what a very good job!
Here are the results of my first tests and use

If you need more informations or if you need more test feel free to come back to me
Christian
[Wiser test v 3 0 25 beta.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8994030/Wiser.test.v.3.0.25.beta.pdf)

_Originally posted by @LGO44 in https://github.com/asantaga/wiserHomeAssistantPlatform/issues/252#issuecomment-1167579721_

**Comment by msp1974** [comment]
@LGO44 
Christian,
I have put an update in dev to fix:

1) Correcting schedule type for creating schedule
2) Ability to add a slot to a day with no slots
3) Ability to delete last slot in a day

Needs a little bit of tidying up but if you could see if 1 fixes the issue.  Thx

**Comment by msp1974** [comment]
@LGO44 can you also please send me your json output with both the schedule that would not save when editted and a new blank schedule created with the app so i can look at those 2 issues.  I suspect the first one is to do with the needed support for sunrise/sunset but the other one may need a rethink of how we create/display schedules.  Thx

**Comment by LGO44** [comment]
@msp1974 
here are the results of the tests of the fixes
[Wiser test v 3 0 25 beta _2.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8999767/Wiser.test.v.3.0.25.beta._2.pdf)

•	My  json output with a new blank schedule created by the integration:  wiser_data 1.zip
•	My  json output with a new blank schedule created by the wiser home app:  wiser_data 2.zip
•	In these files the schedule shutters id 4 name prog1 has a with duplicate times and could not be saved, you are right this schedule use sunset

[wiser_data 1.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8999768/wiser_data.1.zip)
[wiser_data 2.zip](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8999769/wiser_data.2.zip)

**Comment by msp1974** [comment]
Great thx.  Will look at maybe adding a default schedule when creating a light/shutter.

For the following, think I maybe wasn't clear.

1) Adding a slot to a day with no slots.  If a day has no slots ie only a hashed bar, you can now click on the hashed bar and it will allow you to add a slot.  You can only click on the hashed bar if no other slots on that day.

2) Deleting the last slot in a day.  I mean if there is only one slot in a day, you can now delete this to leave you with a day with no slots.  Then 1 applies.

**Comment by LGO44** [comment]
by consulting the log I can see an error, that I can't understnd the origin

_2022-06-28 15:00:11 INFO (MainThread) [custom_components.wiser] Wiser Hub data updated - WiserHeat03F9E3
2022-06-28 15:00:11 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_state when dispatching 'WiserHeat03F9E3-HubUpdateMessage': ()
Traceback (most recent call last):
  File "/config/custom_components/wiser/light.py", line 173, in async_update_state
    await self.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/wiser/light.py", line 139, in extra_state_attributes
    attrs["next_day_change"] = str(self._device.schedule.next.day)
AttributeError: 'NoneType' object has no attribute 'day'_

Do you have any idea?

This error disappeared when I suppress the light schedules with no day configured ( after a creation)

**Comment by msp1974** [comment]
OK, following issues should now be fixed:

1) Not able to edit shutters or lighting schedule after creation
2) Error in HA for a schedule with no slots

Going to work next on Sunrise/Sunset (enhancement 4) and then slider (issue 6) and language support (issue 5)

When you get chance to check the creation of shutter and lighting schedules, if you can let me know if it now looks good.  I decided to fix it in the api that it adds a default empty schedule when creating and if created in the app and is completely blank, it substitutes this blank schedule to the card.  Seemed the simplest way to do.  Also means after first save, a full schedule is now there.

**Comment by LGO44** [comment]
> OK, following issues should now be fixed:
> 
> 1. Not able to edit shutters or lighting schedule after creation
> 2. Error in HA for a schedule with no slots
> 
> Going to work next on Sunrise/Sunset (enhancement 4) and then slider (issue 6) and language support (issue 5)
> 
> When you get chance to check the creation of shutter and lighting schedules, if you can let me know if it now looks good. I decided to fix it in the api that it adds a default empty schedule when creating and if created in the app and is completely blank, it substitutes this blank schedule to the card. Seemed the simplest way to do. Also means after first save, a full schedule is now there.

1. Not able to edit shutters or lighting schedule after creation

- the creation of a schedule initialize a slot per day

![image](https://user-images.githubusercontent.com/95585425/176271174-1d28294a-ca27-4d41-a85d-d0111bce17e8.png)

- I cannot edit a day (hashed) . **Where have I to click to edit a slot?**

2.  It seems ok

Traces of creation and save schedule
[Wiser test v 3 0 25 beta _3.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/9004636/Wiser.test.v.3.0.25.beta._3.pdf)

**Comment by LGO44** [comment]
> Im not sure this is the right version of the card. I think the browser caches it and you need to do a shift F5 to refresh. Card should be version 1.0.11 which you can see if you edit dashboard and select edit on the card to see options.
> 
> Clicking on the hashed bar should show a blue border round it. It maybe same colour as the bars. I would turn off use theme colours for now. May need to change border colour.
> 
> For info, i am away for a few days now but will pick up on further enhancements when back on Tuesday.
> 
> Thanks for your help so far.

@msp1974,
Thanks, after a Shift F5 everything is OK now. I hadn't though to reset the browser...
Sorry for disturbing

**Comment by LGO44** [comment]
@msp1974 
The more I use the wiser schedule tool, I wonder how we did it before?
With the tool the name of the schedule is the item to choose, It should be nice to have the ability to edit the name of the schedule.

**Comment by LGO44** [comment]
@msp1974 , I have tested your last job for the special time Sunrise and Sunset that 's OK for me, it run very well.
Very well also or the  RENAME action , thanks

Another time you produce a good job.

**Comment by msp1974** [comment]
Perfect.  Im going to get this released over the weekend.  I have been also recreating the zigbee network card so that may make it into this release too, if i get some time to finish it tomorrow.  As always, thanks for your help in testing.

**Comment by msp1974** [comment]
Closing now as v3.1.0 released with card in it.
