### ISSUE TITLE
HA core 2022.7.0 - now logging deprecation warning against wiserHomeAssistantPlatform

### ISSUE THREAD

**Issue by southseaboy** [asantaga/wiserHomeAssistantPlatform#268]
Updated to 2022.7.0 and am now seeing the following log warning

> Logger: homeassistant.components.number
> Source: components/number/__init__.py:220
> Integration: Number (documentation, issues)
> First occurred: 11:23:59 (1 occurrences)
> Last logged: 11:23:59
> 
> custom_components.wiser.number::WiserAwayModeTempNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
> 

I am running version 3.0.24 of the component

**Comment by msp1974** [comment]
Thanks. We will fix this in an update soon.

**Comment by msp1974** [comment]
Just realised that this is now broken for HA lower than 2022.7.  ARGGG!!!

**Comment by robtesch** [comment]
Yep. I'm sure you know this already but just in case:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/wiser/__init__.py", line 400, in async_setup_entry
    resource_id = await hass.data['lovelace']["resources"].async_create_item({"res_type":"module", "url":url})
AttributeError: 'ResourceYAMLCollection' object has no attribute 'async_create_item'
```

**Comment by msp1974** [comment]
@robtesch what version of HA are you running?

**Comment by robtesch** [comment]
2022.7.2

**Comment by msp1974** [comment]
This seems to be an issue about how you have your dashboard configured.  It seems to be using YAML instead of JSON storage.  I will open this as a different issue.  Thx

**Comment by robtesch** [comment]
Oh ok, thought it might be the same issue since it seemed to be working before (but I might have not noticed that it wasn't working). Yes, I do use Yaml for the dashboard.

**Comment by msp1974** [comment]
This is new code in v3.1.0 to 'install' the schedule card.  Opened new issue #270

**Comment by msp1974** [comment]
Had to revert this in v3.1.1.  HA team will not do anything about this so we will leave it with this warning until nearer the time we need to an then support a min of 2022.7 for releases post that.

**Comment by msp1974** [comment]
I'm hoping I have now found a way of getting rid of the errors but still supporting HA 2022.6 and 2022.7.  This was part of v3.1.2
