### ISSUE TITLE
wiser platform 3.1.2 :schedules

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#276]
@msp1974 : sorry to disturb you.

**First point:**  The copy feature runs correctly . It's very easy to use.

**Second point:** It's now impossible to modify the level of a schedule : the slider is no more displayed

![image](https://user-images.githubusercontent.com/95585425/181016418-10f8b9b9-3e9f-4da2-ba8b-670dc0b77f05.png)

**Third point:** creating a new schedule

- After having created a new schedule all the day are filled with hashed and unknown
- When I select one day the border is now in a different color and it's very visible . Thanks
- I cannot add a new set, only copy the selected day to another ...

![image](https://user-images.githubusercontent.com/95585425/181018748-8ad522b3-edc5-4b86-ac46-df0e9f435cec.png)

- to modify the setting of one day we have to : first select the day an second to click on the border to activate the "ADD button"  without any effect,  see the second point
![image](https://user-images.githubusercontent.com/95585425/181020885-f08d934a-889f-4c87-9790-1273916b619a.png)

**Comment by msp1974** [comment]
Is this just on level schedules or all?  This is strange as non of this bit has changed.  Let me have a look at it later.  I presume you have this in sidebar or dashboard mode on a tab?  What browser are you using?

**Comment by msp1974** [comment]
Hmm. There is something wrong here.  Have pulled the release for now and will look before re-releasing.

**Comment by LGO44** [comment]
> Is this just on level schedules or all? This is strange as non of this bit has changed. Let me have a look at it later. I presume you have this in sidebar or dashboard mode on a tab? What browser are you using?

I use either safari or firefox on Mac, or edge or firefox on windows.
I use a dashboard
This issue is only on light and shutter

**Comment by msp1974** [comment]
@LGO44 - ok I have fixed these issues and re-released v3.1.2 if you want to update.  Sorry about that!

**Comment by msp1974** [comment]
BTW - the new diagnostics option is in Settings -> Devices & Services -> Select the Wiser Devices -> Select any device in the list -> See the download diagnostics button.  This is now consistent with how a number of other integrations do it.

![image](https://user-images.githubusercontent.com/11211952/181224613-de54f2e5-14e3-4222-b385-da573abaa86b.png)

**Comment by LGO44** [comment]
> @LGO44 - ok I have fixed these issues and re-released v3.1.2 if you want to update. Sorry about that!

**@msp1974** Thanks, everything fine now. 
I tried with : 
- safari and firefox on macOs 
- edge and firefox on windows

Mark, only those who do nothing do not make mistakes

**Comment by LGO44** [comment]
> BTW - the new diagnostics option is in Settings -> Devices & Services -> Select the Wiser Devices -> Select any device in the list -> See the download diagnostics button. This is now consistent with how a number of other integrations do it.
> 
> ![image](https://user-images.githubusercontent.com/11211952/181224613-de54f2e5-14e3-4222-b385-da573abaa86b.png)

**@msp1974**  I asked the question much too quickly. With a little thought I found the solution, sorry for that.

**Comment by msp1974** [comment]
Great.  will close this.
