### ISSUE TITLE
Feature Request: After cycling room off and on again, set room temp to previous one

### ISSUE THREAD

**Issue by Kalma-House** [asantaga/wiserHomeAssistantPlatform#281]
Hi,

Right now, when a room is in manual mode and I turn its thermostat in HA off and then on, the temperature is set to the scheduled temperature (if the room has a schedule assigned, even if it is not supposed to be followed), or it is set to 5º (if the room has no schedule assigned).

My proposal is that, in manual mode, the thermostat should remember tha last 'on' temperature and return to it whenever it is turned back on. If the thermostat has no last 'on' temperature on record (maybe because HA was restarted), the temperature should be set to 5º (as in when the room has no assigned schedule), but never to the scheduled temperature, which it may cause its unintended activation. 

Thanks,

Javier

**Comment by asantaga** [comment]
As mark mentioned , we;d have difficulty in storing previous values between restarts.. but its possible...

**Comment by msp1974** [comment]
This in 3.1.3 in dev but currently uses scheduled temp if nothing is stored.  Will look at maybe adding a config option to use min temp so that it doesn't change too much for others.

**Comment by msp1974** [comment]
Javier, just released v3.1.3 which will store the manual/heat temp.  There is also a config option to be able to set the value to use if non stored.  Min Temp is an option in this you will need to select.

Let me know if this works how you expected.

**Comment by Kalma-House** [comment]
Great news. I will test it tonight. Amazing responsiveness. Thanks.

Javier

**Comment by msp1974** [comment]
Excellent.  Will close this issue.
