### ISSUE TITLE
New Feature: Add ability to change Hub IP address via config options

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#282]
Add ability to change IP address via config options as currently only way with HA is to edit config file or delete and re-add integration.

In 3.1.3 in Dev

**Comment by msp1974** [comment]
Released in 3.1.3

**Comment by diginfo** [comment]
I know this is closed and implemented, but it would also be nice to be able to set the port, especially useful when the hub is not on the LAN and accessed via port forwarding.
