### ISSUE TITLE
OnOff Schedule with midnight times causes  'Unknown Error'

### ISSUE THREAD

**Issue by jbeardon** [asantaga/wiserHomeAssistantPlatform#284]
Hi Guys.
I was attempting to create an 'on-off' schedule to force a Wiser smartplug to be permanently on (i.e a single 'On' event at midnight or any other time). I was able to delete the standard on-off events until I was left with the single 'on' but on saving, the on changed to off! I then went back to the wiser app - it was showing the event as being 'on'.
I copied the schedule within the app to all days, then refreshed the HA dashboard, clicked on the schedule entry and it just displays an 'Unknown error'
It's a minor inconvenience but would be good if I could manage all schedules within HA.

Really appreciate your work on this integration - it really is first class :-)
Thanks, John

**Comment by msp1974** [comment]
John,  i have tried to recreate the issue you describe and do see the first part if i set the schedule from 00:00 to on and then save it turns it to off.  Will look into this.

Cant seem to recreate the unknown error.  Can you describe a little more step by step or post a video showing this.

Can you also confirm (from my testing) if the time is anything but 00:00 then it doesn't have an issue.

Thanks

**Comment by msp1974** [comment]
Dont worry, i miss read your explanaition.  I have recreated both issues.  Will look into this.  As said above, seems if you dont use 00.00 hours it works ok.

**Comment by jbeardon** [comment]
Thanks Mark - Totally understand this sort of schedule can cause an issue (especially at 00:00). I will re-adjust accordingly.
Thanks again
John

**Comment by msp1974** [comment]
John,  v3.1.3 just released should solve your issue.

**Comment by jbeardon** [comment]
Fantastic. Thank you so much!

**Comment by jbeardon** [comment]
@msp1974 Just updated and can confirm the issue is fixed. Really appreciate this Mark.
Thank you.
John
