### ISSUE TITLE
v3.1.3 - Zigbee Map Card Issue

### ISSUE THREAD

**Issue by jbeardon** [asantaga/wiserHomeAssistantPlatform#286]
Hi Guys.
After updating to the current version, the Zigbee Map card seems to have disappeared. Showing as 'does not exist' on dashboards and is no longer in the list of cards. I've cleared cache/reloaded etc.
![image](https://user-images.githubusercontent.com/14904316/183281745-506c7fe7-b0ee-43f7-b670-77bbb1ed8252.png)

**Comment by msp1974** [comment]
Somebody else reported this happened on 3.1.2 on the HA forum. Can you please do 3 things for me.

1) check it is still listed in resources. 3 dots to edit dashboard, 3 dots again for manage resources.  Should have entry for wiser/zigbee-network-card.js

2) check in your browser developer console for errors and provide it if so.

3) provide a diagnostic output from an integration device so I can try and recreate your setup.

Thanks

**Comment by jbeardon** [comment]
Hi Mark.

1. Yep - still listed in resources.
2. Developer tools: 
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED http://192.168.69.35:8123/wiser/wiser-zigbee-card.js

mwc-list-item-base.ts:224 Uncaught (in promise) http://192.168.69.35:8123/wiser/wiser-zigbee-card.js

3. Diagnostics attached.
[config_entry-wiser-4556f750dc4f30b6bf068574687fb044.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/9276673/config_entry-wiser-4556f750dc4f30b6bf068574687fb044.json.txt)

**Comment by msp1974** [comment]
I dont know if this is to do with HAOS but it is complaining the gzip version of the card provided in the integration is not gzip.  Can you try deleting the gzip versions in the wiser/frontend diredtory, leave the js versions, and refresh tour browser then.  Or reboot if that doesnt work.  We provided the gzip versions as HA seems to create them but not update when the js file changed.

Will look more into why this is happening but hopefully this will fix it for now.

**Comment by jbeardon** [comment]
I've deleted the gzip and refreshed - issue resolved.
Very odd that it's not affecting the schedule card that is on the same dashboard.

Thanks again Mark.
Cheers
John

**Comment by msp1974** [comment]
This should be resolved in 3.1.4.  Let me know if you have issue again.  Closing issue.
