### ISSUE TITLE
Network map not showing - present in resources

### ISSUE THREAD

**Issue by Carl-mgb66** [asantaga/wiserHomeAssistantPlatform#288]
Hi, as I raised on the Home Assistant forum the network map has recently disappeared even though the /wiser/wiser-zigbee-card.js exists in the Resources.

I attach the diagnostics file from my system as requested.

I see the following error in the Chrome developers tools: Uncaught SyntaxError: Unexpected token ‘{’

[config_entry-wiser-4ea6f1a99b2e4e257aa05e1204f81824.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/9277253/config_entry-wiser-4ea6f1a99b2e4e257aa05e1204f81824.json.txt)

**Comment by msp1974** [comment]
OK I have run up a HAOS 8.4 VM and have been able to recreate this issue.  Let me work on it and I will provide an update when fixed.

**Comment by msp1974** [comment]
Ah ha.  This is the same issue as issue #286, however seems to give a very different error in your case.  Both these seem somehow related to running on HAOS I think.

Anyhow, if you look in the custom_components/wiser/frontend folder, you will see the js and js.gz files that are the cards.  Can you delete the js.gz files and do a shift-f5 browser refresh and tell me if that now works.

**Comment by v966732** [comment]
> Ah ha. This is the same issue as issue #286, however seems to give a very different error in your case. Both these seem somehow related to running on HAOS I think.
> 
> Anyhow, if you look in the custom_components/wiser/frontend folder, you will see the js and js.gz files that are the cards. Can you delete the js.gz files and do a shift-f5 browser refresh and tell me if that now works.

Confirmed, this resolved the issue for me

**Comment by Carl-mgb66** [comment]
I've deleted the .gz files and that has fixed it for me as well.

**Comment by msp1974** [comment]
Should be all good in 3.1.4 now.  Closing but let me know if you encounter issue in future.

**Comment by Carl-mgb66** [comment]
Thanks. Great work.
