### ISSUE TITLE
Enh :Add support for HACS

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#29]

**Comment by asantaga** [comment]
From @jchasey 
``` In the meantime can we have support for custom component cards```

Im not familiar with custom component cards...  need to look into this, what additional features will they provide?

**Comment by jchasey** [comment]
Sorry, request was not clear. This has been superseded now by HACS. It allows easy discovery and install of custom components prior to them being supported officially.
To add this project in, just need to do a PR to add the repository here:

https://github.com/custom-components/hacs/blob/data/repositories/integration

Full details are here:

https://custom-components.github.io/hacs/developer/general/

The extra info.md etc are optional so can be added later (I'm happy to create those)

**Comment by asantaga** [comment]
Awesome, yeah I did see HACS and was going to add support for it.. looks cool

changing EH to add support for HACS

**Comment by asantaga** [comment]
Done! in 1.5a  https://github.com/asantaga/wiserHomeAssistantPlatform/commit/8e60e318ea8144e7a91bff9e895c3108acb5d31c
