### ISSUE TITLE
Zigbee Network Map not showing in Lovelace 'Add Card'

### ISSUE THREAD

**Issue by DavidqStokes** [asantaga/wiserHomeAssistantPlatform#290]
I am running the current version of this integration (which I love) and have just added the Schedule Card to my front end (works fine)

However, the Zigbee Network Map card is not showing in the list of cards when I try to add a card via the UI (using 'Add Card'). The  Schedule Card shows up just fine.

The /wiser/wiser-zigbee-card.js resource is showing in my list of resources and the wiser-zigbee-card.js and wiser-zigbee-card.js.gz files are both in the custom_components/wiser/frontend/ folder.

I am on the 2022.8.5 release of HA

Any help anyone can give would be appreciated

**Comment by msp1974** [comment]
Can you delete the .gz file and refresh your browser.

**Comment by DavidqStokes** [comment]
Done, and that did indeed fix the issue. Thanks for the help (and keep up the good work on the integration)
