### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by eaitken51** [asantaga/wiserHomeAssistantPlatform#291]
When configuring & entering obtained secret key, recieve error within integration "Unknown error connecting to the Wiser hub. Please check the logs."

Logs

Logger: custom_components.wiser.config_flow
Source: custom_components/wiser/config_flow.py:59
Integration: Drayton Wiser Integration for Home Assistant ([documentation](https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/README.md), [issues](https://github.com/asantaga/wiserHomeAssistantPlatform/issues))
First occurred: 12:00:02 (1 occurrences)
Last logged: 12:00:02

Unknown error connecting to Wiser Hub
Traceback (most recent call last):
  File "/config/custom_components/wiser/config_flow.py", line 157, in async_step_zeroconf_confirm
    validated = await validate_input(self.hass, user_input)
  File "/config/custom_components/wiser/config_flow.py", line 59, in validate_input
    wiser_id = wiser.system.name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by msp1974** [comment]
This is because you have no schedules on your setup. Create a blank one and it should work. I will leave this issue open to fix this as it seems we have had this a few times recently.

**Comment by eaitken51** [comment]
I resolved it.

For context, I wanted to run this integration fully local without the need for Wiser Cloud service, however until you fully complete the set up process (including signing up for an account) in the Wiser app the integration will not function.

Not sure if this is a bug or feature of this integration, but it may be worthwhile adding to the documentation.

Closing bug.
