### ISSUE TITLE
Unable to set up dependencies of wiser. Setup failed for dependencies: hacs

### ISSUE THREAD

**Issue by briandorey** [asantaga/wiserHomeAssistantPlatform#292]
I have a new wiser hub and after copying the wiser directory into the custom components folder on a docker install of home assistant and restarting i am getting this error in the logs:

Unable to set up dependencies of wiser. Setup failed for dependencies: hacs

I am running Home Assistant 2022.8.4

If i try to add the integration manually it shows a popup with:

Error
Config flow could not be loaded: undefined

**Comment by msp1974** [comment]
I'm guessing you do not have HACs installed. In the manifest.json file, delete HACs and see if that works after a server restart.

**Comment by msp1974** [comment]
Fixed in 3.1.6

**Comment by msp1974** [comment]
v3.1.6 just released.  Closing issue.  thanks for raising.
