### ISSUE TITLE
Installation R3.1.4

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#293]
I receive a notification to install the last release R3.1.4.
After the update I'm still in version 3.1.3
![image](https://user-images.githubusercontent.com/95585425/187648505-22c739d2-abd5-4a21-91eb-2f8dca749254.png)

When I look to the github , the **dev** version is effectively  in **3.1.4** but the **master** stayed in **3.1.3**

**Comment by msp1974** [comment]
Oh. It is possible I didn't push the dev to master before released! Will do it as 3.1.5 tonight....and try to do properly this time! 😀

**Comment by LGO44** [comment]
Thanks Mark 😀
only those who do nothing, don't make any mistake!

**Comment by msp1974** [comment]
3.1.5 released with updates from 3.1.4 as should have been
