### ISSUE TITLE
wiser.remove_orphaned_entries not working?

### ISSUE THREAD

**Issue by jbeardon** [asantaga/wiserHomeAssistantPlatform#299]
Hi Guys.
I've been having issues with Wiser plugs I use as repeaters which have forced me to delete and re-add them to my hub. This has created a number of duplicate entries for the 2 plugs. I've tried calling wiser.remove_orphaned_entries in developer tools several times but the old, 'unavailable' devices are still listed.

Any ideas?

Cheers,
John

**Comment by msp1974** [comment]
Have you deleted all the entities under the device before running the service?

**Comment by jbeardon** [comment]
That has worked for most of the redundant devices but I have two that do not give me the option to delete the entities:
![image](https://user-images.githubusercontent.com/14904316/191197402-c127e9c5-5ac7-4b48-8bae-7cb530339d6b.png)

**Comment by msp1974** [comment]
Hmm.  I tried to recreate this by renaming one of my Smartplugs to leave a device that no longer exits.  However, I do get the option to delete so not sure why you don't.  I also don't get the entity is unavailable, I get
```
This entity is no longer being provided by the wiser integration. If the entity is no longer in use, delete it in settings.
```
Few questions:

1) Are you on the latest versions of HA (2022.9) and Wiser (3.1.5)?
2) Did you upgrade from Wiser v2.x to v3.x without removing and re-adding?
2) What exactly did you do to remove and re-add the smart plug?  Did you rename them or keep the same name?  What are the new entities name (ie are they a wiser_repeater_away_mode_turns_off_2)?
3) What is the other entity you have the same issue with? Did you do the same thing with this one?

This seems more of a HA type issue as such, but trying to work out if there is a scenario that we are creating that is making this happen.

**Comment by jbeardon** [comment]
Thanks Mark
Yes, latest versions
When I upgraded to 3, I did remove the existing and re-add.
I think point 3 is where the issue is - the ones I am having problems removing were removed from Wiser, then re-created with the same names. Entities of those devices are the ones causing issues, so you are probably correct in that it is more an HA issue.
It's no great shakes as there are now only 2 devices so I will just disable/hide them.

**Comment by msp1974** [comment]
If you want to delve into the innards of HA, you can delete them by removing out of the /config/.storage/core.entity_registry file.  Make a copy first just in case!!

OK, will close this for now but please feel free to reach out again if you need more help.
