### ISSUE TITLE
Expose next_day_change attribute to sensor.wiser_hot_water

### ISSUE THREAD

**Issue by TinyShark** [asantaga/wiserHomeAssistantPlatform#302]
Mentioned on the Home Assistant Community Forums:

`climate.wiser_[your_room]` exposes the attribute `next_day_change` for the designated schedule, whereas `sensor.wiser_hot_water` does not.

This attribute would be useful when displaying countdowns/info about when the schedule is going to be ON/OFF for hot water.

**Comment by msp1974** [comment]
This is now included in v3.1.6 that has just been released.  Also included is an attribute that gives the date and time of the next schedule change event that may help you with your card.
