### ISSUE TITLE
Schedule card collapse when changing time in 12 hour time format

### ISSUE THREAD

**Issue by cmillsy** [asantaga/wiserHomeAssistantPlatform#308]
Hi. 
When i try to edit the schedule card (i.e. move the time bars) the bar collapses to the left. If i then try to save it just reverts back to how it was. Altering the temperature works fine but i can't alter any of the times. Does anyone else have this issue?
Craig

**Comment by msp1974** [comment]
Can you provide more details as nit seen this.  What version of HA and integration? What device are you using/browser etc.  Can you provide screenshot, or better video, showing what is happening.  Thanks

**Comment by msp1974** [comment]
So this made me scratch my head as couldn't make it do it and then I saw you are using 12 hour time (which is supposedly supported).  Put mine in 12 hour time and yes, it does this horrible thing.

Will work on fixing this but if you put your HA to 24hr time, it works fine.  I guess most have 24hr time and this has not been raised before.  Thanks

**Comment by cmillsy** [comment]
Excellent. Thankyou. 24hr did the trick. I might revert back to 12Hr if i see any fixes but i'm perfectly fine with 24Hr. Thanks again.

**Comment by msp1974** [comment]
Next release will have the fix for this in it.

**Comment by msp1974** [comment]
Just released v3.2.0beta3 where this is now fixed if you want to go back to 12h time format.  If you don't want to install this beta at this time as it has a lot of backend changes then, full release will probably be sometime next week. Thanks for reporting.
