### ISSUE TITLE
Google home integration via home assistant 

### ISSUE THREAD

**Issue by dbrb2** [asantaga/wiserHomeAssistantPlatform#31]
Hi, 
I don't think this is a bug - more likely an error on my part: 

The drayton wiser integration is working well for me with home assistant 
I have home assistant linked into google home
If I ask google home "what is the temperature in the X room" is replies "the Wiser X room is set to auto"

This last statement is correct...but do you know how home assistant decides which bit of information it has from the Wiser unit to respond with when a request comes in from google home? It seems in this case it is responding with the unit state "auto" rather than it's temperature....

**Comment by asantaga** [comment]
Alas my Alexa's arent connected to HA and I dont have a Google Home device so I dont really have the means to debug this.......  

Wiser has native integration with Alexa/GoogleHome so you could use that instead?

If someone else has an Idea im happy to accept PRs or suggested code changes..

**Comment by asantaga** [comment]
Did u do any further r&d dbrb2?

**Comment by msp1974** [comment]
I have this working perfectly with Alexa.  If I ask the room temp 'she' replies correctly.  If I ask her to warm the room up or set a temperature also works.

My integration with HA and Alexa is via the HA cloud skill.  I expose the climate control for the room and (in the Alexa app) link this to a room group.  Are you using this or Hue integration?

**Comment by asantaga** [comment]
Closing this for now, dbrb2 reopen if its still an issue.

**Comment by dbrb2** [comment]
Apologies for not replying before the ticket was closed - as a bit of info:

* I do have some control via google home. For example, I can set the
temperature to X degrees
* Asking the room for temperature when the unit is set to "Auto" just tells
me "the room is set to Auto"
* If I set the room to "Heat/Cool" mode instead, Google responds with the
temperature as expected. Not sure what (if any) this has on the wider
Drayton system...
* Interestingly, when I set the temperature to "Off" it is interpreted by
HA as "-20" - which may just be down to how Deayton represents "off"...
