### ISSUE TITLE
Cannot assign a schedule using an automation

### ISSUE THREAD

**Issue by ben-willmore** [asantaga/wiserHomeAssistantPlatform#311]
In v3.2.0beta, when creating an automation, a schedule assignment such as the one below does nothing when run:

service: wiser.assign_schedule
data:
  schedule_id: 20
  to_entity_id: climate.wiser_spare_room

This works fine in v3.1.7

**Comment by msp1974** [comment]
Ben,  just release v3.2.0beta3 where this is fixed. Also added ability to assign by name which was requested on forum. Thanks for reporting.
