### ISSUE TITLE
Schedule card doesn't give feedback when assigning a schedule to a room

### ISSUE THREAD

**Issue by ben-willmore** [asantaga/wiserHomeAssistantPlatform#312]
Again, in v3.2.0beta only (3.1.7 is fine):

In the schedule card: 

Click a schedule then select a room -- assignment works (as shown in the Wiser app) but room does not get highlighted in the HA UI

**Comment by msp1974** [comment]
Ben,  just release v3.2.0beta3 where this is fixed.  Thanks for reporting.
