### ISSUE TITLE
No 'boost' mode

### ISSUE THREAD

**Issue by sonixtorm** [asantaga/wiserHomeAssistantPlatform#32]
Options for the room are 'Heat/Cool' and 'Auto'. Seem to be missing 'Boost'.

**Comment by phixion** [comment]
seems to be on to-do: https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/custom_components/wiser/climate.py#L68

**Comment by sonixtorm** [comment]
Thanks; good spot. I was going on the release notes which suggest it’s implemented. Seems to be some good info on how it was implemented in the OpenHab binding; I may have a hack about over Xmas.

**Comment by msp1974** [comment]
I have been playing around a bit with this and it seems the best way to do this is to implement PRESET modes.  This way you can differentiate between Auto, Manual and Off (ability to turn off also needs adding) as HVAC modes and whether running from the schedule, an override or boost.

I have modified code for this that I will make a PR over the next few days.

**Comment by asantaga** [comment]
I was thinking.. 

For Boost, I could query the current temperature and add 2C to it... For say 1Hr.. Would that work?

**Comment by phixion** [comment]
Thats exactly how wiser implemented it in their app in the quicksettings.

In their roomthermostats you can boost up to 5 or so hrs depening on how often you tap the damn button. I dont think thats useful but thats just me. Maybe make boost_time configureable by the user with a 1hr default?

**Comment by asantaga** [comment]
@phixion ,  Mark (@msp1974 ) is your friend here and has implemented not only boost (+2C or whatever u want) but also a number of presets for the time. 

Checkout the latest 1.7 release.

**Comment by asantaga** [comment]
implemented in 1.7

**Comment by sonixtorm** [comment]
Great work; thank you 👍

**Comment by phixion** [comment]
awesome! Thanks @msp1974 and @asantaga have a nice christmas!
