### ISSUE TITLE
Rooms with no devices display in the UI

### ISSUE THREAD

**Issue by sonixtorm** [asantaga/wiserHomeAssistantPlatform#33]
A room that I had created in the Drayton Mobile App shows in the HA UI, even though all devices have been removed and it is no longer visible in the Drayton UI.

**Comment by asantaga** [comment]
Hey there,

I just checked this out and I cant reproduce :-( 

I also tried to add the room in the app, query the data from postman and then delete the room and the room does disappear.. so dunno why its still there...

**Comment by asantaga** [comment]
Closing this for now, @sonixtorm  let me know if this still persists..

fyi , just release a 1.7 release

**Comment by sonixtorm** [comment]
Thank you for the update and the great work on this integration. I’ll try adding/removing the room in the Wiser app in case it’s legacy from an old version that didn’t tidy up properly.
