### ISSUE TITLE
What happened to the schedule and Zigbee Map custom elements?

### ISSUE THREAD

**Issue by mormor1971** [asantaga/wiserHomeAssistantPlatform#330]
I just noticed that the Wiser Schedule and Wiser Zigbee map custom elements has disappeared from my Wiser Heat dashboard, is this something that has happened to others or do I need to investigate why they disappeared from my HA install?

This is what I see now:

![image](https://user-images.githubusercontent.com/21991482/204086429-c2f59c5c-5601-45e9-8f39-40ab1825d010.png)

Any ideas on how to troubleshoot this?

**Comment by msp1974** [comment]
Both js files should be listed in the resources.  However, if you restart HA the integration will add them back if they are missing.

Note. If you have changed to yaml mode in front end you need to add to your resources file manually.

**Comment by mormor1971** [comment]
I have checked the wiser folder and the two scripts are not there so I went and redownloaded the Wiser integration and restarted HA but the error is still there as far as I can see.

**Comment by msp1974** [comment]
Ok, so the js files are in the custom_components/wiser/frontend directory. Are you saying they are not there?  Can you also send a screenshot of your resources list - edit dashboard and then same 3 dots, manage resources.

Also confirm you are not running in yaml mode for frontend.

**Comment by mormor1971** [comment]
The filed are in the frontend directory on the HA docker instance:

![image](https://user-images.githubusercontent.com/21991482/204164642-6436963b-1a81-4ffd-8b2a-0b4dbecb70f4.png)

I then went and changed the resources to include the frontend directory and restarted HA, after that I now have both the original resources and the edited resources so somehow the original /wiser/ resources got added back in during the restart?

![image](https://user-images.githubusercontent.com/21991482/204164728-254fc2fe-79d1-414e-afcd-8fb63e743ba3.png)


Where is the that configured, up until the other day the two .js filed=s were in the /wiser/ folder and not in the /wiser/frontend/ folder? I upgraded HA to the latest version on Tuesday and after that the two custom components moved into the /wiser/frontend folder.


I'm not using the yaml mode for this dashboard / frontend.

**Comment by msp1974** [comment]
The js files were always in that folder.  In resources /wiser is a url shortcut which points to the wiser/frontend folder.  As i said, the integration will always ensure that the resources are listed correctly at restart.  As such, remove the ones you added.  Do a shift F5 on your browser.

If you are still getting an error, then can you check in your browser console to see if you have any errrors causing the js files not to load.

**Comment by mormor1971** [comment]
I did just that and after a refresh, which HA actually prompted, the custom components were back again.

The resources still says /wiser/xxx though and not /wiser/frontend/xxx and if I look in the wiser folder on the HA server there are no symlinks to the frontend/xxx files so looking at the config as it is it should not work if you look at the file locations.

I'm not sure why it broke in the first place though but at least it's working again. 👍

**Comment by msp1974** [comment]
Glad its working again.  The resources are correct not listing frontend in the path.

It is not a symlink but a url endpoint that the integration creates within the HA application.  Thus when you call http://[homeassistant]:8123/wiser/filename.js  it looks in custom_components/wiser/frontend for filename.js.

Below is an extract of code from wiser/frontend/__init__.py where it sets this up.  This file also installs the correct paths in the resources, so you don't have to worry about it.

```python
# install card resources
    async def async_register_wiser_path(self):
        # Register custom cards path
        self.hass.http.register_static_path(
            URL_BASE,
            self.hass.config.path("custom_components/wiser/frontend"),
            cache_headers=False,
        )
```

```python
URL_BASE = "/wiser"
```

I am not sure what caused your issue but have not had any other reports.  I suspect a shift F5 may have fixed in the first place and that this was some caching issue of a previous version or something.
