### ISSUE TITLE
Erase orphaned devices and update

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#331]
If I rename a device , when I ask the integration to reload: 

-  it creates the new device
-  but it doesn't remove the previous one
-  the sensor *_signal, identify ... are not updated

We have to suppress the integration and reinstall it
[config_entry-wiser-2611920e504eb8d12ffebb9912438042.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/10096363/config_entry-wiser-2611920e504eb8d12ffebb9912438042.json.txt)

**Comment by msp1974** [comment]
It cant really remove the previous one itself.  There is the option to delete it through the devices and services.

![Screenshot_20221127-182406_Chrome](https://user-images.githubusercontent.com/11211952/204152892-47ad2f4f-0671-4de1-86a3-b615e5a0aa2b.jpg)


Once done, the sensors will belong to the correct device (may need restart)

**Comment by LGO44** [comment]
@msp1974 I search the way to do it, thank you another time for your help

**Comment by asantaga** [comment]
issue resolved
