### ISSUE TITLE
Electric Heat Switch

### ISSUE THREAD

**Issue by iwf10** [asantaga/wiserHomeAssistantPlatform#334]
As requested i'm raising the issue to support the data from the new Electric Heat Switch.

The use case is for supporting electric underfloor heating.   There are a number of items present in the diagnostic data which would be useful for this use case.    Further the limitation of the need for a room stat means it's not possible to control the floor properly in the Wiser App.  HA would resolve that issue.

The diagnostic file identifies a number of items which would be useful to service and some it would be useful to writeback to.   i'm assuming if the item can be written to within the Wiser App it should be possible to write to them via HA ( but I might be wrong).

The items shown within the HeatingActuator are

Sensortype - for information, can be changed in Wiser and is part of the initial config - no need to be able to update, though could be used to test whether Electric UFH is present
MeasuredTemperature : the actual probe floor temperature at the time of reading - read only
MinimumTemperature - the minimum probe floor temp to be meet  - should be able to write, it's the 'away' temp
MaximumTemperature : Max probe temperature - must be able to write and even schedule 
Offset : the temperature offset, affects MeasuredTemperature +- in 1 degree 

In use and because of the current requirement for the Room stat it's possible to set a high room stat target and a much lower MaximumTemperature.  The relay cuts out when MaximumTemperature, though the Room stat ignores that.   I need to test what effect setting MinimumTemperature has when the Room Stat is off.

The objective would be to be able to set MaximumTemperature to the desired floor temp either directly or via a schedule until such time as Drayton amend the app and remove the need for the Room stat.  But being able to access the data in HA would be start

Diagnostic file attached
[config_entry-wiser-0fb75f80a5816c23bbd112c3e7763414.json (4).txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/10154467/config_entry-wiser-0fb75f80a5816c23bbd112c3e7763414.json.4.txt)

**Comment by msp1974** [comment]
OK, few things if you could help me with.

1) Adding the parameters to api is fine but do need ranges of the min/max temps and also the offset temp to be able to control the ranges allowed.
2) I presume, the way this is supposed to work is that the roomstat manages the room temp setting and the UFH min/max is to limit the temp of the floor whilst it heats the room to the set temp.  Just want to be clear how you see your limits working as this will just make the floor colder but the roomstat will keep calling for heat and keep it on.  Is that correct?  Just trying to work out how we implement this in HA - maybe sliders for each of min/max/offset as room already has a climate control?  You can use the input_number.set service then to change these values but you won't be able to have a Wiser schedule drive this - unless you create an automation to monitor schedule temp and adjust the max on that basis.  Is this what you envisage?

**Comment by iwf10** [comment]
Thanks.
broadly yes. In reality we should be trying to do away with the room stat in this use case, but that probably need to be accepted by Drayton.  In such a case you’d be able to schedule the floor just based on Max Temp and measured temp. In my case I hate having a cold floor, though I’m not trying to heat the whole room. So a room temp of 18 and floor temp of 28 is perfect , at least in my situation 

I’d be surprised if someone hasn’t figured a way to build schedule around a single value, but would accept it’s not one of the standard controls.

Within Wiser you can set the following: Probe type ( but I’d leave that as read only) MaximumTemperature (set able between +5 and 40 c, ) MinimumTempreature  (Disabled or +5 to + 39) and offset (-9 to +9 ) all these in 1 dregree increments.

I’d see it working by setting the room stat at something un achievable. I performed a couple of tests yesterday.   Max temp 25, room target temp 30, the switch turned off at 25, though the room stat still showed it to be on, or requiring heat.  Secondly Min temp 23, room stat 21, measured 22, the min temp setting did not override the room stat

  I tried yesterday to set a miminmum temp above the current temp with the room stat off and the heat switch didn’t overule the room stat ( something I’ll take up with Drayton.

So setting the room stat to say 30c and MAXIMUMTEMTERATURE at say 25

**Comment by iwf10** [comment]
Any update on when we might see some of this data surfaced.  I'm have a running battle with Dayton on the art of the possible.  They don't even think the data is available, which is clearly is

**Comment by msp1974** [comment]
Hi,  sorry for late replay, I have been away for a week or so.  I have completed much of the work to add this in but had some back and forth with Wiser on how to set the params (as I have no device to test with).  I think I have it sorted now so should be able to provide a beta release for testing in next couple of days

**Comment by iwf10** [comment]
Great. it'll be most useful.  Wiser have some work to do to make better use of the switch.  with the data coming via the api I can prove it to them.  cheers

**Comment by msp1974** [comment]
Now added to v3.2.3beta.  Can you test it for me and let me know of any issues.  Thanks

**Comment by iwf10** [comment]
Great will do.  I just need to work out how to upgrade to a beta :)

**Comment by iwf10** [comment]
I'm new to this, so am probably doing something stupid, but the beta is unable to find the Wiser, with a constant retry setup message.   Am I supposed to start again from from scratch

**Comment by msp1974** [comment]
No. Do you have anything else in the logs or has your hub dropped off the WiFi?

**Comment by iwf10** [comment]
The hub is viewable via the Wiser app, both from 5g and internal network, so it's something else.  other HA devices seem ok.

Which logs should I be looking at ?

**Comment by msp1974** [comment]
In settings - system - logs.  Presume where you are seeing retry message.  Can you provide these logs.

In the meantime, to get working again, you can go to redownload and pick the prior version.

**Comment by iwf10** [comment]
Resolved.  The IP address of the hub has changed.  Configuring for the new one has worked.   I'll sort the addressing out within the router. Apologies, not sure what caused the change.

**Comment by iwf10** [comment]
Hi 

HA is now reading the floor temp.  It would nice to be able to use the same sensor card as I do for other room temperatures, but at least I can read the data

**Comment by msp1974** [comment]
You can add the climate sensor to a thermostat card which will also allow you to set min/max temps.

![image](https://user-images.githubusercontent.com/11211952/211362112-26fd370d-7239-4511-a77b-c2092fe4dc1d.png)

**Comment by iwf10** [comment]
yes, but being able to view over time, as I do the other temperatures is equally useful 

![image](https://user-images.githubusercontent.com/119517680/211363124-856e5bd0-86b9-4d6e-b279-96213a0f4aa5.png)

**Comment by msp1974** [comment]
Do you mean an LTS sensor like on rooms?  If so, will add that for you.  Just for current temp (Energy and Power already exist) or anything else also?

**Comment by iwf10** [comment]
Yes, indeed.  My main plan is to use the data collected to persuade Wiser to start using the floor temp rather than the room to control the floor.   In my use case I'm just trying to not have a very cold floor when stepping out of the shower :)

**Comment by iwf10** [comment]
Great, just remind me would you. how do you update the integration?

**Comment by msp1974** [comment]
In HACs if you have beta versions enabled, update from there. If you don't have beta versions enabled, go into Integration entry in HACs, select 3 dots top right, redownload and turn on beta versions.  Then update in HACs as before.  It may take an hour or so to show available update. You can force this by same 3 dots as above and update information option

**Comment by iwf10** [comment]
great. all working.  will report back

**Comment by ikoz** [comment]
@iwf10 my use case is exactly the same, I am in the process of laying out new electric UFH and the rest of the system is all wiser. However in the bathroom I'll only have a towel rail without wiser TRV, this will control the bathroom air temperature.
The UFH would only be used to keep the floor warm to the touch, so I'd want to control it thermostatically based on the floor sensor, not roomstat. Does this already work with the HA integration or is a (unncessary) roomstat still needed for the heat switch to work at all?

**Comment by iwf10** [comment]
@ikoz in with you on this. In fact I’m thinking of putting my old heatmiser controller back in.  The latest beta of the HA integration surfaces the current probe temperature, which it didn’t before, so in theory someone with good HA skills could write something I’m sure.  A bit beyond me.

Trouble is you need the room stat, even though it serves no practical purpose. It’s worse though because the room stat reads air temp which is affected by lots of other things.

I too am frustrated by Drayton, but at least the actual switch contain all the data needed. They just need to sort out the software.

but what you do though is to set the max temperature in the switch configuration to what I think is reasonable ( 28c) ( via the wiser app) then simply use the room stat as a timer.  I’m going to write up my views on the Facebook page, see if that has any impact.

**Comment by ikoz** [comment]
@iwf10 i see, yeah the requirement for roomstat is frustrating. I was hoping that if operating via HA the roomstat may not be needed, but looks like that is not the case.
That being said, the heatmiser controller would also have air temp sensor as well, no? Not sure if an commercial UFH controller exists without air sensor, that allows controlling the floor temp alone. For that it looks like i may need to go towards a shelly relay or similar.

**Comment by iwf10** [comment]
Heatmiser has the right controller, which combines controller and floor stat.  It’s what I had installed before I brought in Drayton.  I only brought in Drayton because heatmiser didn’t have smart rad valves .

yes the room stat will use it’s own stat rather than the floor.  What I’m asking Drayton is to allow the room stat to use the floor temp rather than the air temp.

**Comment by msp1974** [comment]
Closing this issue as requested functionality now in v3.3.0 release.
