### ISSUE TITLE
Possible feature request: Toggling wiser hub comms via automation? 

### ISSUE THREAD

**Issue by dbrb2** [asantaga/wiserHomeAssistantPlatform#335]
This may be a bit of an edge case...
My wiser system is only powered when the boiler is on, and the boiler is off when I'm not around. 
That means that the logs fill with thousands of failed attempts to contact the Wiser hub

If there was a way to disable the hub comms programatically via an automation I could tie it to the boiler power state, which would be great. But I realise this is a bit unusual, so may not make the grade!

**Comment by asantaga** [comment]
yeah, this is a edge case :-) 

I'll look if we can implement this, my only concern isnt technical but does it make sense and will it confuse people.

One question, why dont you have the hub/boiler powered? Most boilers have power so that if the temperature falls below a certain value the boiler spins for a bit to stop if from freezing... Wouldnt you want this feature?

**Comment by dbrb2** [comment]
Ah - yes understood. 
My boiler (and I think most combis) use a small volume of gas every day even if they are not used for heating or hot water. That combines with the wiser power itself, and the opentherm gateway that controls the boiler, to give an electrical load of ~15W that I could do without. 

The freezing is less of a problem, as I have run my condensate pipe to an internal drain where it can not freeze - having said that I do have an automation that can turn everything on if the external temperature drops below freezing, as measured from a sensor in the garden 

I also then have an automation that turns the boiler on if the lights are on in any of the rooms that have hot water taps. 

Of course this is less of a problem during the winter, as the boiler is on more than it is off for heating. It becomes more valid in the summer when it is only needed for hot water 

Thanks!

**Comment by asantaga** [comment]
Im surprised that your boiler uses gas when its not being used. In the old days we had gas boilers with a pilot light, yes that used gas when not being used but my condensing boiler did not and I thought combis only used has when used (it heating on/taps on).. 

but ... its a moot point.

Putting a switch to by pass the rest calls wouldnt be that hard, but what data would you want in the trvs? do we set all temps, battery power etc to zero? Do we remove the entities? but then HA will barf with a ton of errors...

**Comment by rittzy** [comment]
Just as a side note, most boilers do not use any gas when they are not being used unless you have a boiler that is ancient and uses an always on pilot light, they use no gas when off so there is no need to have it turned off when not in use.

**Comment by dbrb2** [comment]
To be fair, the gas usage was minuscule - maybe only 0.4kwh in a 24 hour period - which I think is about 0.05m3. I wondered initially if there was a fault, but a boiler service showed nothing. All I could come up with was maybe the boiler has some kind of self test usage. 

The main reason though for turning off was that during the summer the ~15w of boiler self power+wiser hub power+opentherm gateway power was good to have off. 
I can see though that it might be an unnecessary software can of worms to open, and the errors in the logs don't actually do any real harm!

**Comment by rittzy** [comment]
Yea I can understand with the price of electricity, even saving 15w can lead to some savings over the years. I know with my own boiler if I turn it off then on it fires up for a seconds a runs through a test cycle before settling back down.

I personally leave mine on due to having everything connected and integrated at all times, I have a minimum low temperature of 14 degrees when no one is about so my system fires every few hours during winter.

**Comment by scooper1** [comment]
you maybe able to turn the integration on and off via service calls

**Comment by andywwright** [comment]
​Not integration related, but if it's a combo boiler, the idle gas consumption might be due to a hot water pre-heat is on by default and switching it off might not be that obvious (i.e. pressing an Eco button or some such)

**Comment by asantaga** [comment]
I've thought about this and disabling the comms would cause a number of issues to HA (entities disappearing, what do we default the values to etc etc), 

I'll get @msp1974 opinion too but I dont think we can implement this easily.
