### ISSUE TITLE
Possible Feature Request: Cancel Heating Boost for Specific Entity

### ISSUE THREAD

**Issue by anthonywalker75** [asantaga/wiserHomeAssistantPlatform#336]
At present it is possible to boost the heating for a specific entity.

Would it be possible to have the facility to cancel the boost of a specific entity as opposed to using the cancel all option on the controller card?

If not then could the cancel all be presented as a service call?

Scenario:
Wiser system used in office environment.
Primary schedule heats all offices to base temperature (eg 18C). 
Using presence detection when office worker arrives on site heating in only their office boosted to their desired comfort level (eg 22C).
When office worker leaves temperature reverts to base temperature (boost cancelled).
Therefore, only offices occupied are heated above base temperature.

I currently have a clumsy automation which sets the temperature of an office based on presence. But this does not use the boost function, and has caused a few problems when person leaves due to it setting temp to base potentially after system schedule has shut heating down (this causes the heating to turn back on).

Regards

Anthony

**Comment by msp1974** [comment]
This already exists. Boost with time 0 and it will cancel. Alternatively, set hvac to auto will also cancel any boost.

**Comment by anthonywalker75** [comment]
Thanks for the information. It might be worth mentioning this in the documentation. Also when you set the time to 0 you get a red line in the automation which states value must be greater than 1.

Regards

Anthony
