### ISSUE TITLE
Create new sensor for flow/return for openTherm compatible boilers

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#337]
From https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/1818
This template sensor exposes the ch flow/return,  this could be exposed as a native entity, instead of creating a template

Putting here for now, will implement native entity 

`- platform: template
     sensors:

       flow_temperature:
 
         friendly_name: Flow temperature

         value_template: "{{state_attr('sensor.wiser_heating','ch_flow_temperature')}}"

         unit_of_measurement: '°C'

       return_temperature:

         friendly_name: Return temperature

         value_template: "{{state_attr('sensor.wiser_heating','ch_return_temperature')}}"

         unit_of_measurement: '°C'`

**Comment by martr84** [comment]
I can see you have added a lot of opentherm state attributes in a recent commit, could you include the dhw attributes.

i've include my opentherm output from the hub, theres also a few other attributes in there too.

boiler is a ideal logic 24 combi boiler (uk).

Thanks



{
   "chFlowActiveUpperSetpoint":750,
   "chFlowActiveLowerSetpoint":350,
   "dhwFlowSetpoint":550,
   "dhwEnable":true,
   "featureActions":{
      "ModulationOnboarding":true
   },
   "Enabled":true,
   "transmitter":{
      "messagesSentCount":154055
   },
   "receiver":{
      "decodingErrorsCount":2111
   },
   "operatingMode":"OTplus",
   "preDefinedRemoteBoilerParameters":{
      "dhwSetpointTransferEnable":true,
      "maxChSetpointTransferEnable":true,
      "dhwSetpointReadWrite":true,
      "maxChSetpointReadWrite":true,
      "dhwSetpointUpperBound":580,
      "dhwSetpointLowerBound":400,
      "dhwSetpoint":440,
      "maxChSetpoint":750,
      "maxChSetpointUpperBound":750,
      "maxChSetpointLowerBound":450
   },
   "ch1FlowSetpoint":610,
   "ch1FlowEnable":true,
   "ch2FlowSetpoint":350,
   "ch2FlowEnable":false,
   "operationalData":{
      "RelativeModulationLevel":130,
      "MinimumModulationLevel":24,
      "ChPressureBar":13,
      "DhwFlowRate":0,
      "Ch1FlowTemperature":610,
      "ChReturnTemperature":530,
      "Dhw1Temperature":600,
      "MaximumCapacityKw":24,
      "SlaveStatus":10
   },
   "roomTemperature":204,
   "roomSetpoint":210,
   "TrackedRoomId":2
}

**Comment by msp1974** [comment]
Sorry @martr84, I forgot about these additional attributes when releasing v3.3.0.  Will add for next release.

**Comment by msp1974** [comment]
Included in v3.3.1.  Will close.  Thx
