### ISSUE TITLE
Add ability to control the wiser smart plug (on/off)

### ISSUE THREAD

**Issue by eon123** [asantaga/wiserHomeAssistantPlatform#34]
Would be great to have control of these plugs in HA considering how popular they are due to  being used as range extenders, is this possible?

**Comment by asantaga** [comment]
good point... I'll investigate into this over xmas..

I do need to get the damm thing into the main branch of HA.....

Changing task name

**Comment by asantaga** [comment]
Looking at the openhab impl this can be done by using the following patch command
"{\"RequestOutput\":\"" + (outputState ? "On" : "Off") + "\"}";

I smell a major enhancement coming on :-)

**Comment by asantaga** [comment]
next on the list. :-)

**Comment by asantaga** [comment]
opened base bug https://github.com/asantaga/wiserheatingapi/issues/11

**Comment by asantaga** [comment]
This is now implemented in branch R1.9Dev. There is still a sync issue so leaving this open but it fundamentally works

**Comment by asantaga** [comment]
Fixed this by forcing the state to be refreshed, seams to work

Line 155 of __init__.py
            self.wiserhub.refreshData()


@msp1974 Is this truely bad in the async world?

**Comment by msp1974** [comment]
Only in the fact you are doing 2 updates one after another. The line after does force an update.  The nothrottle=true means it does immediately. I just got one of these plugs tonight and have been looking at it.

Issue you are having is a timing one. When you set the plug to on, there seems to be a delay while the plug actually turns on before the hub reports it as on.  Guessing the 2 updates is enough time for this to show correct state.  If anything i would copy line 156 twice to see if this works. Alternetive cheat would be to add a small delay using await sleep but think this is frowned upon in HA.  

I will have a look at this over weekend and see if there is a better approach.

**Comment by msp1974** [comment]
Also, would be tempted not to call this method set mode as the plug actually has a mode of manual or auto and you can set a schedule on it. Maybe set plug state?

**Comment by asantaga** [comment]
Mm 

A) re uodate i suppose i could just issue  the update without doing a async call...  maybe a very short sleep is the right approach. I could make the sleep itself async so that it  relinquishs control back to HA thread 

B) ya right there are different modes but i wonder if  that should be a api call. So we would have set state and set mode

Finally. Dude u up late as well!!!

**Comment by msp1974** [comment]
Researching some docs, think the right way to do this is as below:
await asyncio.sleep(1)
Time in brackets is in seconds.  Think 1 second is more than enough time for this to update to the right status before doing a refresh with async_update.  I'll give it a try tonight and see how it works.

Always up late!  Only time to get things done! ;-)

**Comment by msp1974** [comment]
Have also noticed that we are calling the forced refresh twice when setting away mode and switches.  Once in the switch.py file and once in init.py when calling api.  Prob shouldn't do this given feedback on stability issues with hub of requesting updates from it too often.  Will try and sort tonight or over weekend.

**Comment by msp1974** [comment]
So been playing with this tonight to see if adding a delay works and what length.  Seem to have settled on yes this does work and about 0.5 secs does ok.  However, seen some very strange behaviour from my brand new smartplug!

Firstly, the 'OutputState' value disappears from the returned json when querying it (seen through Postman) when in an On state.  Shows when in off state.  There is however and manual state that shows instead which you can test with.  

Also, if I turn on, it can stay on for 5 seconds and then turn itself off then on then off again within a couple of seconds.  Positive there is nothing being sent from HA.  Have you seen anything like this with yours?  Not sure if this has updated firmware during today as seemed fine yesterday.

**Comment by asantaga** [comment]
Weird thing about the smart plug missing json attributes..  I'll also confirm on myside and see which is the more reliable attribute for checking the status..

I'll add the await asyncio.sleep(1) to the method and confirm it works fine. 

Side note :  Like you , totally swamped during the weekdays and only late at night can I do some coding, alas I have a conference next week, a house I need to clean up so not sure how much time I'll get... joys of work , home life and a 4yr old ever wanting attention.....

**Comment by Fulch** [comment]
Have not tried HA control of plug yet (waiting for you guys to "do your thing" with the code first) but using the Android wiser app or the button on the plug mine is behaving fine.

Firefox Rested extension displays the expected json response and plug stays 'on' or 'off' as instructed!

**Comment by asantaga** [comment]
merged it in so its ready for testing.

**Comment by asantaga** [comment]
#62 merged
