### ISSUE TITLE
Heating actuator

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#340]
As I installed the 3.2.3beta , the integration create climate.wiser_heatingactuator_salle_salon_floor_temp and number.wiser_heatingactuator_salle_salon_floor_temp_offset for one heating actuator but not for the others 

Very good idea to create an device heatingactuator! for me it should be nice to migrate the attributes temperature,  target_temperature, output_type from "Wiser heatingactuator xxx signal" to the device.

[config_entry-wiser-d2b5e58746bb2e3c81e153fe19a017cf.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/10369169/config_entry-wiser-d2b5e58746bb2e3c81e153fe19a017cf.json.txt)

**Comment by msp1974** [comment]
Hmmm  seems one of your heating actuators shows different data to the other.  It should not have created the climate and number entities for any of your heating actuators as you do not have floor temp sensors.  I have fixed that for the next update.  Thanks for the help.

The attributes have to be on an entity not a device.  Maybe we should create a sensor entity for the heating actuator.  Will put it on the todo list.

**Comment by LGO44** [comment]
Sorry for the bad news.

I've installed the version _3.2.3beta2_ over the _beta1_ then the entity climate.wiser_salle_salon is no more provided by the integration. The previous issue was on this one too.

 I reinstall the 3.2.2 
![image](https://user-images.githubusercontent.com/95585425/211626326-1bc7ab8f-013d-4563-89f9-5d3c49d56666.png)
 the climate  wiser salle salon is ok
![image](https://user-images.githubusercontent.com/95585425/211626454-01743f33-fb9d-45de-b18c-79252b057c96.png)

I install again the version 3.2.3beta2
![image](https://user-images.githubusercontent.com/95585425/211626661-6e6e790a-60cd-44ab-af25-b6bba471fadb.png)

 I loose the climate salle_salon 
![image](https://user-images.githubusercontent.com/95585425/211626826-b6fc652b-e2d2-4ca9-80e3-ae78c27e87be.png)

![image](https://user-images.githubusercontent.com/95585425/211626887-b8e7026f-29b4-451e-bb07-164b37c6c269.png)

![image](https://user-images.githubusercontent.com/95585425/211626947-8f98e44d-b174-4f5c-b13f-15167e34fd51.png)


Sorry for the print screen in french!

**Comment by LGO44** [comment]
Thank you Mark,
I'm not at home  for a few days, I'll test your improvement next week end

**Comment by LGO44** [comment]
The issue is fixed by the version 3.2.3beta3
Thank you Mark

**Comment by msp1974** [comment]
Will close for now.
