### ISSUE TITLE
Zigbee topology : repeater

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#345]
When the repeater of a device is a heating actuator, the attribute 'repeater' is identify by heatingactuator_id. 
A user doesn't know where is this device . 
It should be nice to name it room_heatingactuator (_1 or _2 or _3 according to the number of actuator in the room)

![image](https://user-images.githubusercontent.com/95585425/215347610-b121e8cd-ddeb-4f9a-8e32-e2125f5d7796.png)

**Comment by msp1974** [comment]
Fixed in v3.3.0 released just now.
