### ISSUE TITLE
Passive mode overriding boosts

### ISSUE THREAD

**Issue by tombadog99** [asantaga/wiserHomeAssistantPlatform#348]
Passive mode overrides boosts which are physically activated using the trv heads/room thermostats. It would be great if boosts could still be allowed either by allowing the standard boosts to not be overridden or even by raising the passive mode minimum temperature for the relevant boost period.

**Comment by msp1974** [comment]
So, have played around and stopped it overriding a boost but that raised another question.  What should the thermostat card show in this situation.  As it is still in passive mode, it is showing a range temp but the boost has set a specific one.  And also, should it show Passive Mode - Boosted as the status?  What's your thoughts?

**Comment by tombadog99** [comment]
I think there are probably a number of ways it could be done. I was imagining a boost raising the minimum temp up by the relevant boost amount and perhaps a status of Passive Mode - boosted as you suggest. The only thing is In guessing there wouldn't be an easy way to cancel the boost which doesn't bother me but may bother others?

**Comment by msp1974** [comment]
Ok, so after thinking about this here is my proposal of how it works.

The boost can be initiated from either the TRV itself or selecting a boost preset (as in normal modes).  This also allows access to the cancel boost option in HA.

As a boost is effectively temporarily taking out of passive mode, the thermostat card should show this.  As such:
When boosted, it sets thermostat card back to single target temp and shows Passive - Boost xxm as in normal boost.  This allows the boost temp to be amended via HA if desired.
When boost over, it goes back to temp range and showing just Passive as the mode.

Does this make sense?  Link to a quick video as a video paints a damning picture and all!!!

https://www.loom.com/share/cbc4119bea1048cebce0fca74523c0ee

**Comment by tombadog99** [comment]
Yes, this looks perfect!

**Comment by msp1974** [comment]
Passive mode with boost override in v3.3.1.  Closing for now.  Thx
