### ISSUE TITLE
schedule duplication after integration reload and hub reset  

### ISSUE THREAD

**Issue by scooper1** [asantaga/wiserHomeAssistantPlatform#357]
old deleted schedules appear and override rooms in heat mode  after a combination of hub reset and home assistant reload
this has been happing for the last 4 weeks and is not a one-off problem  - now had to delete the same schedules five times so far
the duplicated ones have different ids 
both systems are fully to date 

it is happing on both systems I look after 

![image](https://user-images.githubusercontent.com/14822945/227657672-c5696b2d-01ad-4bf1-bac6-cefb379b4923.png)

**Comment by msp1974** [comment]
Need some more info on this issue.  Please provide a diagnostics file and steps to recreate - maybe a video of this happening.  Thx

**Comment by msp1974** [comment]
Any further info on this issue?  If not, will close as cannot recreate.  Thx

**Comment by msp1974** [comment]
Closing due to lack of response.  If the issue is still occuring, please re-raise and provide the requested info.  Thanks
