### ISSUE TITLE
Allow "Passive Mode" to scheduled.

### ISSUE THREAD

**Issue by andyblac** [asantaga/wiserHomeAssistantPlatform#358]
Would it be possible to allow room passive mode to be scheduled ?, by this I mean instead of the option in the room move this to be an option in the scheduling. This would allow us to not allow call for heat, but only at certain times of the day, or whole days and not others.

**Comment by msp1974** [comment]
No this is not possible. The schedules are on the hub and this is effectively an automation in HA.  You can get HA to turn passive mode on and off on a schedule with the scheduler integration in HACs but otherwise im afraid it cant do that.

**Comment by andyblac** [comment]
> No this is not possible. The schedules are on the hub and this is effectively an automation in HA. You can get HA to turn passive mode on and off on a schedule with the scheduler integration in HACs but otherwise im afraid it cant do that.

This is what i meant in the HA shedule, so this can be done now ?, if so how would i got about this i am very new to HA.

**Comment by msp1974** [comment]
You can't do with the Wiser integration but have a look at this integration/custom card.  It will allow you to create a schedule to turn Passive mode on/off but won't allow you to amend any Wiser heating schedules.

https://community.home-assistant.io/t/scheduler-card-custom-component/217458

**Comment by andyblac** [comment]
sorry but how do i set passive mode
<img width="594" alt="Screenshot 2023-03-30 at 17 17 30" src="https://user-images.githubusercontent.com/77936/228900544-9f95bee1-7b9d-4836-8d74-849c8c13bcf4.png">

**Comment by andyblac** [comment]
i'm sorry but i am very new to HA, I don't understand I do not see an option in Wiser Schedule card or the the Custome Schedule card as above, to enable or disable "passive mode"

**Comment by msp1974** [comment]
Its not in the schedule card.  Thats what i was saying before.  The schedule card allows you to manage schedules on the Wiser hub.  Schedules are a native function of the Wiser system for managing room temperatures and other Wiser devices.  Passive mode is not a native part of the Wiser system but a coded automation provided by this integration.  As such, passive mode cannot be scheduled within the Wiser schedules and you will need some other way to schedule turning it on and off.  The schedule integration allows you to create a schedule to turn passive mode on and off (using the passive mode switch - see below) but that schedule will not interact in any way with the Wiser schedules.

The instructions linked to above, tell you how to enable the passive mode automations on this integration by clicking on configure from the integration widget in devices and services and then explaining that once you have done that you wil have a new switch entity for each room to allow you to enable/disable passive mode.

Hope that helps.

**Comment by andyblac** [comment]
yes, I cann see the manual switch for passive mode, so are you saying atm it is only manual enable / disable option and not schedule for different time of the day ?
<img width="386" alt="Screenshot 2023-03-30 at 17 51 48" src="https://user-images.githubusercontent.com/77936/228908749-4963b538-77d1-4492-9c2a-e21862b2ed07.png">

**Comment by msp1974** [comment]
> is only manual enable / disable option and not schedule for different time of the day

Yes and it will only ever be manual.

The scheduler integration (https://www.google.com/url?sa=t&source=web&rct=j&url=https://community.home-assistant.io/t/scheduler-card-custom-component/217458&ved=2ahUKEwiN0_ahl4T-AhWUR8AKHRV1AGUQFnoECBMQAQ&usg=AOvVaw0FOxy0Mvznpvu0StlBqK82) will allow you to create a schedule to turn on/off the passive mode switch.  Ask on their forum if you are struggling how to do this.

**Comment by andyblac** [comment]
Thanks for your help, my mistake was i was using `climate` for the scheduler, when it should have been a `switch` then it showed the `pass mode` option, still learning all this stuff, so thanks again
