### ISSUE TITLE
Passive Mode Temperature Increments

### ISSUE THREAD

**Issue by toddstar** [asantaga/wiserHomeAssistantPlatform#359]
Ticket for question/issue raised on forum post https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/2301 - Whilst testing the new passive mode updates in 3.3.1 my system carried on using the old 0.5 increase rather than the figure set in the options. 

@msp1974 says its an issue with it not being set on update https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/2303

**Comment by msp1974** [comment]
@toddstar - just released a v3.3.2 version with the fix for this.  Can you please confirm.

Note:  There is also now an attribute on the climate entity called passive mode temp increment which shows what this is operating at.

**Comment by toddstar** [comment]
Still seeing ~0.5 increasement for target temp

Heating Off
![Screenshot 2023-04-05 162003](https://user-images.githubusercontent.com/22575856/230127580-c44b9ad2-92da-4f75-b51f-9ce92a8c659d.png)
Heating On (LTS Target 16c, should be 17.5/18c)
![Screenshot 2023-04-05 162046](https://user-images.githubusercontent.com/22575856/230127603-2f8062c0-6195-4f04-992a-c58b7783eb08.png)
(target increase set to +2)
![Screenshot 2023-04-05 162120](https://user-images.githubusercontent.com/22575856/230127617-71672605-21a0-4eb7-b8eb-d1032d396b01.png)

**Comment by msp1974** [comment]
Ok i can see this.  Done some head scratchimg and i think i know the issue.  Needs a bit of rework on the api, so give me a few days.

**Comment by msp1974** [comment]
@toddstar - sorry it's taken a little longer than expected.  This is now in v3.3.3 just released.  If you could test it and let me know if it works as expected.  Thx

**Comment by toddstar** [comment]
> @toddstar - sorry it's taken a little longer than expected. This is now in v3.3.3 just released. If you could test it and let me know if it works as expected. Thx

No worries on the delay!
All working as expected now 👍
