### ISSUE TITLE
Any way to get TRV calling for heat?

### ISSUE THREAD

**Issue by normanstanleyspencer** [asantaga/wiserHomeAssistantPlatform#365]
Hello - please could you tell me how to get the TRV state (idle, heating etc.)?  When I look at the history for the TRV, it shows a chart, but what I am after is whether that TRV is calling for heat or not, as a history.  I could turn the 'Wiser LTS Heating Demand' % into a binary sensor, but that seems like overkill.  Many thanks for a great integration.

**Comment by andyblac** [comment]
what your after is the entity called "climate.wiser_xxxx" (xxxx being the room name in wiser app), see example below

<img width="411" alt="Screenshot 2023-04-11 at 13 06 27" src="https://user-images.githubusercontent.com/77936/231157932-42b92396-8e6c-482b-aba9-d905588b84c7.png">
<img width="1126" alt="Screenshot 2023-04-11 at 13 06 42" src="https://user-images.githubusercontent.com/77936/231157989-e124279c-aa5a-40a8-831b-1154292ee3b0.png">
you should see "wiser xxxxx heating" like above in RED.

**Comment by andyblac** [comment]
there is an Entity "sensor.wiser_heating" but this is for any device calling for heat.
<img width="394" alt="Screenshot 2023-04-11 at 13 12 14" src="https://user-images.githubusercontent.com/77936/231158922-803ece12-3822-4cd4-8b99-e8c1ae84043d.png">
<img width="1352" alt="Screenshot 2023-04-11 at 13 12 22" src="https://user-images.githubusercontent.com/77936/231159315-7af2f8fa-8eeb-4418-8fcf-75bc98ca5f7b.png">

**Comment by normanstanleyspencer** [comment]
Many thanks - I was trying to only extract the Wiser *** Heating state (this doesn't seem to be a separate sensor?) so I can have a history chart like the wiser_heating sensor but for each individual TRV - the reason being I want to see which are the TRVs that call for heat while the others don't (and therefore tweak the heating to be more efficient to prevent too many boiler cycles).

If not, I'll create binary_sensors for each based on the LTS Heating Demand % being > 0 and report back.

**Comment by normanstanleyspencer** [comment]
Here's what I did.  Hope it helps someone.

`  - platform: template
    sensors:
      wiser_cfh_kitchen:
        friendly_name: "Wiser Call For Heat Kitchen"
        value_template: >-
          {% if states('sensor.wiser_lts_heating_demand_kitchen') | float == 0 %}
            Idle
          {% elif states('sensor.wiser_lts_heating_demand_kitchen') | float > 0 %}
            Call
          {% endif %}`

**Comment by normanstanleyspencer** [comment]
Here's what I did.

Hope it helps someone.

  - platform: template
    sensors:
      wiser_cfh_kitchen:
        friendly_name: "Wiser Call For Heat Kitchen"
        value_template: >-
          {% if states('sensor.wiser_lts_heating_demand_kitchen') | float == 0 %}
            Idle
          {% elif states('sensor.wiser_lts_heating_demand_kitchen') | float > 0 %}
            Call
          {% endif %}

**Comment by msp1974** [comment]
Assuming from the comments above this is resolved? Thanks @andyblac for helping.
