### ISSUE TITLE
Wiser Zigbee Network Outlier

### ISSUE THREAD

**Issue by Charles-Misc** [asantaga/wiserHomeAssistantPlatform#368]
I like this card but it's now showing one trv very far away from the cluster and even after a reboot isn't auto scaling as before.
![WizerNetwork](https://user-images.githubusercontent.com/102307254/236046467-da23ab03-ef82-47ce-b92d-ff9b9be3caac.png)

**Comment by msp1974** [comment]
Hmm not seen it do that.  The underlying library we use to draw the network controls the layout.

Can you give some more info.

What browser? 
Does it do it on other browsers?
Have you got any other cards that have some sort of diagram layout installed?
I presume it is a trv that is orphaned on the right?

I will have a look and see if i can see anything that may cause this or allow prevention of it.

**Comment by msp1974** [comment]
Any further info on this?

I am working on an update to make it look and function a little better which will also update the libraries used but would like to test against your issue.

**Comment by msp1974** [comment]
@Charles-Misc can you try the latest version of the integration with the updated zigbee network card and see if this is solved.  You can also manually adjust and save the layout.

**Comment by msp1974** [comment]
Closing due to lack of response.
