### ISSUE TITLE
False negative temperatures when the hub loses the sensor

### ISSUE THREAD

**Issue by andywwright** [asantaga/wiserHomeAssistantPlatform#369]
So the batteries died today in my Wiser room stat and the temperature in HA immediately turned to -19C ruining all the charts. Would you please clarify if it is a supposed behavior and I have to create a workaround or it's a bug and we can hope it will be fixed eventually?

**Comment by msp1974** [comment]
You can plan on us trying to fix this.  It seems one of the recent firmware updates on the hub changed how it behaved when loosing signal with a trv.  Give me a week or so and we'll release an update.

**Comment by msp1974** [comment]
v3.3.5 should now fix this.  It sets the current temp to blank and as such, the history graphs show a constant line for last read temp.

**Comment by msp1974** [comment]
Closing issue as resolved
