### ISSUE TITLE
Enhancement request. Add is_locked attribute to climate entities

### ISSUE THREAD

**Issue by pcaouolte** [asantaga/wiserHomeAssistantPlatform#374]
Would it be possible to add an is_locked attribute to the Wiser climate entities please?

This would simplify automations by avoiding the need to check which devices are in the same room as a climate entity and then checking if those devices are locked.

It is possible that only some devices in the same room as the climate entity are locked so I suppose that the is_locked attribute state could be 'true', 'false' or 'part'. Alternatively the is_locked attribute state could contain the number of devices in the room which are locked.

Apologies if this is not the appropriate way to make this request. I am very new to github.

**Comment by msp1974** [comment]
Had a look at this but struggling with how to make this make sense.  The hub supports lights and blinds too in France so it doesnt necessarily make sense to just show all devices.  What is your use case and maybe i can come up with something that helps.

**Comment by pcaouolte** [comment]
Hi Mark,

Thank you for looking at it. I was trying to display a Lock icon when any of the TRV or room stats in a room are locked.
If I could check the climate entity for the room and know that a device in the room was locked then it would avoid having to look at each device in the room in turn to check if they are locked or not.
It's not a big deal. I've worked around it by checking each device in the room so that I can display this:
![IMG_2376](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/105014804/87344b06-d213-4482-a06a-6d5e79b0148e)

**Comment by msp1974** [comment]
@pcaouolte i haven't forgotten about this and will look at it during Nov.

**Comment by msp1974** [comment]
Sorry for the very long wait.  This is now in v3.4.4, released earlier today.

**Comment by pcaouolte** [comment]
Thank you 👍
