### ISSUE TITLE
Getting 0% across a lot of devices on new install

### ISSUE THREAD

**Issue by elliotwestlake** [asantaga/wiserHomeAssistantPlatform#377]
Just recently installed the system and the home assistant integration. 

I seem to be getting 0% and "No Battery" on most of my devices.

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/17042376/58b40b98-eb8d-4e27-9fef-ff1ebfe4aac1)

Diagnostics:
[config_entry-wiser-63418ccbfe7e74b150e63637bd376418.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/12281711/config_entry-wiser-63418ccbfe7e74b150e63637bd376418.json.txt)

**Comment by msp1974** [comment]
It can take a little bit of time after a hub restart (in and out of setup too) for battery states to be sent to the hub.  Your diagnostics file only shows 1 of your TRV reporting its battery state, which is consistant with your screnshot.  Give it an hour or so.

**Comment by elliotwestlake** [comment]
Nice one, will do. thanks! @msp1974
