### ISSUE TITLE
climate to off : LTS_target_temperature not recorded

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#378]
I select all the climate to off, then an error is detected by the recorder :
the unit of this entity had been modified from '°C' to ''.

Then all the LTS target temperature had been lost...

**Comment by msp1974** [comment]
Hmm, not sure how to handle this.  Had feedback that temp showed -20C when off causing issues with graphs.  As such changed it to None when off.  This is obviously now causing other issues.  May need a concensus as to how to treat this situation.

**Comment by LGO44** [comment]
I'm OK for that.

**Comment by msp1974** [comment]
@LGO44 , what do we want to do about this issue?

**Comment by msp1974** [comment]
Ok, this was finally settled to make it unavailable in v3.4.4
