### ISSUE TITLE
RuntimeWarning: coroutine '_make_delegate_method.<locals>.method' was never awaited config_file.close()

### ISSUE THREAD

**Issue by Scoff123** [asantaga/wiserHomeAssistantPlatform#379]
I'm not 100% sure but I believe this warning message started occurring in my HA Core logs since I updated HA to 2023.8.3, and is happening quite frequently:

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/wiser/coordinator.py:138
Integration: Drayton Wiser Integration for Home Assistant (documentation, issues)
First occurred: 22 August 2023 at 00:31:09 (44 occurrences)
Last logged: 10:43:20

/usr/local/lib/python3.11/site-packages/aioWiserHeatAPI/helpers/extra_config.py:21: RuntimeWarning: coroutine '_make_delegate_method.<locals>.method' was never awaited config_file.close()

I'm not sure if this is on the HA side or the Integration side so thought I'd raise it here initially. 

Thanks

**Comment by msp1974** [comment]
Thanks. Aware of it.  Not causing an issue but started warning from HA2023.8.0.  On schedule to fix in api.

**Comment by Scoff123** [comment]
Great, thanks Mark.

**Comment by msp1974** [comment]
This should now be fixed in v3.3.9 - just released.
