### ISSUE TITLE
Wiser battery level indication is incorrect

### ISSUE THREAD

**Issue by Pack-os** [asantaga/wiserHomeAssistantPlatform#382]
The wiser Thermostat valves have two AA batteries giving a maximum 2.4 - 2.6v.

New batteries have been fitted that indicate 2.6v but are showing 20% & low

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/123515997/66af8ae7-c326-4178-bdd4-8e66d38880b1)

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/123515997/6c6e4a49-f77b-4963-bd55-7fb49d18eda5)

**Comment by dunxd** [comment]
I don't believe the iTRVs send the battery level details to the hub very frequently - so the figure doesn't update very quickly. Give it an hour or so.

I imagine this is to preserve battery life - you don't need to know the battery level very frequently.

**Comment by Pack-os** [comment]
Hi,
The batteries have been fitted for several days with no change.
I am about to fit some new rechargeable batteries and check voltage first then monitor.
Whilst it does not affect the function it upsets battery level automation checks in HA.

**Comment by dunxd** [comment]
I wouldn't recommend NiCad rechargables for the iTRVs as they have a lower voltage (1.2v) even when fully charged. Fine for electronics, but with the iTRVs they have to drive a motor.

**Comment by msp1974** [comment]
If you use rechargeable batteries, the % will always be low as they are 1.2v and not 1.5v.  We convert the voltage to a % (as the hub only supplies voltage and a text status).

Wiser themselves say you should not use rechargeables in these trvs and as such, we don't support using them.

**Comment by Pack-os** [comment]
The voltage difference certainly explains what I am seeing, I will indeed remove all rechargeable batteries.
After the comment from dunxd I checked the app and it does indeed show the same.
Thank you all for your feedback.
