### ISSUE TITLE
Opentherm Relative Modulation Level

### ISSUE THREAD

**Issue by SteveJack34** [asantaga/wiserHomeAssistantPlatform#383]
Hi
Just reading some of the Open Therm parameters in the attributes. I've noticed the Relative Modulation Level value seems to be wrong. According to the Protocol RML should be 0-100%. I'm getting a value of 320% with the hot water on. I'm assuming it is a factor of 10 out.

**Comment by msp1974** [comment]
Ok.  Will fix in next release

**Comment by msp1974** [comment]
Fixed in v3.3.10
