### ISSUE TITLE
Enhancement Request: Additional OpenTherm parameters

### ISSUE THREAD

**Issue by SteveJack34** [asantaga/wiserHomeAssistantPlatform#385]
Add the following opentherm parameters:
ID 014 : Maximum relative modulation level setting (%)
ID 015: Maximum boiler capacity (kW) / Minimum boiler modulation level(%)
ID 033: Boiler exhaust temperature (°C)
ID 034: Boiler heat exchanger temperature (°C)

Willing to Beta if needed.
SteveJ

**Comment by msp1974** [comment]
Can you provide a diagnostic download so i can see that the hub is providing these.  If it is we can add, if it is not, we can't.

**Comment by SteveJack34** [comment]
Hi Mark

Diagnostic attached. Looks like the hub isn’t providing those parameters I was asking for. Which is odd, I don’t know if you’ve looked at the OpenTherm website but the hub had been tested and reads those parameters from the boiler. Licensed Products - Opentherm Association <https://www.opentherm.eu/request-details/?post_ids=4266> . It may be that my boiler (Vaillant Ecotec Plus 837 with VR33 eBus to OpenTherm module) doesn’t provide those parameters.

 

Steve Jacklin

Steve’s Bees

 <http://www.steves-bees.co.uk> www.steves-bees.co.uk

07769 660133

**Comment by msp1974** [comment]
Ok then i'll close this as can not be provided.  However, is the hub yiu have not this one?  The HubR i think is the European one.

https://www.opentherm.eu/request-details/
