### ISSUE TITLE
BLE device support?

### ISSUE THREAD

**Issue by glxxyxafonso** [asantaga/wiserHomeAssistantPlatform#386]
Hey!

I was trying to setup my BLE Wiser switch, but can't because this integration requires a Wiser Hub.

Is there any plans to have BLE device support?

**Comment by msp1974** [comment]
No, we do not support and do not plan to support BLE devices.  This integration is purely designed to talk to a Wiser hub.  Is it not supported by the Bluetooth integration?

**Comment by glxxyxafonso** [comment]
> No, we do not support and do not plan to support BLE devices. This integration is purely designed to talk to a Wiser hub. Is it not supported by the Bluetooth integration?

I think it's not supported.
Wiser's support for fully functioning Non-Hub devices is terrible. In some FAQs they say that the new Wiser app supports BLE devices, but then support says that it does not work with BLE devices. SE is so damn confusing!

If anyone wants to help me check if it works with the BT integration, would appreciate it!

**Comment by asantaga** [comment]
Alas this integration is not going to support Wiser BLE devices directly, sorry

**Comment by asantaga** [comment]
@glxxyxafonso There are some BLE integrations out there which work with HA, you might be able to get it to sniff your BLE device and do something useful with it. alas its out of scope for this integration
