### ISSUE TITLE
Flow and Return Temperature Issue

### ISSUE THREAD

**Issue by SteveJack34** [asantaga/wiserHomeAssistantPlatform#387]
Ok so first day of the heating being on for a length of time so thought I would check my flow and return temperatures.
With temperature probe on the boiler I get a flow and return of 30 and 28 degC. In HA I'm showing a flow and return of 47 and 42. I've looked at the diagnostic download and flow and return are 470 and 420. I would suspect there is a conversion off somewhere.

**Comment by msp1974** [comment]
All other temps from the hub are in degrees C, so i dont see why these wouldnt be.  I do not have an opentherm boiler to check this but i would say temps of 30 and 28 are very low if your boiler is running.  Are you sure these are correct.  How and where are you measuring it?

**Comment by SteveJack34** [comment]
Measure on the inlet and outlet of the boiler. Might have another issue. Don’t think the integration is talking to the hub. Which is why the temps are wrong.

 

Looking in the debug logs I get 

http://X.X.X.X:80/data/v2/status/ Error is 400

When I try from a browser I get

{

    "Error": "Unauthorized"

}

Would the secret key of changed? Don’t see why.

 

Steve

 

Steve Jacklin

Steve’s Bees

 <http://www.steves-bees.co.uk> www.steves-bees.co.uk

07769 660133

**Comment by msp1974** [comment]
If you have factory reset the hub the secret key will change.

**Comment by SteveJack34** [comment]
Not reset hub. Looking at forum I’m not the only one with this issue.

Steve

 

Steve Jacklin

Steve’s Bees

 <http://www.steves-bees.co.uk> www.steves-bees.co.uk

07769 660133

**Comment by msp1974** [comment]
Sorry didntread your note properly.  Unauthorised is from browser.  You will always get this if you dont provide the secret key in the request headers, so expected from a browser.

So have you also updated to 2023.10.2?

**Comment by SteveJack34** [comment]
Yes

 

Steve Jacklin

Steve’s Bees

 <http://www.steves-bees.co.uk> www.steves-bees.co.uk

07769 660133

**Comment by msp1974** [comment]
I believe this is now resolved with the HA 2023.10.3 release. Can you confirm?

**Comment by SteveJack34** [comment]
Yes its Mark

 

Steve

 

Steve Jacklin

Steve’s Bees

 <http://www.steves-bees.co.uk> www.steves-bees.co.uk

07769 660133

**Comment by msp1974** [comment]
Closed as bug created in HA 2023.10.2 with update to aiohttp.  HA 2023.10.3 reverted.
