### ISSUE TITLE
Inaccurate temperature and status

### ISSUE THREAD

**Issue by kevindbeard** [asantaga/wiserHomeAssistantPlatform#389]
For a couple of my rooms, the temperature and status doesn't match the Wiser app.

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/10993674/83fb5a96-698b-4fc6-8fef-b20a2c7dca53)

![Screenshot_20231016-152622](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/10993674/6ecb7d3e-d638-492f-83c7-dd39703506ac)

I have the scan interval set to 30 seconds and I've waited for a few minutes for them to sync up

**Comment by kevindbeard** [comment]
Actually the status did eventually sync up but the temperature never matches

**Comment by dunxd** [comment]
I think the Wiser app rounds the temperature to the nearest 0.5° whereas
the integration shows to the nearest 0.1°.

**Comment by kevindbeard** [comment]
Thanks @dunxd 
As for the inaccurate status, it looks like that is actually the Wiser app.  When I stand next to the boiler I confirm that nothing is calling heat even when the app says there is.
I will close this issue

**Comment by asantaga** [comment]
The integration just reports what we get from the wiser hub.... and yes the "real" temperature can be wildly off depending on the thermal characteristics of your house..

Wiser always reports 1-2C warmer than it really is.. The only true solution is to install room stats in each room (expensive)
