### ISSUE TITLE
Add support for Schneider Wiser Gateway

### ISSUE THREAD

**Issue by enoch85** [asantaga/wiserHomeAssistantPlatform#390]
It's now been around 1 year since I dug deep in this rabbit hole... Now I'm back with the same objective: trying to make everything I own in terms of "smart devices" to talk to HAOS (HACS). I just did a fresh install of HAOS 11, with a separate Zigbee2MQTT, so far so good. 

I noticed that you made some progress on this integration, but I can't seem to figure out if the [Gateway](https://www.se.com/se/sv/product/CCT501901/gateway-wiser-anv%C3%A4nds-som-n%C3%A4tverksnod-hanteras-via-wiser-by-seappen-zigbee-3-0-vit/) is supported yet, or not? You're talking about a "European version", but do you by that mean the Gateway? If not, this is officially a request for adding it.

If it's already supported, I'd like to know how to access the "secret" as described in the documentation. There's only 2 buttons on mine: Power and Reset. Nothing happens if I hit the Power button (holding it doesn't help), and since I have 55 devices connected, I' rather not reset it either without knowing it will work first. :)

Thanks for your great work!

**Comment by asantaga** [comment]
This integration was designed for the wiser Heating Hub. There is a european version of this that additionally supports window blinds and switches but it is not a gateway.

I will check with one of our users but I think the answer is no , its a different device :-(

in the core API I documented how to get the heathub secret key using steps documented here. Can you try them out , if you are able to get to step 4 then it might work and we can talk, but not then alas no this integration wont work.

https://pypi.org/project/wiser-heating-api/

**Comment by enoch85** [comment]
Ok thanks, will try.

Note to self: https://www.productinfo.schneider-electric.com/wiser_eu/wiser-system-user-guide-sweden-finland/Swedish/System%20User%20Guide%20(Sweden,%20Finland)_sv_0000773212.xml/$/CommissioningtheWiserHUBbyAPmodeTSK_sv_0000525969

**Comment by asantaga** [comment]
LGO44 on the HA thread (https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/2777) mentions its compatible with CT501801, yours is CT501901..

Give it a go and we'll add it to the list . I looked at the page (My swedish is rusty) but the shows the Wiser Gateway but also a Wiser Hub.. 

It maybe the hub is supported.. Alas needs testing, we're in the uk and only have the uk varient , which is way more limited to what u have there...

**Comment by enoch85** [comment]
OK, so I failed, but at least I made *some* progress:

### To enter the "setup mode" you have to:
1. Disconnect the ETH cable
2. Press the "R" button for 0.5 seconds
3. Now the middle LED starts to blink
4. Connect to the Wiser WIFI
5. Password is *wisersmarthome*
6. Begin with your testing....

### Progress
I thought I start with the most obvious

- 192.168.8.1/secret (didn't work so I scanned the network and found out that the "gateway" was on 192.168.220.114.)

Then I tried:
- 192.168.220.114
- https://192.168.220.114
- 192.168.220.114/secret
- https://192.168.220.114/secret
- 192.168.220.1/secret
- https://192.168.220.1/secret

That didn't work either, so I did a port scan and found this:

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/4511254/c5aa80e6-cf80-4c4a-a8c8-0c75b87d46ca)

So I tried the same URLs as above, but with the different ports.

- 192.168.220.114:39997
- 192.168.220.114:40557 (responded with a black screen, so it got connected, but no output)
- 192.168.220.114:46888
- 192.168.220.114:39997/secret
- 192.168.220.114:40557/secret
- 192.168.220.114:46888/secret
- 192.168.220.1:39997
- 192.168.220.1:40557
- 192.168.220.1:46888
- 192.168.220.1:39997/secret
- 192.168.220.1:40557/secret
- 192.168.220.1:46888/secret

Then I gave up. Anyone else that might have any ideas are super welcome to push me in the right direction. To me, it seems like they've hidden or removed the `/secret` function. Maybe because they noticed use cases like this app...? :smile:

**Comment by asantaga** [comment]
its likely a different device altogether, sorry :-(

Im closing this as alas I dont see how we can help here..

**Comment by enoch85** [comment]
Ok, almost gave up...

I realized I was a bit too tired, so the ports I got were my own device.............

I did a new port scan on the actual gateway, and now it starts to become interesting.

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/4511254/ea05e7b6-2b0c-4e98-a4a5-7c105a017d6f)

So I tried all the ports with the same method as above, but I thought port `6668` was extra interesting due to the - what looks like to be - a secret. So I jumped on my PC instead and did a curl:

```
daniel@xps9310:~$ curl --http0.9 -v http://192.168.220.1:6668
*   Trying 192.168.220.1:6668...
* Connected to 192.168.220.1 (192.168.220.1) port 6668 (#0)
> GET /secret HTTP/1.1
> Host: 192.168.220.1:6668
> User-Agent: curl/7.81.0
> Accept: */*
> 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

```
daniel@xps9310:~$ curl --http0.9 http://192.168.220.1:6668/secret --output wiser
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2675    0  2675    0     0     88      0 --:--:--  0:00:30 --:--:--   129
daniel@xps9310:~$ cat wiser 
U[3.3	�#�����w���$�,`7�uw�FEg��&Ze�f��e	�3?!_��/���A��*�v���N
                                                                     ���8�&$��UU[3.3
�R}�\�J���L�s͇/���
                 K}�=J�]��'�f��e	�3?!_��/��	j�Bs�;.�J'��atj�UU[3.3
                                                                              ���#���b�(:�,ʘQ��脓hH�F,6�f��e	�3?!_��/���6�;
�+.�K�g���UU[3.3
x���"a��Z��)?ׅ�6x���Sv��"�f��e�ʤ&�3?!_��/���}6Ú�-) �`?-b�������UU[3.33�b����a���~�����8�D������f��e	�3?!_��/���S�x<��i_vV�ò�f��e.3V_�3?!_��/���7+�|NT\��m|�
g������UU[3.3"ٗi�B	3i�W@�_����e���5C#9f��e	�3?!_��/������%��T�'��[M�4�X^�UU[3.3H�ĕ�ӛaöE$2�'
I�!L����)�13df��e	�3?!_��/�����2(-�B�@]�70��UU[3.3"ٗi�B	3i�W�F�\d�&y�Y�ȿ
                                                                                �f��e	�3?!_��/���� �kN\N�����!ayΎ��UU[3.33�b����a���~�ÚPW�l{�۪����f��e	�3?!_��/���	�J�G_q�kVI`�VR����UU[3.3�$՗��<8�w3���8f�LӦ
                                                                                  �:�m�ܿpP�f��e	�3?!_��/��
                                                                                                          ��P�d�N����m�Nܦ��UU[3.3E*R��;�S$�h�V���G��an5����Ʀf��e	�3?!_��/��@y(��:�r�O2]�UU[3.3����V�Le�Q��6�b0�1k��A+�۞f��e	�3?!_��/��K����N{�z����
                                                                                                                               ·t�UU[3.3�1����z3s�|n8y&�����VQyt�¡h/F�TY󓁁d�$�EFQ�V��˥iR)W X����UU[3.39����Q6qMȇ�p2��f߬��:'fGJ9f��e	�3?!_��/��)�!�vW}����n�YYq���UU[3.3�R}�\�J���L�s͇/s��Z�>��J��Of��e	�3?!_��/��֊���c�3�i/G'k.���B�UU[3.3����#���b�(:�,�-6n�a׈���`(a�f��e	�3?!_��/��wP9�n�Z$ɲ*�Ah�ֵ��UU[3.3X�*�[���.��2~b�/Kx�(S��TFf��e	�3?!_��/���r��q�9�@	���"�[��޽�UU[3.3,%�Og���m��C�<�N�r�G�k�=�%b�Tf��e	�3?!_��/��P�^�7�:\�o*�%J��UU[3.33�b����a���~�
6
U��UU[3.3E*R��;�S$�h�V�[�� ?�C�8��=ֹ*f��e	�3?!_��/��IJ�>�)jm����
```

And voila, at least we have a binary file now. Don't have a clue what to do with it, but I'll paste it here: https://cloud.danielhansson.nu/s/rqSyNAbrzXCGPk3

Maybe it's possible to convert a binary to text?

**Comment by enoch85** [comment]
And here's the binary output from the same file:

```
daniel@xps9310:~$ od -t x1 -c wiser | head -20

0000000  00  00  55  aa  00  00  00  00  00  00  00  08  00  00  00  5b
         \0  \0   U 252  \0  \0  \0  \0  \0  \0  \0  \b  \0  \0  \0   [
0000020  00  00  00  00  33  2e  33  00  00  00  00  00  00  1e  09  00
         \0  \0  \0  \0   3   .   3  \0  \0  \0  \0  \0  \0 036  \t  \0
0000040  00  00  01  ca  23  83  b6  ae  b2  e6  77  8d  c8  e3  24  ca
         \0  \0 001 312   # 203 266 256 262 346   w 215 310 343   $ 312
0000060  2c  60  37  a1  75  77  fd  46  45  67  0e  f3  8a  ce  26  5a
          ,   `   7 241   u   w 375   F   E   g 016 363 212 316   &   Z
0000100  1f  65  87  66  04  fc  e7  65  09  d8  33  3f  21  5f  a1  f5
        037   e 207   f 004 374 347   e  \t 330   3   ?   !   _ 241 365
0000120  2f  bf  e0  db  41  df  d0  2a  b9  76  b2  e2  f1  4e  0b  bb
          / 277 340 333   A 337 320   * 271   v 262 342 361   N  \v 273
0000140  8c  f0  38  fa  26  24  86  00  00  aa  55  00  00  55  aa  00
        214 360   8 372   &   $ 206  \0  \0 252   U  \0  \0   U 252  \0
0000160  00  00  00  00  00  00  08  00  00  00  5b  00  00  00  00  33
         \0  \0  \0  \0  \0  \0  \b  \0  \0  \0   [  \0  \0  \0  \0   3
0000200  2e  33  00  00  00  00  00  00  1e  0a  00  00  00  01  f5  52
          .   3  \0  \0  \0  \0  \0  \0 036  \n  \0  \0  \0 001 365   R
0000220  7d  fc  5c  ba  4a  a5  9a  ca  4c  f9  73  cd  87  2f  bd  83
          } 374   \ 272   J 245 232 312   L 371   s 315 207   / 275 203
```

**Comment by enoch85** [comment]
And here's the full output on that port

```
U[3.3	К#ѓ¶®ІжwЌИг$К,`7ЎuwэFEgуЉО&Ze‡fьзe	Ш3?!_Ўх/їаЫAЯР*№vІвсN
                                                                     »Њр8ъ&$†ЄUU[3.3
хR}ь\єJҐљКLщsН‡/ЅѓТ
                   K}т=Jг]цЂ'‰fьзe	Ш3?!_Ўх/їа	jгBs¦;.ЫJ'ЊуatjЄUU[3.3
                                                                              ц¶р#ьо°b“(:№,К
```

Just gibberish to me...
