### ISSUE TITLE
Unable to setup schedules

### ISSUE THREAD

**Issue by maxlock** [asantaga/wiserHomeAssistantPlatform#391]
Hi, I'm trying to add a schedule card to the dashboard. The card appears empty with a warning triangle in it. In the logs I get the following error repeated a few times:

homeassistant    | 2023-10-19 20:36:54.469 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140624796764480] Error handling message: Unknown error (unknown_error) max from 172.31.255.106 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0)
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
homeassistant    |     await func(hass, connection, msg)
homeassistant    |   File "/config/custom_components/wiser/websockets.py", line 149, in websocket_get_schedules
homeassistant    |     connection.send_result(msg["id"], sorted(output, key=lambda n: n["Name"]))
homeassistant    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    | TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

the diagnostics output looks like this:
[config_entry-wiser-09ce3b546d7d5960e47cb0622b6e6fa9.json.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/13047664/config_entry-wiser-09ce3b546d7d5960e47cb0622b6e6fa9.json.txt)

If you have any idea what the problem could be I'm all ears!

**Comment by msp1974** [comment]
It expects the schedules to have names and yours do not.  I think this is because you have a very old firmware version - 2.54, current is 3.14.  Presume you block it from the internet?  You will need to update firmware to resolve this.

**Comment by maxlock** [comment]
Thanks @msp1974 I tried to get the hub to take new firmware and edit the schedule from the app with no luck. I've left it connected to the internet overnight and it's upgraded and is now working. Thanks! :D
