### ISSUE TITLE
Passive TRVs requesting heat when no active TRV does

### ISSUE THREAD

**Issue by turilk** [asantaga/wiserHomeAssistantPlatform#395]
I have been using Wiser HA Integration for about a a month now, especially its passive mode functionality. There is a rather peculiar behaviour that I am unable to identify the root cause of, and I was hoping someone in the forum may be able to help:

I have a setup with 11 TRVs (4 bedrooms, 3 bathrooms, kitchen, dining room, reception room, hallway)

My config is as following:
 - Between 9am and 10pm, the reception room thermostat is the only non-passive thermostat set at 19C.
 - Between 10pm and 9am, the master bedroom thermostat is the only non-passive thermostat set at 21.5C.
 - All the remaining thermostats are set in manual passive mode to be between 17C-22.5C

 What I have been observing is that the thermostats set in passive mode randomly call for heat, even though the active thermostat is not when this happens. I also confirmed that when the passive mode thermostats call for heat, their temperature readings are not below the lower threshold of 17C that I set either. When this happens, not all passive thermostats call for heat either.

A clear example of this behaviour is the following period: November 2 - 09:00-15:00

- Reception thermostat is the non-passive one.
- Dining room thermostat is passive.
- In this period, dining room is requesting heat, even though the reception thermostat is not

![resim](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/30794942/2ee567bc-a93b-495f-a97e-9ef1eb47f94c)

In the logs, I cannot see anything besides an occasional connection error (see below):
```
2023-11-02 13:29:03.126 WARNING (MainThread) [custom_components.wiser.coordinator] Connection error trying to communicate with Wiser Hub 192.168.0.13 for url http://192.168.0.13:80/data/v2/domain/.  Error is Cannot connect to host 192.168.0.13:80 ssl:default [Network unreachable]
```

@msp1974 asked me to share
- a diagnostic file
- debug logs
in the Home Assistant Integration main thread: https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/2942?u=turilk 

I would appreciate it if you can share some details on how to capture / generate the above items.

**Comment by msp1974** [comment]
Have you managed to collect any debug logging?

**Comment by turilk** [comment]
Hello Mark,

I haven’t had the time to check it out yet, but I left debug logging
enabled. I will post a copy of the debug logs hopefully before weekend.

Thank you,
Ilker

**Comment by senna1992** [comment]
this might  be something like "get stuck prevention" / function check of the actual valves by the trvs.
else it could be a issued by wiser hub itself. Have you set anything there?

i would check like this:
does this also happen if you disable the integration on ha for a day or two?
it still happen if you set the shedule and temp right from wiser home (and HA is used just to read)?
is the shedule set using the integration identical with the one in wiser home app?

**Comment by msp1974** [comment]
Any further update on this @turilk ?

**Comment by msp1974** [comment]
Closing as no response and no other reports of this issue
