### ISSUE TITLE
Question - how cooling work?

### ISSUE THREAD

**Issue by vampywiz17** [asantaga/wiserHomeAssistantPlatform#397]
Hello there,

It is not a real "issue" but i would like ask something with wiser.

How to use this system exactly to cooling? If we connect it to a heat pump, how to handle the heat/cool zone? how it work the dewpoint sensors that possible to connect it to zone controller?

If somevody use it similar configuration, please answer this.

Thanks a lot!!

**Comment by msp1974** [comment]
I dont have this setup but you may find someone in the forum who can provide some insight, so recommend that you post this question there.

I'll close this issue as Angelo and I won't be able to help.
