### ISSUE TITLE
Relative modulation level is wrong

### ISSUE THREAD

**Issue by jacekowski** [asantaga/wiserHomeAssistantPlatform#398]
It seems like relative_modulation_level is still incorrect (even after #383 ) , however the issue seems more likely to be related to wiser hub itself rather than integration, but this place probably has the highest chance of finding someone who has an idea on how to fix it.

Based on my testing so far it seems like the hub is decoding response to id 17 incorrectly
![ot](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/9898247/43c1f2e3-6693-43cb-8cf8-dfcb78474f3b)

**Comment by msp1974** [comment]
I'm afraid we cannot correct issues with the hub firmware.  You will need to raise this with Wiser as they do not look at this github repo and Angelo and I are not associated with them.  They do however, read our forum page, link below:

https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965

As such, I will close this as not an integration issue.  Thanks for raising.
