### ISSUE TITLE
3rd party temperature sensors? 

### ISSUE THREAD

**Issue by dbrb2** [asantaga/wiserHomeAssistantPlatform#399]
This feels like something that is probably not possible...
The TRVs control the valves, but also measure room temperature. In general, right next to the valve is not the best place to measure room temperature. 

If it were possible via HA / Wiser integration to use the temperature from an arbitrary 3rd party sensor available within HA as the actual room temperature, that could make the Wiser system a lot more accurate - but I suspect this might need changes to the Wiser system itself...?

**Comment by msp1974** [comment]
No this is not possible without changes to the Wiser hub. You can add a roomstat to your room which does just this, however they are a bit pricey.. It is a much requested feature of Wiser to have a cheaper remote temp sensor but no plans as far as we know.  There is a hack in our recipees section of the wiki to use external temp sensors.
