### ISSUE TITLE
Safari (Mac) bug and wiki suggestion

### ISSUE THREAD

**Issue by adamquickfall** [asantaga/wiserHomeAssistantPlatform#405]
Hello,

I recently used this integration to get my newly-installed Wiser system onto Home Assisant and it's working really well. Amazing work! 

I think I may have noticed a bug: On Safari (Mac), editing a schedule via the 'Wiser Schedule Card' doesn't allow you to adjust the temperature. The slider to set temperature doesn't appear (image attached). However on Chrome and in the HA app, it works perfectly. 

I also have a suggestion for the 'Installation' part of the wiki, which would be a line about the instructions assuming everything is already fully set up via the Wiser Home app process (including thermometers paired to Hub and added to account). In hindsight this is pretty obvious, but I caused myself a lot of unnecessary problems by assuming I just needed to use the Wiser app to get the Hub on the no-internet HA network, then follow the HA integration instructions. 

<img width="484" alt="Screenshot 2023-12-04 at 21 21 12" src="https://github.com/asantaga/wiserHomeAssistantPlatform/assets/4619199/154dee8c-c663-4942-ae84-36acc4347791">

**Comment by msp1974** [comment]
I believe this is solved in v3.4.1 with update to schedule card to v1.3.2.  Please confirm.  Thanks

**Comment by msp1974** [comment]
Added note about settign up Wiser system first in Wiki.  Closing issue but please reopen if not resolved as I think.

**Comment by adamquickfall** [comment]
Thanks @msp1974. Sorry for the delay, I can confirm this issue is now fixed! The note is great too.
