### ISSUE TITLE
Hub won't connect since update to 3.4.1

### ISSUE THREAD

**Issue by Robbidoo** [asantaga/wiserHomeAssistantPlatform#412]
"Interestingly" I have two hubs connected and I am only seeing an error on one of them which is latest firmware 3.14.0.

The other is on 3.12.1 and working fine.

Logger: custom_components.wiser.coordinator
Source: custom_components/wiser/coordinator.py:155
Integration: Drayton Wiser Integration for Home Assistant ([documentation](https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/README.md), [issues](https://github.com/asantaga/wiserHomeAssistantPlatform/issues))
First occurred: 22:17:20 (8 occurrences)
Last logged: 22:21:06
Connection timeout trying to communicate with Wiser Hub <IP> for url [http://<IP>:80/data/v2/domain/](http://192.168.178.64/data/v2/domain/). Error is
<end of message>

Wiser Hub firmware 3.14.0
Hass version: 2023.12.2, Frontend: 20231208.2

Working fine through native phone app.

**Comment by msp1974** [comment]
Have you removed the IP address from the error message or is that what it says?

**Comment by Robbidoo** [comment]
Sorry yes that’s me removing it. The hub hasn’t connected since 3.4.1 was installed. On 13 Dec 2023, at 23:10, Mark Parker ***@***.***> wrote:﻿
Have you removed the IP address from the error message or is that what it says?

**Comment by msp1974** [comment]
OK, I think we need some debug logs from the api.  Can you ensure this is in your config.yaml, reboot and send the logs it generates from failing to connect to your hub.
```
logger:
  default: warning
  logs:
    aioWiserHeatAPI: debug
```

**Comment by msp1974** [comment]
OK good to hear.  If it does it again, feel free to reopen this issue with the debug logs.  I'll close for now.
