### ISSUE TITLE
History not showing when boiler is turned on.

### ISSUE THREAD

**Issue by silfax** [asantaga/wiserHomeAssistantPlatform#413]
I don't know if this is a bug, it is by design, has something to do with the mode my thermostat is currently working, or it's about the thermostat itself and not the integration, so apologies if I'm wrong. My thermostat is currently installed in an uninhabited house and is set to "away" mode, 10°C. Since temperature outside dropped towards 0°C during the past week, the boiler is shortly turned on at various time intervals in order to keep the temperature constant. However, when I expand the thermostat card and check the history, I cannot see when the boiler was turned on/off, I can see only the temperature chart. With other thermostats, the boiler cycles are shown in the history. Now, in order to check how the boiler is cycling, I need to check the electrical energy consumption of the boiler. Some screenshots below with the history as shown by Wiser, the history as shown by Hive (direct connection to HA via Z2M, no hub) and the power for the boiler as indicated by a smart plug. Should it work like that? Am I doing anything wrong? Thanks!
![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/65038681/1cdcfc53-4305-4dcf-8200-3508b201dae6)
![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/65038681/20db5880-578a-4746-a01f-4dd16c09ae2d)
![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/65038681/45248817-6bb4-4cc8-87bb-ddad0ccda41e)

**Comment by silfax** [comment]
ok, looking more closely, playing with the time scale, hiding some elements, etc., the heating cycles are there. just covered by the temperatures. sorry, my mistake.

**Comment by asantaga** [comment]
np , closing
