### ISSUE TITLE
Schedule Card Feature Request - Hide hot water options

### ISSUE THREAD

**Issue by codemunkie15** [asantaga/wiserHomeAssistantPlatform#415]
Hi

Firstly, thank you for providing this integration. It's an absolute game changer!

Would it be possible to optionally hide the hot water schedule in the schedule card please? I have a Kit 3 for multi-zone but don't use the hot water channel because I have a combi boiler.

Many thanks

**Comment by msp1974** [comment]
Will be in next release for you

**Comment by msp1974** [comment]
v3.4.2 just released including this feature request in schedule card.  Closing issue.

**Comment by codemunkie15** [comment]
Thank you!
