### ISSUE TITLE
Extension Won't Start

### ISSUE THREAD

**Issue by JIBYC** [asantaga/wiserHomeAssistantPlatform#416]
Hello,

Without consciously updating HA or the plugin I am getting the follow errors:

Error 1

Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 11:58:27 (3 occurrences)
Last logged: 11:58:41

Unable to install package aioWiserHeatAPI==1.5.1: ERROR: Cannot install aiowiserheatapi==1.5.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.2.1 -> 23.3.2 [notice] To update, run: pip install --upgrade pip

Error 2

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 11:58:41 (1 occurrences)
Last logged: 11:58:41

Setup failed for custom integration wiser: Requirements for wiser not found: ['aioWiserHeatAPI==1.5.1'].

**Comment by msp1974** [comment]
Sorry for late response.  You have updated the Wiser integration to 3.4.x and not updated HA to 2023.12.  This is a requirement to fix a problem caused by HA2023.12.
