### ISSUE TITLE
Drayton wiser integration boost service missing

### ISSUE THREAD

**Issue by motclem** [asantaga/wiserHomeAssistantPlatform#417]
siwhere along the line this has happened:

wiser.boost_heatingunknown service: wiser.boost_heating I think this might be related to the change to the climate entity am I missing something the integration works amid can control my raids from the dashboard.

**Comment by msp1974** [comment]
This service is still part of the integration.  Is the integration loading correctly?

**Comment by motclem** [comment]
yes afaik

**Comment by motclem** [comment]
deleting and reinstalling the integration has fixed it :)

**Comment by motclem** [comment]
deleting and reinstalling the integration has fixed it :)
