### ISSUE TITLE
The battery status is unavailable 

### ISSUE THREAD

**Issue by ialexyi** [asantaga/wiserHomeAssistantPlatform#421]
The iTRV battery powered devices doesn't show the battery level. 

Core
2024.1.0b0
Supervisor
2023.12.1
Operating System
11.3.rc1
Frontend
20231227.0

![Screenshot_20231228_231724_Home Assistant](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/7450073/5f6f6ef7-58a4-4261-9d2f-0f1c93c4ad70)

**Comment by ialexyi** [comment]
Has been fixed:
Firmware: 0.60.4

**Comment by bitlisz1** [comment]
I have same issue with all of my 12pcs iTRVs (fw.: 0.60.4) and 2pcs Room Thermostats (0.42.2).
Just suddenly all battery level goes unavaiable, and slowly comes back in 15-30min.
I did not find any in  HA logs. Just downloaded diagnostics log from integration, and enabled debug logging.
