### ISSUE TITLE
Access scheduled temperature as a sensor

### ISSUE THREAD

**Issue by Nilogax** [asantaga/wiserHomeAssistantPlatform#422]
I'm using Comfort mode and wanted to monitor how the heating is pre-empting the change in schedule setpoint.  I was hoping to use the target temp data but it seems that the target temp is set to the next scheduled temp at the time comfort mode turns the heating on rather than at the scheduled time.  I know I can read the current schedule to a file but is there a way to expose the scheduled temp data for charting?  Sorry if it's possible to do this with the current system but my skills don't extend that far (yet).

**Comment by msp1974** [comment]
You can see the next schedule time and temp on the climate entity attributes.  You will need to look at it in the dev tools states tab to see them.  You can make a template sensor from these attributes to allow you to chart history.

Sorry dont use comfort mode so not looked if these also advance to next setting when active.  Let me know if this doesn't work and we can look to add something.

**Comment by Nilogax** [comment]
Thanks - all sorted.  For info I templated a sensor from the current_schedule_temp attribute, which gave what I needed.
