### ISSUE TITLE
Enable passive mode for rooms without smart valves

### ISSUE THREAD

**Issue by meizon** [asantaga/wiserHomeAssistantPlatform#425]
I have one room on a zone (channel) that only has a room stat and no iTRVs however I'm unable to use passive mode.  I've tracked down the code:

https://github.com/asantaga/wiserHomeAssistantPlatform/blob/1437d1290251179c8b6a60b7b6f5c84f760bcd97/custom_components/wiser/switch.py#L182

Just interested as to why it needs smart valves for passive mode?

**Comment by msp1974** [comment]
Presume your rad has a standard trv? In which case it is already passive.  The rad will heat if other rooms fire the boiler already.  What you don't have is the ability to set a range but there is also nothing to stop the room heating past its top temp.

**Comment by meizon** [comment]
No, I have two rads in the room, both without TRVs. Even with non-smart TRVs, the room stat will still call demand from the boiler which is also what I'm trying to avoid.

**Comment by meizon** [comment]
To clarify, I have one room with a Wiser room stat, two radiators and it's the only room on one zone (channel).

**Comment by msp1974** [comment]
Still not understanding what passive mode will give you in your setup.  If that is the only room on a channel then it is wholly controlled by the roomstat. Why not just adjust temp/schedules on it? How will the room heat otherwise?

**Comment by meizon** [comment]
I was trying to use it as a way of having the demand for heat triggered less often. At the moment the demand will trigger more frequently as it'll try and maintain an exact temperature during the night for example. I'd much rather allow it to drop a degree or so, then heat for two degrees rather than cycle on and off every ten minutes. 

I appreciate that this isn't quite what passive mode was designed for.

**Comment by meizon** [comment]
Will close this out. Thanks for the discussion, I'll see what other way I might be able to achieve this.
