### ISSUE TITLE
Wiser Roomstat (CCTFR6400)

### ISSUE THREAD

**Issue by mulleer** [asantaga/wiserHomeAssistantPlatform#426]
I have an issue with the Wiser Wireless Smart Room Thermostat (CCTFR6400) 

HA shows only 2 sensors:

1. Battery
* battery_voltage: 3
* battery_level: Normal
* unit_of_measurement: %
* device_class: battery
* friendly_name: Wiser RoomStat Bureau Battery

2. Signal
* icon: mdi:wifi-strength-4
* friendly_name: Wiser RoomStat Bureau Signal
* vendor: Drayton Wiser
* product_type: RoomStat
* model_identifier: Thermostat
* firmware: 0000a412
* node_id: 23416
* zigbee_channel: 24
* displayed_signal_strength: VeryGood
* serial_number: 842E14FFFE6093D3
* hub_route: direct
* device_reception_RSSI: -48
* device_reception_LQI: 208
* device_reception_percent: 100
* controller_reception_RSSI: -51
* controller_reception_LQI: 196
* controller_reception_percent: 98
* humidity: 44
* temperature: 22

and 2 controls:

1. DeviceLock
2. Identify

but nothing about the target temperature ( and therefore no possibility to drive any of my Wiser TRVs )
The current temperature and humidity are available as attributes of the signal entity.

**Comment by msp1974** [comment]
Your roomstat needs to belong to a room and it is the room that has the target temperature and therefore controls the trvs.  Do you have this linked to a room?

**Comment by mulleer** [comment]
Ok, solved now. Thank you for the explanation and sorry for my
misunderstanding !

Le mar. 16 janv. 2024 à 03:01, Mark Parker ***@***.***> a
écrit :

**Comment by msp1974** [comment]
No problem. Feel free to post any questions you have on our HA forum page.  Lots of people on there who will help you.
