### ISSUE TITLE
State of Hub entities are updating only with long delay

### ISSUE THREAD

**Issue by areinhar87** [asantaga/wiserHomeAssistantPlatform#428]
Hi  - I started to work on a floorplan and spotted following issue:
I use wiser hub 2.0 incl. HA-Integration for controlling some lights in my house. I have got the issue that the state changes only with a long delay of approx 40-60 seconds. Has anybody the same problem?

**Comment by senna1992** [comment]
Do you experience the issue from within wiser app too?

I see some severe lag with powertag-E (resi9)
but that's on wiser side of things.


If no - outlets are comparable in speed to Z2m paired plugs

**Comment by msp1974** [comment]
They will only update when the integration updates from the hub.  The app constantly polls when in the foreground, so you will see updates much quicker but we cannot do it constantly in the integration as it will overload the hub.  You could set your update interval to 30s to make a little better.

As a note, if you turn them on/off from HA, you will see instantly as we update after any command.

Closing as unable to rectify this.
