### ISSUE TITLE
Your config file is corrupted and needs to be fixed to maintain all the functionality of this integration.

### ISSUE THREAD

**Issue by MikeBookham** [asantaga/wiserHomeAssistantPlatform#438]
I am seeing the following error every 30 seconds in the logs & cannot find anything in the documentation to help resolve corrupted config file:
_ERROR (MainThread) [aioWiserHeatAPI] Your config file is corrupted and needs to be fixed to maintain all the functionality of this integration._

A full reboot has made no difference.

**## System Information**
version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 27.8 GB
disk_used | 13.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Tailscale (0.15.0), File editor (5.7.0), UniFi Network Application (3.0.3), Studio Code Server (5.15.0), Advanced SSH & Web Terminal (17.1.0), Home Assistant Google Drive Backup (0.112.1), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 11
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 February 2024 at 22:21
-- | --
current_recorder_run | 11 February 2024 at 12:52
estimated_db_size | 224.64 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by msp1974** [comment]
In config/.storage is a file that is named wiserXXXXX that matches the name of your hub.  This is where we store settings for passive mode and manual temp settings.  If you can see what is wrong then fix it, if not, delete it and it will be recreated but those settings will be lost and things like passive mode re enabled.

**Comment by msp1974** [comment]
Will update the wiki with how to fix this or maybe give a better message.

**Comment by MikeBookham** [comment]
Thanks for the fast response.
I was in the process of upgrading ot Home Assistant OS 11.5 which too an age, which is why I didn't reply sooner.
Anyway, this issue is now fixed by deleting the file you specified. I have only ever configured the IP address of the Wiser hub via the integration UI, so not sure why there were entires in that file.

Contents of  the corrupt file:
```
{
  "Rooms": {
    "5": {
      "manual_temp": 5
    }
  }
}6": {
      "manual_temp": 12.0
    },
    "5": {
      "manual_temp": 5
    }
  }
}
```
Contents of the newly auto-rebuilt file aftwer abiove file deleted
```
{
  "Info": {
    "Version": "1.0.0"
  }
}
```
