### ISSUE TITLE
LTS Temperature of room reporting 0 a few times every day

### ISSUE THREAD

**Issue by Chaoscontrol** [asantaga/wiserHomeAssistantPlatform#439]
It's been a while that I've been seeing these drops in the graphs. 

- The issue only happens in this specific room/sensor. 
- This room has 3 iTRVs, and 1 room thermostat. 
- It's the only room in my house with a room thermostat, but I'm not sure that's a direct relation to the issue. 
- It reports 0 for 4 or 5 times every day. No time consistency. 
- Unsure if this is related in any way to my other couple weird reported issues: [here](https://github.com/asantaga/wiserHomeAssistantPlatform/issues/436) and [here](https://github.com/asantaga/wiserHomeAssistantPlatform/issues/434)

[23/02](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/6642238/698032fc-2346-45e7-9164-a11e726300bf)
[24/02](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/6642238/f272a938-480f-4508-b210-3363e6c67f6d)
[25/02](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/6642238/d02f0637-ebe2-426c-b43b-5dd93f02efd6)

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/6642238/ef0a943f-c30d-4964-8fd8-8a02189286d7)

It doesn't cause a massive issue, but [it messes up any graph I do forcing the Y-axis down to 0](https://file.coffee/u/r3SkJyxSdKN0ZmUh2PZ01.png).

**Comment by msp1974** [comment]
I suspect (without any in depth analysis) that it is related to some of your other issues, which again all relate to the hub sending poor data.  See my note on #434.

**Comment by Chaoscontrol** [comment]
I have not seen this happen for a few days now. Unsure if one of the API edits you asked me to do fixed that or what did, but something fixed it.

**Comment by msp1974** [comment]
Ok good.  I'll close for now but if you see it again, reopen it.
