### ISSUE TITLE
Wiser intergration

### ISSUE THREAD

**Issue by Foxdell1234** [asantaga/wiserHomeAssistantPlatform#440]
Please forgive me if I am doing this wrong, (still very new to home assistant and all the bits that can go with it)  however, I have this warning keep appearing in my logs.  

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: February 28, 2024 at 11:33:54 PM (9 occurrences)
Last logged: February 28, 2024 at 11:33:54 PM

Entity None (<class 'custom_components.wiser.climate.WiserRoom'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues

Is it anything to worry about or just a bug/glitch?

Thanks

**Comment by msp1974** [comment]
Firstly, no nothing to worry about. It is a depreication with an unnecessary warning message. Will not be removed until 2025.  Already an issue open #135, so will close this if thats OK.
