### ISSUE TITLE
Validation of translation causes log entry, happened before todays update too

### ISSUE THREAD

**Issue by senna1992** [asantaga/wiserHomeAssistantPlatform#443]
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:288
First occurred: 09:00:22 (2 occurrences)
Last logged: 09:00:22

Validation of translation placeholders for localized (de) string component.wiser.config.step.zeroconf_confirm.title failed
Validation of translation placeholders for localized (de) string component.wiser.config.step.zeroconf_confirm.description failed

Happens after restarting HA.
Can't download diagnostic information. "server dropped out" (translated from german)

**Comment by msp1974** [comment]
Resolved in v3.4.4
