### ISSUE TITLE
sensor.wiser_lts_target_temperature_main_bedroom reporting "Off"

### ISSUE THREAD

**Issue by Chaoscontrol** [asantaga/wiserHomeAssistantPlatform#447]
Found about this [here](https://github.com/home-assistant/core/issues/112038#issuecomment-1974865029). 

A sensor is never supposed to report "Off", but when the schedule contains a timeframe with "Off", that's what the sensor reports. I can reproduce this with any of the target sensors. 

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/6642238/67ac03cf-5cff-4a90-a6d2-49cdb8eda952)

**Comment by msp1974** [comment]
Ah, this is linked to #378, which do not have a good answer for.  We used to set it to -20C (which is what the hub actually reports when off but that caused complaints as graphs would then show a negative drop).  I guess we need to work out an answer.  Maybe best to set it to 0C?  I will ask in the forum for opinions.

**Comment by Chaoscontrol** [comment]
I think 0C makes the most sense, yes.

**Comment by msp1974** [comment]
I'm actually going to try and set it to None which shows unknown in the sensor and see how that goes.  We were also previously setting the units to None if off, so stopping that too.

**Comment by Chaoscontrol** [comment]
Cool, just posted in the forum that unknown` might be a good option too based on [this](https://github.com/home-assistant/core/issues/78805#issuecomment-1254372817).

**Comment by msp1974** [comment]
Sensor now reports as unavailable in v3.4.4 - just released
