### ISSUE TITLE
1.8 cannot import name 'TEMP_MINIMUM'

### ISSUE THREAD

**Issue by relaystar** [asantaga/wiserHomeAssistantPlatform#45]
just deployed v1.8 using HACS:

> Component error: wiser - cannot import name 'TEMP_MINIMUM' from 'wiserHeatingAPI.wiserHub' (/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py)

The component doesn't initialise

**Comment by Afterdark1st** [comment]
I have the same problem after the update today ------
 Component error: wiser - cannot import name 'TEMP_MINIMUM' from 'wiserHeatingAPI.wiserHub' (/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py) ?

line 16 to 22 i think 

import homeassistant.helpers.config_validation as cv
import voluptuous as vol
from homeassistant.const import (CONF_HOST, CONF_MINIMUM, CONF_PASSWORD,
                                 CONF_SCAN_INTERVAL)
from homeassistant.helpers.discovery import load_platform

from wiserHeatingAPI.wiserHub import (TEMP_MINIMUM, TEMP_MAXIMUM)

**Comment by daylehouse** [comment]
Same here, v1.8 has stopped any of my wiser components working.

**Comment by mrvladis** [comment]
It seems like I am lucky. Still works for be both in HA and NodeRed.

**Comment by relaystar** [comment]
it would appear that the problem here is that:
> https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/custom_components/wiser/manifest.json

hasn't been updated to reflect the new release of the wiser-heating-api to 1.0.3

indeed manually editing this and rebooting this allows the component to initialise

**Comment by asantaga** [comment]
thanks, fixed

**Comment by Afterdark1st** [comment]
manually editing to 1.0.3 and then rebooting the hardware ie pc worked for me

**Comment by asantaga** [comment]
release 1.8.1 fixes this, sorry. My install automagically upgraded the pypi library - not sure how.
1.8.1. now specifies 1.0.3 of the pypi library..

Bit of a PITA I thought Id be able to upgrade the base library without having to release HA Component but ho hum.....

**Comment by Afterdark1st** [comment]
Thanks for the update all is working well,
would like to add a BIG thanks for the plugin and all your hard work

**Comment by daylehouse** [comment]
Awesome fixed for me also, excellent!
