### ISSUE TITLE
One of the two heating channels is unavailable on a 3 channel hub after updating to 3.4.4

### ISSUE THREAD

**Issue by robertwigley** [asantaga/wiserHomeAssistantPlatform#450]
On a three channel hub, it appears that one of the channels is going unavailable after the update to 3.4.4. Reverting to 3.4.3, brings back nomal operation and availability. Strangely, this is Channel 1, rather than Channel 3.

![333c67ab90b03856246e913d272a111cf81f9fc8](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/12278920/b6d67477-aa36-4a38-96f9-cf90454f1b42)

This is on my Dad's system, rather than miine. He has a 3 channel hub. Channel 1 is ‘Downstairs’, channel 2 is “Hot Water” and Channel 3 is “Upstairs”. There are no iTRVs in either room/zone, just a room thermostat in each.

He has one other room called “Kitchen”, which is an Electrical Heat Switch and room thermostat controlling a plinth heater. There are no other rooms related to the central heating though.

Demand for all three channels also becomes “Unknown”:

![d2c11c49eebf29ed21884585473d1a07f07aaf1b](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/12278920/c49a877c-81ee-494b-9d4e-ba079a4c50e2)

Diagnostics file attached as requested:
[config_entry-wiser-f557d97c366c528cca5a6c3f0fd2ef6f.json](https://github.com/asantaga/wiserHomeAssistantPlatform/files/14494999/config_entry-wiser-f557d97c366c528cca5a6c3f0fd2ef6f.json)

**Comment by msp1974** [comment]
OK, so I have run your diag file in my mock hub against v3.4.4 and it works fine.  Not really sure why not working for you.  Are there any log errors?

**Comment by msp1974** [comment]
AH, actually, yes I can recreate.  It is related to the issue with heating actuators in v3.4.4 per #449, stopping other sensors loaded.  Will have this fixed shortly.

I also saw another issue with the naming of the heating on/off sensors with multiple channels, so thanks.

**Comment by robertwigley** [comment]
Sorry to say it, but no change in 3.4.5. It's still showing `unavailable` and the demand sensors `unknown`.

The following is shown in the log:

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:599
Integration: Climate (documentation, issues)
First occurred: 14:00:06 (1 occurrences)
Last logged: 14:00:06

wiser: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 530, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 263, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 289, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/wiser/sensor.py", line 1196, in _handle_coordinator_update
    self._state = self._data.wiserhub.devices.get_by_id(self._device_id).get(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_WiserHeatingActuator' object has no attribute 'get'
```

**Comment by msp1974** [comment]
OMG! Think I need a holiday.  Do you want to redownload the update - forgot to push dev branch!

**Comment by robertwigley** [comment]
Appears to be resolved now redownloaded with the updated API. Thanks Mark. 👍
