### ISSUE TITLE
number of problems with a heatingactuator

### ISSUE THREAD

**Issue by scooper1** [asantaga/wiserHomeAssistantPlatform#454]
1] The first issue is the current_temperature: is showing 17.3 it should be 20.1 - the long-term stats show the correct value - and so does the attached debug file

from the developer pannal state page 
climate.wiser_heatingactuator_kitchen_under_floor_heating_floor_temp

Wiser HeatingActuator Kitchen under floor heating Floor Temp heat
hvac_modes:
min_temp: 5 max_temp: 39
target_temp_step: 1 
current_temperature: 17.3
target_temp_high: 27 
target_temp_low: 5 
icon: mdi:radiator-off 
friendly_name: Wiser HeatingActuator Kitchen under floor heating  Floor Temp
supported_features: 2

2) this device keeps going unavailable  - this may be all the wiser devices and has been happening since the latest current updates -- it is all wiser devices  this is a new issue

3)  the debug file shows  "Status": "Output_Thermal_Limit"  - limit is 27c debug file shows 20.1c - this might be a wiser firmware bug as the actuator keeps cycling  - but not sure how to raise that with wiser tech support  as only available in the home assistant debug file - do you have any contacts with them -  i do have problems with the actuator keep turning off during 100% heat demand

[config_entry-wiser-30d0221bdd6d4fefb2036c62b2af5cbb.json](https://github.com/asantaga/wiserHomeAssistantPlatform/files/14515152/config_entry-wiser-30d0221bdd6d4fefb2036c62b2af5cbb.json)

**Comment by scooper1** [comment]
to fix point 2  i had to downgrade to 3.4.2 to get a stable connection

**Comment by msp1974** [comment]
So 3.4.3 is doing it too?

**Comment by scooper1** [comment]
i could not get a connection with 3.4.3 even  after restarting hub

**Comment by scooper1** [comment]
it has been an adventure  trying to find out what was happening heating actuator with multiple issues - made even worse that the heating actuator has to be coupled with a roomstat to be able to configure the thermocouple on the actuator 
I only got the actuator this week to try and bring in the heated floor floor into the wiser system   
I have tried to raise point 3  with wiser tech support but not hopeful I am going to get a sensible reply 
I also have raised a feature request to be able to configure the actuator temperature probe without having  a room stat in the  same group

**Comment by msp1974** [comment]
I'll run your debug in my mock hub later and see if i can find issue with the  current temp. And have a look at the unavailable issue.  I have some other people reporting this too.

In regards your point 3, i suspect output thermal limit maybe not to do with max temp but a thermal cut out. Is it overloaded and that is why it is cycling.  Dont really have any contact that can help you other than going through support.

**Comment by msp1974** [comment]
Ok, so been looking at this and have a few updates:

**Issue 1**
I cannot see any issue with the reported current temp.  Using the debug file you gave me presented 20.1C (this is on v3.4.5).  I checked that the LTS sensor is using the same parameter from the api, so this would lead me to believe it is the climate sensor not updating.  Could be maybe related to issue 2, along with issue 3 - are there any errors in your logs?


**Issue 2**
The going unavailable issue...... 

So, I am making a change to stop the sensors going unavailable, just because it is concerning most people who have a similar problem to you.  However, the reason they go unavailable is because it failed to update from the hub.  v3.4.3 -> v3.4.5 is trying to fix some of the reasons that hub updates were failing (since changes to aiohttp back in Dec 23 and some issues with the hub itself that I am trying to discuss with Wiser) but also introduced making sensors unavailable if it did fail (not 100% intentional but a newer function of some of the HA core code).  However, stopping them becoming unavailable is just masking the issue.  I have made it log a warning however, so you will continue to see in the logs.  These changes will be in v3.4.6.

Now, the big question is why your hub is failing to update and how frequently is it actually doing it.  From v3.4.5 onward, I would suspect it is likely a timeout issue.  I think we have been over your wifi before but what is it?

Side Note: I did, whilst looking at this, find an issue with the number slider that allows you to change the offset temp for your floor heating (I guess you maybe didn't have it as it was failing to load), but that will be fixed in v3.4.6 too.

**Comment by msp1974** [comment]
Ah mesh wifi. That will he why so many drop outs.  They sort of fixed it with a much quicker reconnect but nothing that reduced disconnects on mesh.  Lot less noticeable as they can last only for a few seconds to a few mins now whereas before they were 2 hours.

I would say that I bought a cheap TPLink extender and connected that to my mesh wifi and the hub to it on a different SSID.  Made a massive difference.  In fact, due to a kitchen refurbishment, the extender is some 20 feet from hub and often shows poor signal from hub in integration but it drops out far less than my test hub that is still on mesh and about 5ft from main router.  Maybe worth a try.

**Comment by scooper1** [comment]
I can turn off fast switching to stop the hub from wandering between points   I will try that.  Had to do that for a Google doorbell .  You got to love old houses with clicker blocks in the walls.  The blocks contain lots of iron slag

**Comment by scooper1** [comment]
Um how do you get the hub to change network.   I have a Access point for my car that different ssid and is not a mesh

**Comment by msp1974** [comment]
You'll love this simple, user friendly method!

Put it in setup mode and go to the app and log out of your account.  If you then go back to the first page in the app you can select Get Started -> Professional Installer option to go through the initial hub setup and change wifi.  It does not remove all your devices etc.

**Comment by msp1974** [comment]
Also, just fyi, ive done some more work on update routine to eliviate connection timeouts and to stop entities going unavailable if update does fail.  Will be released as 3.4.6 later.  Would appreciate you trying and see if it resolves your issues.

**Comment by scooper1** [comment]
Will do   
Wifi change might be tomorrow so dont lose heating tonight....

Currently adding another two roomstats to system and another actuator to control wet room floor 

⁣Get BlueMail for Android ​

**Comment by scooper1** [comment]
Just in case it might be another bug can't show as looks like a 3.4.5 item  maybe.

The actuator temperature room was showing as a current temperature as range  from 5c to current temperature looks normal on 3.4.2  5c being protected temperature.  Maybe as in passive mode but I have not used that on my system 

Thanks

⁣Get BlueMail for Android ​

**Comment by msp1974** [comment]
> Just in case it might be another bug can't show as looks like a 3.4.5 item  maybe.

> The actuator temperature room was showing as a current temperature as range  from 5c to current temperature looks normal on 3.4.2  5c being protected temperature.  Maybe as in passive mode but I have not used that on my system

No clue what this means, can you elaborate.

**Comment by scooper1** [comment]
the value shown when a round thomostat is shown  the center number was a range 5,20 I think

**Comment by msp1974** [comment]
I think what your saying is the centre should be current temp.  If so, no the centre is the target temp - this is not the target room temp but for managing the floor temp range used to heat the room to the rooms target temp.  With the floor sensor this (afaik) is a range as can be seen in the diagnostics.  

```
"FloorTemperatureSensor": {
            "MinimumTemperature": 40,
            "MaximumTemperature": 270,
            "Offset": 0,
            "SensorType": "NTC_10K",
            "MeasuredTemperature": 201,
            "Status": "Output_Thermal_Limit"
          }
```

The bug however I can see is that the min temp is showing as 4C but we limit the min to 5C (as that is what the min is on the rest of the hub temp params).  What is the min this can be set to in the app?

**Comment by scooper1** [comment]
i may have changed the min temp as I setup new zone since debug file 
if the range is how you expect this to work - ok  I was just expecting the measured temperature to show
the range shown in gray is confusing - but if that is how ha handles it ok 

I will try new version tomorrow

any ideas appreciated for the following, nothing to do with your integration - when I set up the first underfloor zone once roomstat was added the wiser app allowed me to set the ntc type and over items.   my second underflow heating zone is not showing the settings for ntc type etc 
the seams to be different versions of firmware in the roomstats  I have tried switching the two versions of roomstat between the different zones but zone 1 continues to see the floor temp and second zone does not

**Comment by scooper1** [comment]
i think the above stat picture is strange as no mode is set - looks more like cooling mode as the colour is above the set point not the range

I have tried the 3.4.6  getting some no-reply logs but I would semi-expect those 

good work thanks working much better


I do seem to be getting a string to float conversion error  - the log follows

2024-03-08 16:58:45.303 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for climate.wiser_back_room to <Job track state_changed event {'climate.wiser_back_room'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ state_attr('climate.wiser_back_room', 'control_output_state') }}) renders=100>: <RenderInfo Template<template=({{ state_attr('climate.wiser_back_room', 'control_output_state') }}) renders=100> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'climate.wiser_back_room'}) rate_limit=None has_time=False exception=None is_static=False>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'On'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'On'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 330, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 727, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1262, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 727, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 434, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
ValueError: Sensor sensor.wiser_back_room_demand has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'On' (<class 'str'>)

**Comment by msp1974** [comment]
I'll have a look at the floor sensor climate entity for next release.  The changes with this thermostat card have caused many issues over how the old one worked.

The error you are seeing looks like its coming from a template sensor.  Is it one?

**Comment by scooper1** [comment]
Not sure about template 
I am using apxcharts card that uses template to avoid repeating large amounts of coding 
Would that affect it - I did bring up the thermostat by clicking on entry shown by card ?  Can attached the Lovelace yaml file it that helps. I also use the button card which does same sort of thing. But I am not using ha template file entries as far I know

**Comment by msp1974** [comment]
No.  This sensor is a template sensor

sensor.wiser_back_room_demand

And I'm guessing is designed to show on or off based on value of
```
state_attr('climate.wiser_back_room', 'control_output_state')
```

**Comment by msp1974** [comment]
Im going to close this issue as the original problem is fixed but will open a new one re the floor temp climate entity.

**Comment by scooper1** [comment]
fixed my problem with the template sensors - forgot I had put those in configuration yaml - deleted them as they were done before you could extract attributes directly, thanks for help
