### ISSUE TITLE
Not an issue: Smoke detector works except smoke sensor

### ISSUE THREAD

**Issue by senna1992** [asantaga/wiserHomeAssistantPlatform#457]
The latest update provides me with its battery percentage and signal state 😁

Thought of this being relevant for you! 

Any way to provide you with some beer or coffee?

**Comment by msp1974** [comment]
Yes, its now supported in the api and all attributes are their.  I have been doing some big rewriting of the integration where all these will then be in HA but with all the issues with connectivity, i have not had time to finish it.

I wont be available to work on this for next month or so but will hopefully have released by May.  It will make it massively easier to add new things / requested sensors etx as they come along.

**Comment by msp1974** [comment]
To tease you!!!! 

![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/11211952/595ec63d-388a-4753-af2a-a0ffe0bb9c28)

**Comment by senna1992** [comment]
Hi msp,

Any ETA for the next release?
running 3.4.6 with 4 smoke detectors now.

happy to test  and report in real use for you =)

**Comment by msp1974** [comment]
Sorry for late reply.  I have been very busy on other things.  There will be an update this weekend with this functionality in it for you.

**Comment by msp1974** [comment]
v3.4.8 released with some alarm sensors.
