### ISSUE TITLE
future change request: Wiser "MEG5161-0000" with "MEG5113-0300"Relais button switch "does not report a color mode"

### ISSUE THREAD

**Issue by senna1992** [asantaga/wiserHomeAssistantPlatform#458]
Logger: homeassistant.components.light
Quelle: components/light/__init__.py:914
Integration: Licht (Dokumentation, Probleme)
Erstmals aufgetreten: 8. März 2024 um 23:55:15 (1 Vorkommnisse)
Zuletzt protokolliert: 8. März 2024 um 23:55:15

light.licht_8 (<class 'custom_components.wiser.light.WiserLight'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues

debug info will be uploaded asap

**Comment by msp1974** [comment]
Thats fine re the debug info.  This is another HA change that changes allowed standards.  Will fix in next update.  Thanks.

**Comment by msp1974** [comment]
Implemented in v3.4.7.  Closing this issue.  Thanks for raising.
