### ISSUE TITLE
Question: Can Home Assistant talk to Wiser TRVs without a controller?

### ISSUE THREAD

**Issue by marklam** [asantaga/wiserHomeAssistantPlatform#460]
Just a question, not a bug!

Background:
> It looks like my heating system would be suited to a system with a 2 channel Heat Hub, but my existing controller hasn't died yet so I don't want the upheaval of replacing the proprietary 3-port valve that's in there currently.

What I'm wondering is, whether I could fit the Wiser TRVs and talk to them with Home Assistant using your integration without having to have the hub yet, so I can set their target temperatures (perhaps on a schedule) but use my old controller to actually do the heating/circulating side of things.

My follow-on question would be - when I do get to the point of adding the "Heat Hub", will Home Assistant co-exist with the Hub, or would I have to give total control of the TRVs to the Hub?

Sorry if this is the wrong place to ask this, but I thought that you probably have the best direct experience of this area!
Thanks.

**Comment by msp1974** [comment]
Mark,  no our integration only talks to the hub on http.  All the wiser devices are zigbee and therefore need a zigbee controller to talk to them (which is what the hub is - albeit a closed one).  As a note, there are often hubs on ebay that people have bought on a deal for the trvs and roomstats, so selling just the hub only - and often pretty cheap.  I have seen 3ch (2 heating plus 1 hw) for about £90-£100.

In terms of your second question (prob obvious now based on answer to 1), the hub will always control the TRVs etc and then our integration sends commands to the hub and reads data from the hub.  Most of the work in managing your heating is done by the hub (with or without our integration) and you can see our integration as being like the Wiser app but you are able to automate things and combine other HA sensors to drive these automations (which obviously the app cannot do), graph data over time, manage your heating and other smart devices in one place (the HA app).

As a second note, there are some people using ZHA or Zigbee2MQTT with HA to control these but I did hear there were issues but not sure if that works well or not.  My advice would always be get the hub.  It has lots of smarts to manage your heating and is worth the money in what it can save you, together with our integration.

However, warning - it will turn you into a heating bore! ;-)
