### ISSUE TITLE
Unable to set Hot Water on or off in automation

### ISSUE THREAD

**Issue by darrenaf** [asantaga/wiserHomeAssistantPlatform#466]
I've looked at most of the entities and can set the hot water from Auto to Manual, but there doesn't seem to be an option  to turn it on or off.  There's and entity sensor.wiser_hot_water which is recording the state, but I can't see an obvious way of getting this from within an automation.

**Comment by msp1974** [comment]
The is a button  to toggle hot water.  It's not perfect and I do intend to make a switch for on/off but there was a reason we didn't in the first place that I need time to research.

See wiki for further help.

https://github.com/asantaga/wiserHomeAssistantPlatform/wiki/Functionality#hot-water
