### ISSUE TITLE
Slow updating of sensor

### ISSUE THREAD

**Issue by w4kanaka** [asantaga/wiserHomeAssistantPlatform#469]
This happened the first time today

2024-04-18 03:39:03.135 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.wiser_lts_temperature_handtuchheizkorper (<class 'custom_components.wiser.sensor.WiserLTSTempSensor'>) took 1.081 seconds. Please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues

Home Assistant OS 12.2

Core
Version
core-2024.4.3

Supervisor
Version
supervisor-2024.04.0

Wiser Home Assistant Integration v3.4.6

[config_entry-wiser-10ecdc1ecf39c71cceb1910d3f2bf52b (1).json](https://github.com/asantaga/wiserHomeAssistantPlatform/files/15049632/config_entry-wiser-10ecdc1ecf39c71cceb1910d3f2bf52b.1.json)

**Comment by msp1974** [comment]
I never really understand this HA issue as, because we are pre-fetching data to then provide during entity updates, this means that it is actually HA causing the slow delay - possibly high utilisation on your hardware at the time the updates ran.

Will close this as no real action to be taken by this integration.

**Comment by w4kanaka** [comment]
Ty for ur time and explanation. As said it has been the first time i noticed that „issue“, just followed instructions. Enjoy ur day,RobVon meinem iPhone gesendetAm 03.05.2024 um 19:36 schrieb Mark Parker ***@***.***>:﻿
I never really understand this HA issue as, because we are pre-fetching data to then provide during entity updates, this means that it is actually HA causing the slow delay - possibly high utilisation on your hardware at the time the updates ran.
Will close this as no real action to be taken by this integration.
