### ISSUE TITLE
Allow un-assigning schedule from wiser.assign_schedule service

### ISSUE THREAD

**Issue by bfayers** [asantaga/wiserHomeAssistantPlatform#470]
I need the ability to un-assign the schedule from the service as well as assigning. I noticed it's possible over the HASS websocket by setting remove: true, but that isn't implemented in the service.

**Comment by msp1974** [comment]
Added in v3.4.7 to allow you to assign an id of 0 to room/device to remove assigned schedule.  See wiki notes for usage.

https://github.com/asantaga/wiserHomeAssistantPlatform/wiki/Services#assign-schedule
