### ISSUE TITLE
Card font size cannot easily be changes

### ISSUE THREAD

**Issue by Anobium** [asantaga/wiserHomeAssistantPlatform#477]
Latest update changed the card layout. All very nice except the font size is not adjustable.. with ease.

![Screenshot_20240507_070655_Home Assistant](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/17933379/e7a199a2-1332-4f86-945f-cfb15845b226)

Whilst I am here.. the current temp being a small dot on the arc of the circle is very small. This should be a lot larger, or, a color filled large circle.

But, overall. A great job!

**Comment by msp1974** [comment]
This card is part of HA and not this integration - it has no ability to make these changes.

Closing as not integration related.
