### ISSUE TITLE
Boost/Cancel/Toggle Hot Water and Cancel Heating Overides no longer working

### ISSUE THREAD

**Issue by rlewis187** [asantaga/wiserHomeAssistantPlatform#480]
As title really, the hot water controls are no longer provided by the integration according to Home Assistant
![image](https://github.com/asantaga/wiserHomeAssistantPlatform/assets/80640955/f1602d51-98ed-474b-aed5-f1a7fc4f1148)

Here is the error when I tried to cancel the hot water:
```

Logger: homeassistant.helpers.service
Source: helpers/service.py:279
First occurred: 17:42:26 (11 occurrences)
Last logged: 17:47:41

Referenced entities button.wiser_cancel_hot_water_overrides are missing or not currently available
```

Hub Firmware : 3.18.3
Home assistant version  2024.5.2 
Integration Version: 3.4.7

**Comment by msp1974** [comment]
Are there any other errors in the log (particularly when HA starts)?  Was it HA2025.5.2 that caused them to disappear or v3.4.7? And if you go back to v3.4.6 do they now appear?

**Comment by rlewis187** [comment]
Not sure when they disappeared tbh, I just updated HA to the latest version and they haven't come back. I will revert to an old version of the integration now and report back.

**Comment by rlewis187** [comment]
They came back when reverting to 3.4.6.

**Comment by msp1974** [comment]
Ah, sorry ive just twigged the issue.  There was an issue in 3.4.7 that stopped these working if you had moments configured.  This was fixed and re-released.  Prob not a good idea in hindsight.  If you redownload v3.4.7 it will work.

**Comment by rlewis187** [comment]
Thanks MMark, that has fixed my issue.
