### ISSUE TITLE
Not getting cards

### ISSUE THREAD

**Issue by olbasoil** [asantaga/wiserHomeAssistantPlatform#484]
I don't get the schedule or network cards installed after downloading via Hacs and configuring the integration. I have deleted the integration and re-installed, but still no cards available when editing my dashboard. I do have all my ITRV's showing as entities

This is version 3.4.7 

Is there a way I can install these separately?

**Comment by msp1974** [comment]
Have a look in resources (edit dashboard -> 3 dots at top right, resources).  They should be listed in there.

You may have to do a shift-F5 (sometimes see the caching is a bit too agressive).

**Comment by olbasoil** [comment]
Found them. Many thanks
