### ISSUE TITLE
How do I connect the Wiser Hub - CLP501902

### ISSUE THREAD

**Issue by 123gizi** [asantaga/wiserHomeAssistantPlatform#487]
Hi,
I'm in Australia and I'm trying to get the API key from my Wiser Hub but I can't work it out. Are you able to provide any further guidance?
It is the CLP501902 model (https://www.sparkydirect.com.au/p/Clipsal-Iconic-Wiser-CLP501902-Wiser-Smart-Hub-Zigbee-Enabled), connected via ethernet, connection via WiFi tried but still no luck.
I tried the Australian Schneider Electric support but was told they don't have an open API that they can share with me...

I tried getting via a cURL command (https://community.home-assistant.io/t/wiser-hub-secret-key/574433/4) to the ip assigned by the router but it times out. Any thoughts?

**Comment by ian1182** [comment]
For the UK hub the curl command is issued to the 192.168.8.1 address as this is done whilst the hub is in setup mode. It's not the address your router hands out once the setup process completes. It's a fixed address built into the hub itself. That assumes your hub is compatible with the steps.

If you have an android phone it's also possible to obtain the hub api key using the packet capture app available in the Google play store. As the name implies it captures the traffic from phone to hub.

**Comment by 123gizi** [comment]
@ian1182 Thanks for the reply. I've downloaded PCAPdroid, selected the wiser app and I'm looking at the PCAP file generated on my PC using Wireshark but there's no obvious API key or Secret Key that I can locate. I do have the session IDs but they're all random with nothing consistent. This is my first time trying to sift through a PCAP, is there a specific line I should be looking for?

Also, when I press the setup button, it appears to power cycle and flashes for a short period but no SSID appears for me to connect to - Do I need to reset the hub? I'm reluctant to do so, as I don't want to run around the house setting everything up again...

**Comment by ian1182** [comment]
I suspect your hub is not compatible. Your the hub looks nothing like the UK/Fr/De models

https://wiser.draytoncontrols.co.uk/

 An example piece of output from packet capture would look like this, I have masked the secret in my case but it leaps out like a sore thumb. You don't need to use wireshark as it's visible in the capture app on your phone

GET /data/v2/network/Station/ConnectionStatus HTTP/1.1
Secret: ##############################################
Wiser-app-version: 6.11.0
Host: 192.168.1.77

HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Transfer-Encoding: chunked

B
"Connected"
