### ISSUE TITLE
Save function missing on Wiser Zigbee card editor

### ISSUE THREAD

**Issue by Thomasba58** [asantaga/wiserHomeAssistantPlatform#488]
I can't say when this occured currently running v3.4.7 but there is no longer a save layout function on the wiser zigbee card when you try to edit the layout.
It used to be to the left of the refresh button, which would save the layout and then there is another save button below the refresh to save the card. that one still exists but layout is no longer saved.

It used to be where I've circled in red.
<img width="761" alt="Screenshot 2024-07-12 094211" src="https://github.com/user-attachments/assets/0cd63125-2839-45e6-9b89-693b83a8f87a">

**Comment by msp1974** [comment]
Cannot see any issue wiht this.  Is it still the same?

**Comment by Thomasba58** [comment]
Hi nothing has
<img width="1152" alt="Untitled" src="https://github.com/user-attachments/assets/fa64efc1-c76c-4c50-abac-8bd3004dee19">
 changed the Save layout is still missing

**Comment by msp1974** [comment]
OK, let me look some more.

**Comment by msp1974** [comment]
OK, this should now be resolved in 3.4.8 - just released.

**Comment by Thomasba58** [comment]
All working perfectly now thankyou.

**Comment by LGO44** [comment]
all is OK now 
@msp1974 thanks for your job
