### ISSUE TITLE
[3.4.8] Smoke Sensor integration has no per device mapping 

### ISSUE THREAD

**Issue by senna1992** [asantaga/wiserHomeAssistantPlatform#496]
HI, 

i am happy to report seeing all of my smoke detectors in HA now,
i even got more information (+Heat Alert +Remote Alarm) comapred to the Wiser home app :)
amazing work =)

![2024-09-07 21 21 18 192 168 0 42 89eec525bf12](https://github.com/user-attachments/assets/368cd834-1771-43c0-9dcd-fc4e7da0f609)

If its possible it would be good to have them be listed in their repsective devices instead of 1 containing multiple multiplied entities. (which of the 4 is which? trying all of them out with some test spray might annoy my neigbours :-]

[config_entry-wiser-9b53e456ad3705a3e39faa20b40d008b.json](https://github.com/user-attachments/files/16919689/config_entry-wiser-9b53e456ad3705a3e39faa20b40d008b.json)

![2024-09-07 21 24 21 192 168 0 42 2e83a837c5e6](https://github.com/user-attachments/assets/8b5f684d-5c5d-4b75-91c9-aab39587c504)

**Comment by msp1974** [comment]
Ah, sorry, should be seperate devices.  Thanks for the diag file.  Will sort this in next few days for you.

**Comment by senna1992** [comment]
Anything I can help you with, 
Translation or testing stuff maybe?

**Comment by LGO44** [comment]
> Ah, sorry, should be seperate devices. Thanks for the diag file. Will sort this in next few days for you.

Hello Mark, I have done some modifications in my repository for the smokealarmdevices, and the Hub V2. I will push the repository in a PR in this repository.
Of course I m ready to discuss all the modifications

**Comment by msp1974** [comment]
Sorry for the delay, but this should now be resolved in 3.4.9 - just released.
