### ISSUE TITLE
network card does'nt work

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#498]
hi 
the network is not well reported on chart
![Screenshot_20240928_153106](https://github.com/user-attachments/assets/30a31d7d-9a44-4132-ac9e-d96f8499cc2b)

**Comment by asantaga** [comment]
Is this still an issue? Ive not seen it and I think we'd need debug logs

**Comment by enthalpie91** [comment]
OK could'you explain how i got debug log ?
Best

**Comment by enthalpie91** [comment]
hi i found a log under 
/homeassistant/custom_components/wiser/frontend/wiser-zigbee-card.js
it is very long !!! sould I send it ?

**Comment by msp1974** [comment]
This is because most of your devices are connecting to your boiler interface device which is not yet supported as per issue #499 .  Should resolve when this is added to the api.

**Comment by msp1974** [comment]
Resolved in v3.4.10.
