### ISSUE TITLE
CCTFR6001 Boiler Interface support

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#499]
hello
first many thanks for the job !!!!!! 
I have a new hub ref CCTFR6310 (CCT501801) and a boiler interface CCTFR6001 
I see in the interface only one apparatus , I think It is a agregate of the 2 item ? like if i have only one CCTFR6311G2
could you confirm ?
![Screenshot_20240930_134339](https://github.com/user-attachments/assets/03a2e5ad-3ea5-4242-823b-973f2d9365b6)

in a second time i will connect the boiler with Opentherm and i would be sure this will be ok  ( Issue 489 ?)
Regards

**Comment by enthalpie91** [comment]
And may be it is in relation, i have post one another issue, the network is wrong

**Comment by msp1974** [comment]
Sorry for the delay, but this should now be resolved in 3.4.9 - just released.
