### ISSUE TITLE
Implement the ability to set current target temperature 

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#5]
todo

**Comment by asantaga** [comment]
work in progress..

**Comment by asantaga** [comment]
started work on this, code nearly done just one little bug where python is unable to find the function in the main python library.. 

totally baffled why.. will look again tomorrow but if anyone else sees whats wrong please let me know :-)

**Comment by sjtbham** [comment]
You're working on the wrong object that is why ... needed to add a method on object `WiserHubHandle` also. The PR above adds this method.

Note also that the temp is coming in as e.g. 19.5 but it needs to be sent as 195. I did some basic testing with this against my heatHub and a room thermostat (I don't have any TRVs to test with).

**Comment by asantaga** [comment]
that's embarrassing.... 

I went to a conference last week and was gonna look at it with fresh eyes.. but awesome to have you work it out.. 

very embarrassing :-)
