### ISSUE TITLE
no value for Boiler return and depart température 

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#500]
Hi
I would like to see the boiler water temperature ( depart and return)
"wiser_lts_boiler_return_temperature"
I get no value
IS because CCTFR6001 is working mode ON/OFF , that mean theses values are available when Opentherm mode is set or something else ? like CCTFR6001 is not seen at this time behind the hub CCTFR6310
Best

![Screenshot_20241002_194634](https://github.com/user-attachments/assets/dbf944b7-5ef7-47c6-b4b4-b10e1543a572)]

**Comment by msp1974** [comment]
Yes, these are only available if using opentherm connection to boiler.  If you are not using opentherm, you shouldn't get this sensor.  Will need to look at why you are. If you provide a diagnostic file, I will look at if this can be integrated correctly.

**Comment by enthalpie91** [comment]
@msp1974 
No no. i have reconducted the running mode i had with wiserhome  (on//off) in a first time to see if everythings works. 
In a second time i will connect the boiler on OT protocole , ,but before i want to be sure

**Comment by msp1974** [comment]
As per issue #502, I will provide a fix so that these do not show if not in Opentherm mode, but will create (after a reload) if you switch to opentherm mode.

**Comment by enthalpie91** [comment]
HI 
I should said something with my poor English
I took the decision to leave SE and Wiser because they don't want to support my boiler on OT mode. the OT mode is drive with an additionnal card, working fine with google Zigbee and other soft. 
so I Look at open solution with zigbee and discover HA and decide to move to 
I am pretty sure HA and your integration will work on OT mode , I am in hurry to test
Best and congratulation for the job

**Comment by msp1974** [comment]
This should now be resolved in 3.4.9 - just released.
