### ISSUE TITLE
to be able to add and remove and link device in HA

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#501]
At this time, it is necessary to have wiser apps to add and link new device in wiser home
Is it possible to have this function in the wiserhomeassitant ? 

Best

**Comment by asantaga** [comment]
No, unfortunately FWIK you cant , you need the App for this . @msp1974 ?

**Comment by enthalpie91** [comment]
Ok May be latter ? 
Best

**Comment by msp1974** [comment]
Hi, yes, it would be possible but the level of work needed to do this is likely too great for the value.  Sorry, you'll have to use the app when you spend all that money on new devices! :-)
