### ISSUE TITLE
LTS Humidity Sensors go to zero when integration loses contact with hub

### ISSUE THREAD

**Issue by Kalma-House** [asantaga/wiserHomeAssistantPlatform#503]
As the title says, whenever contact is lost with the wiser hub the lts humidity sensors go to zero. I believe this behavior is wrong. They should behave in the same manner as the lts temperature sensors, which keep the last measurement until contact is regained.

This is more than an aesthetics issue. I use the lts humidity sensors to drive generic hygrostats in HA, and the behavior of the sensors wreaks havoc with the functioning of the hygrostats.

Thanks

Javier

**Comment by msp1974** [comment]
Hi, thanks for logging. Yes this is a known issue that is long overdue a promised fix.  I will sort in the next week or so.

**Comment by Kalma-House** [comment]
Thank you for your fast reply and looking forward to the fix.

Great integration, by the way. I have been using it for two years in two different places and I love it.

Javier

**Comment by msp1974** [comment]
Sorry for the delay, but this should now be resolved in 3.4.9 - just released.
