### ISSUE TITLE
Attributes for adjusting cycle rates for weather compensated boiler

### ISSUE THREAD

**Issue by nbullus** [asantaga/wiserHomeAssistantPlatform#504]
My weather compensated boiler has variable flow temperature dependent on outside temperature. With the minimum 'on' time for 10 min Gas cycles of just 2 mins, I often find that by the time the boiler has fired up and pumped low water temperature to rads, Wiser then turns off for 8 mins. I find that sometimes the room can lose more heat in the 8 mins it is in the 'off' state than it puts back into the room in the 2 minutes it is in the 'on' state. This means that it can take a long time to get that the last 0.5-1 deg of temperature into the room when its running on the minimum 2 mins of 'on' time.

Does the API have access to the cycle rate (cycle length and minimum 'on' time) that we could change? This is to allow us to increase the minimum 'on' time so that the boiler turning on has some effect on the heat in the room running low temps before it then turns 'off'.

**Comment by msp1974** [comment]
Afraid not. You could play with the boiler type setting in the app.  This adjusts cycle times but I can not tell you what each one is.  Maybe someone on the forum can advise.

Will close this issue as we cannot do anything through the api.
