### ISSUE TITLE
Wiser Shutter / Blinds not reachable

### ISSUE THREAD

**Issue by SaschaHilberg** [asantaga/wiserHomeAssistantPlatform#506]
Hi,

My shutters / blinds suddenly are not reachable anymore. I even removed the intergration. After I re-installed it the entities were reachable for some hours but then suddenly they again lost connection. Restarted HO, installed all updates. Nothing fixed the issue. 

Do you have any idea?

Thanl you well. 

Cheers
Sascha

**Comment by msp1974** [comment]
Please can you provide a diagnostics file when they are unreachable.  Thanks

**Comment by SaschaHilberg** [comment]
Hey, Thanks for ur feedback. Not sure how to do this. Can u pls assist?

**Comment by msp1974** [comment]
In HA in Device & Services, select Drayton Wiser and then 3 dots next to Configure button, gives option to download diagnostics.  Just upload it to this issue - it is obfuscated for any sensitive data

**Comment by msp1974** [comment]
Have you been able to get a diagnostic download?

**Comment by msp1974** [comment]
Closing as no response.  Please reopen with a diagnostic download if you want help with this issue.
