### ISSUE TITLE
If WiserService is not available integration fails and never recovers

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#51]
If for whatever reason the wiserhub is down the integration will fail and not recover gracefully. 
need to look at refactoring code so that it becomes more resilient to failures.

**Comment by asantaga** [comment]
From 
https://github.com/asantaga/wiserHomeAssistantPlatform/issues/46

It appears if there is a network issue then the base code gives a NoneType exception which cascades down..
The bug here is in the base wiserapi code, whats happening is on many getXXX operations Im not checking for "NoneType" responses. This would occur if there was no response. 

What Ive done is opened issue https://github.com/asantaga/wiserheatingapi/issues/13 on the wiserapi and I'll look to protecting the responses so that if the response is "NoneType" then I'll respond with an  empty JSON Array.

The issue here is nowever that the init of the base class is only executed when the component is first loaded.. Im not sure how we could force a refresh of the component if an error has occured.. or programatically (via a service request)

**Comment by msp1974** [comment]
Angelo,

Have been looking at this and will send you a pull request.  I looked at the rflink component to see how it is done and it basically schedules to run the setup again if it fails.  Just doing some testing first but looks promising.

I am also going to raise an issue to improve handling of the hub going offline after HA start.

**Comment by asantaga** [comment]
dude, all your PRs are starting to make me look lazy!!!!

reviewing code, but looks fab.

**Comment by asantaga** [comment]
PR #64 is hopefully a fix for this. Will reopen this if its still an issue

**Comment by asantaga** [comment]
Reopening, 

I want to fix https://github.com/asantaga/wiserheatingapi/issues/13 before closing this

**Comment by asantaga** [comment]
Closing as asantaga/wiserheatingapi#13 work was done. 

With the new async model implemented its much more robust
