### ISSUE TITLE
Birghtness for rotary switch not showing up when changed outside HA or in other situations

### ISSUE THREAD

**Issue by hmoreau94** [asantaga/wiserHomeAssistantPlatform#518]
Hi, 

First of all thanks so much for the time you put into this project. 

I'm unclear with the best way the post this issue but let me know if the format is incorrect or if you're missing any relevant information. 

I have a lot of NHROTARY/DIMMER/ (dimmer rotating switch, which reference is SCHS520513W at Schneider) that are connected to a Wiser Hub 2nd gen (Firmware 4.36.33). 

It seems that the brightness percentage doesn't show up properly in the UI. Here are a couple of examples to reproduce: 
- Turn on the light from the UI: open for more detail, the brightness seems to be at the lowest 
- If I change the brighness from outside HA (either manually through the switch or through the wiser app) it doesn't show in Home assistant. 

Here is a screenshot of the light's attributes from dev tools, from the Dashboard (main and more info) and from the wiser 
![Screenshot 2024-11-03 at 21 59 55](https://github.com/user-attachments/assets/a1c542c6-4acb-427
![Screenshot 2024-11-03 at 22 00 01](https://github.com/user-attachments/assets/62595521-bc4d-4dd0-9787-d2f6fbe47a79)
9-b7ad-714d6cb87f66)
![Screenshot 2024-11-03 at 22 00 25](https://github.com/user-attachments/assets/7fd8243b-d642-4982-87ea-129074e91dbd)
![IMG_5029](https://github.com/user-attachments/assets/1e079eb2-7c20-4d4b-b4a1-ad5cb9ddc525)

It seems that the attribute: `current_percentage` shows up the 51% yet on other light, this seems to be usually an information that is reported by `brightness` (at least that's what I got from trying to observe my dimmable ikea bulbs) 

Any chance we could get this working ? 
Best, 
Hugo

**Comment by hmoreau94** [comment]
Also this log started showing up since the last update: 
![Screenshot 2024-11-03 at 22 14 33](https://github.com/user-attachments/assets/78bb1a0f-016d-49d0-9fe8-802cd335f101)

**Comment by msp1974** [comment]
That's great detail on the issue.  Can you also provide a diagnostic download from the 3 dots on the integration  in devices and services, click Drayton Wiser integration and 3 dots menu there.

Don't have the hub2 or any of the nice devices in UK so we can only go off this download to make things work.

Thanks

**Comment by hmoreau94** [comment]
For sure: also do let me know if I can help in any way (used to be a computer science engineer, but now working in product management and my HA skills are just new out of the box ;) )

[Home Assistant Config Entry.json](https://github.com/user-attachments/files/17612136/Home.Assistant.Config.Entry.json)

**Comment by msp1974** [comment]
Ok great.  I think the issue and the log messages are related.  I think there is a typo in the colormode setting which is causing this.  I have a couple of other issues to fix and will release an update tomorrow that should get it all working.

**Comment by hmoreau94** [comment]
Awesome, do let me know once done, I'll give it a good test. Have a great evening ! On 3 Nov 2024, at 22:34, Mark Parker ***@***.***> wrote: Ok great. I think the issue and the log messages are related. I think there is a typo in the colormode setting which is causing this. I have a couple of other issues to fix and will release an update tomorrow that should get it all working. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by msp1974** [comment]
OK, just released v3.4.11 that should fix your brightness issue.

**Comment by hmoreau94** [comment]
Hey Mark, works like a charm thanks so much !
