### ISSUE TITLE
not important version ???

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#520]
hi
i have the last installed but the screen show the version  before ?
best
![Screenshot_20241105_093619](https://github.com/user-attachments/assets/78243ba1-c641-4114-b5d8-2ced6347b241)

**Comment by msp1974** [comment]
Yep.  Missed updating manifest.json with 3.4.11 release.  Will get updated with next release.  Thanks for pointing out.

**Comment by msp1974** [comment]
Fixed in v3.4.12 (cannot retro fix v3.4.11 after release)
