### ISSUE TITLE
Wiser integration no longer works

### ISSUE THREAD

**Issue by V1nc3** [asantaga/wiserHomeAssistantPlatform#523]
Hello
Since last night, without having changed anything, the Wiser integration no longer works.
Here's the error message I got in the logs: 
_Enregistreur: custom_components.wiser.coordinator
Source: custom_components/wiser/coordinator.py:198
intégration: Drayton Wiser Integration for Home Assistant ([documentation](https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/README.md), [problèmes](https://github.com/asantaga/wiserHomeAssistantPlatform/issues))
S'est produit pour la première fois: 20:34:51 (27 occurrences)
Dernier enregistrement: 20:47:10

Unknown error fetching wiser (wiser-WiserHeat043F1F) data. list index out of range. Please report this error to the integration owner_

I restart ,HA and the Wiser box and I forced the update to version 3.4.11 (I was in 3.4.10) but it didn't change anything.
Thanks for your help

Vince.

**Comment by asantaga** [comment]
can you check network connectivity between you HA host and the hub?

**Comment by V1nc3** [comment]
I can ping the hub from the HA terminal

**Comment by msp1974** [comment]
Seems like there is something funny with the data coming from your hub.  I assume your Wiser app is working?  If so, im going to need a download from it to see whats wrong.

As you wont be able to do through HA, are you able to use postman or something similar to get this if i tell you how?

**Comment by V1nc3** [comment]
Yes, I can confirm that my Wiser application (on my cell phone) works fine.
Tell me what you need and how to get it and I'll do it :)

**Comment by msp1974** [comment]
OK, in Advanced SSH & Web Terminal addon do this (install it if you haven't already) or if you are not running a supervised version of HA (ie cannot install addons), run from a linux terminal of some kind (but you may need to amend the output path from /config/[x].json):

```
curl -H "SECRET: [YOUR HUB SECRET]" http://[YOUR HUB IP]/data/v2/[LIST ITEM]/ > /config/[LIST ITEM].json
```

where 
- [YOUR HUB SECRET] is your hubs secret key that you used to setup the integration in the first place.
- [YOUR HUB IP] is the IP address of your hub
- [LIST ITEM] is each of the following
  - domain
  - schedules
  - network
  - status

So you should run 4 times like this.

```
curl -H "SECRET: [YOUR HUB SECRET]" http://[YOUR HUB IP]/data/v2/domain/ > /config/domain.json

curl -H "SECRET: [YOUR HUB SECRET]" http://[YOUR HUB IP]/data/v2/schedules/ > /config/schedules.json

curl -H "SECRET: [YOUR HUB SECRET]" http://[YOUR HUB IP]/data/v2/network/ > /config/network.json

curl -H "SECRET: [YOUR HUB SECRET]" http://[YOUR HUB IP]/data/v2/status/ > /config/status.json
```

Ensure the '/' is at the end of the url as the hub can be fussy about that,

This will then create 4 files in your config directory which you need to send me.  I can then use this to run through my mock server and see what it wrong and hopefully provide you a fix.

Any questions or if this doesn't make sense, please ask.

**Comment by V1nc3** [comment]
[status.json](https://github.com/user-attachments/files/17731850/status.json)
[schedules.json](https://github.com/user-attachments/files/17731851/schedules.json)
[network.json](https://github.com/user-attachments/files/17731852/network.json)
[domain.json](https://github.com/user-attachments/files/17731853/domain.json)

Here are the requested files

**Comment by msp1974** [comment]
Perfect.  Have to go out this afternoon but will look at it tonight.

**Comment by V1nc3** [comment]
No prob, I can manage my Wiser with my mobile cell ;)
Thank you again for you help.
See you

**Comment by V1nc3** [comment]
In fact, going back to version 3.4.8 works. So I've disabled automatic updates.

What do you mean by “button panel”? Did you see it in the list of devices connected to my Wiser?
In fact, my Wiser drives :
- the heating control
- the comfort box/panel, which gives temperatures and controls the heating
- all the light switches in the house.
- entrance switch for programming scenarios (when you leave and return home)

**Comment by msp1974** [comment]
Ah, yes I assume it is the Odace as it has some configured event actions, Pressing top button I guess is home and bottom button away mode?  I'll add that so it at least shows in the devices with signal etc.  Can't at this stage decifer if there are any control functions.  But if we discover those later, we can also add.

**Comment by V1nc3** [comment]
Yes that's it !! :)

**Comment by msp1974** [comment]
If you want to download v3.4.12 - this should fix and also show you Odace signal etc (will also now show in zigbee card).

**Comment by V1nc3** [comment]
I've installed V3.4.12: it works like a charm! 👍 

As for the Odace box, I'm having trouble identifying it under HA . I can't see any of the items that have a state that changes when I activate it.

**Comment by msp1974** [comment]
There is nothing on this device that shows any state, therefore no state changes.  If you look in devices and services, Drayton Wiser devices, you will see it listed with a signal strength and device lock and identify options only.  As we have to poll the hub, there is no way to get if it has been pressed as this is purely through the zigbee network to the hub, which then does an action on the hub.

As this issue is fixed, I'll close it but if there are other functions that could be explored, please open a seperate issue for it.

**Comment by V1nc3** [comment]
Thank you again for your help !
