### ISSUE TITLE
Add support for PowerTagC (hub v2)

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#528]
Taken from #393 .

Add support for new powertagc device.

[config_entry-wiser-dc6e868f3db7376365194efe9d66c848.json](https://github.com/user-attachments/files/17870458/config_entry-wiser-dc6e868f3db7376365194efe9d66c848.json)

**Comment by msp1974** [comment]
Initial support in v3.4.13.  @parvarm, can you please upgrade and give feedback.  Thx

**Comment by parvarm** [comment]
Works like a charm ! Thanks so much.

**Comment by msp1974** [comment]
Great.  Will close this issue now.  Thanks
