### ISSUE TITLE
Add support for 2 gang light switch (hub v2)

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#529]
Taken from #393 

Add support for "ProductModel": "2GANG/SWITCH/1"

[config_entry-wiser-d548df494a35df2948de330b915b7cf0 (1).json](https://github.com/user-attachments/files/17882094/config_entry-wiser-d548df494a35df2948de330b915b7cf0.1.json)

This needs a rearchitect of the api.

**Comment by msp1974** [comment]
Should be fixed in v3.4.13.  @ChrisZ-18 can you please confirm all looks good now.

**Comment by ChrisZ-18** [comment]
@msp1974 Mark great Work!  
Can confirm the 2Gang Switcht show up. Jjust a minor thing: both are marked 2GANG/SWITCH/2.
I would have expected that one the two would be 2GANG/SWITCH/1. But both objects work as expected. 

<img width="1245" alt="Bildschirmfoto 2024-12-03 um 19 03 07" src="https://github.com/user-attachments/assets/14ee7abe-62cc-49f4-8c34-60423645f9c9">

Also leakage and Motion Sensor is now showing up. Perfect that helps my setup a Lot!
Big Thanks!!!

**Comment by ChrisZ-18** [comment]
@msp1974 Mark there is a Bug in the Motion and Leakage Sensor they show of with signal, battery  and  brightness (for the Motion sensor) signal. But there is no motion or leakage event available.

**Comment by msp1974** [comment]
> @msp1974 Mark great Work! Can confirm the 2Gang Switcht show up. Jjust a minor thing: both are marked 2GANG/SWITCH/2. I would have expected that one the two would be 2GANG/SWITCH/1. But both objects work as expected.

No the model from the hub is  2GANG/SWITCH/2.

**Comment by msp1974** [comment]
> @msp1974 Mark there is a Bug in the Motion and Leakage Sensor they show of with signal, battery and brightness (for the Motion sensor) signal. But there is no motion or leakage event available.

Moving this comment to the right issue.
