### ISSUE TITLE
Fix support for WindowDoor and WaterLeakage sensors (binary sensors)(hub v2)

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#530]
Taken from #393 .

While we have added support for some binary sensors, it appears not working fully.  Investigate and resolve.

**Comment by LGO44** [comment]
Hi Mark,

I'm developing the windowdoorsensor with a switch to enable "interacts with the room" and a select for the notification...
How can I help you?

![image](https://github.com/user-attachments/assets/b106ea7b-4f96-40dd-af01-5383088b14dd)

**Comment by LGO44** [comment]
For the windowdoor sensor, the option are OnEither and None.

I think that the options you propose should be used by other sensors.

**Comment by msp1974** [comment]
Main support for these sensors in v3.4.13.  Needs the notification selector adding.

**Comment by msp1974** [comment]
From @ChrisZ-18

@msp1974 Mark there is a Bug in the Motion and Leakage Sensor they show of with signal, battery and brightness (for the Motion sensor) signal. But there is no motion or leakage event available.

**Comment by LGO44** [comment]
For me, on window door sensor  it's OK

**Comment by msp1974** [comment]
Added this to v3.4.14 but do not expect a real time notification as it will only pick it up each time it updates from hub.  In the case of motion sensors, this may not actually happen unless motion is exactly same time as query,

**Comment by ChrisZ-18** [comment]
@msp1974 It works Mark, but as you mentioned, there is be a very long delay. So in Case of Motion Sensor it is mostly unusable with Lights. 
Leakage Sensor works also, but the delay here is more acceptable. Tanks a Lot!

**Comment by msp1974** [comment]
Np.  Will close this as now supported.
