### ISSUE TITLE
Add support for Temperature Humidity Sensor (thresholdsensors) (hub v2)  

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#531]
Temperature Humidity sensor represent an alternative to the roomstat (cost effective)

Device level
![image](https://github.com/user-attachments/assets/49feb847-8ce3-4362-85e0-775be5fee818)

ThresholdSensor:

![image](https://github.com/user-attachments/assets/cc2c6750-1828-4bbd-9e0a-19745587ac92)

My result
![image](https://github.com/user-attachments/assets/90e29b5a-c05d-42c9-9bb7-5232d2d8d108)

A wiser TemperatureHumiditySensor generate 2 threshold sensors.

aioWiserHeatAPI: file threshold_sensor.py
[threshold_sensor.zip](https://github.com/user-attachments/files/17874728/threshold_sensor.zip)

I create the temperature sensor but not the humidity one

extract of sensor.py of the wiserHomeAssistantPlatform
 _    # Add a sensor temperature for temperature humidity sensor
    if data.wiserhub.devices.threshold_sensors:
        _LOGGER.debug(
            f"  Setting up TemperatureHumidity sensor {data.wiserhub.devices.threshold_sensors.count} LTS Temperature sensors"
            )
        for threshold_sensor in data.wiserhub.devices.threshold_sensors.all: 
            _LOGGER.debug(
            f"  Setting up {threshold_sensor.quantity}   {threshold_sensor.device_id} {threshold_sensor.threshold_id}   LTS Temperature sensors"
            )
            if threshold_sensor.quantity == "Temperature":           
                wiser_sensors.extend(
                    [
                        WiserLTSTempSensor(data, threshold_sensor.id, sensor_type="temperaturehumidity_temp"),
                        WiserThresholdSensor(data, threshold_sensor.id, )  ,
                    ]  
                )
            elif threshold_sensor.quantity == "Humidity":            
                wiser_sensors.extend(
                    [
                        WiserLTSHumiditySensor(data, threshold_sensor.id,sensor_type="temperaturehumidity_humidity"),
                        WiserThresholdSensor(data, threshold_sensor.id, )               
                    ]
                    )            
_

**Comment by msp1974** [comment]
Hi @LGO44.  Can you send me a diagnostic file with a temp/humidity sensor in it please.  I have reworked the api and have the threshold sensors working but do not have a test file with one of these sensors.

**Comment by LGO44** [comment]
Hi @msp1974 
here is a diagnostic file with windowdoorsensor (binary sensor) and TemperatureHumiditySensor (threshold sensor)...
 Feel free to give me your code to test.
[config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json](https://github.com/user-attachments/files/17925289/config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json)

**Comment by LGO44** [comment]
@msp1974 I'm testing your dev integration.
I don't see any temperature humidity sensor. I see that you have add the temperature given by the sensor to the room, but not the humidity. ?
My remark is made because I expect that its behavior shoudl be like a roomstat.
This sensors can switch also if it interacts_with_romm_climate

**Comment by msp1974** [comment]
Thanks for the diag file btw.

This is because on all other data I have seen, the threshold sensor is more like an additional sensor value to the main device sensor.  However, in your case (or more the case of this temp/humidity sensor), it only has 2 threshold sensors, so there is no main sensor to add these to.

Need to think more about this if threshold sensors can be the only thing, extra things, 1 or many etc!!

**Comment by LGO44** [comment]
all is OK now
Thanks a lot.
![image](https://github.com/user-attachments/assets/7c1a06e8-5319-4921-8f3b-0a3dcbfaae98)

I have a question, what do you think about linking the humidity and temperature to the room by creating LTS sensors to be consistent with the roomstat?

**Comment by msp1974** [comment]
> I have a question, what do you think about linking the humidity and temperature to the room by creating LTS sensors to be consistent with the roomstat?

I think no for now as if it is not interacting with room climate then it would make no sense.  Also, when it is interacting with room climate, does it not provide the room temp like a roomstat does anyway?

It maybe that these should be stats sensors (ie what the LTS named sensors are).

**Comment by LGO44** [comment]
Thanks a lot for your job
