### ISSUE TITLE
no more schedule after last update HA

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#532]
hello
after the update of the last HA core, i can't see wiser schedule and other sensor
![Screenshot_20241123_080353](https://github.com/user-attachments/assets/b4f92e2a-7aa1-479c-b569-66cdfe79621e)

`## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1461
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 116.8 GB
disk_used | 14.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Zigbee2MQTT (1.41.0-1), Mosquitto broker (6.4.1), File editor (5.8.0), Log Viewer (0.17.1), Let's Encrypt (5.2.3), Samba share (12.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 12
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 novembre 2024 à 19:12
-- | --
current_recorder_run | 23 novembre 2024 à 07:00
estimated_db_size | 5489.79 MiB
database_engine | sqlite
database_version | 3.45.3

</details>`

**Comment by enthalpie91** [comment]
there is echec to config
![Screenshot_20241123_080809](https://github.com/user-attachments/assets/ee846873-928c-4c4a-b201-d1affbbffe3d)

**Comment by enthalpie91** [comment]
HI
it is solved !! the hub was disconnect  ??? don't know why and how , looks like since yesterday when i update HA core ??

**Comment by enthalpie91** [comment]
i will be nice to be advertised if the hub is disconnect

**Comment by msp1974** [comment]
You could create yourself an automation to notify you if you want from the attributes on the Operation Mode sensor.  We don't do this as not everybody wants notifying.,
![image](https://github.com/user-attachments/assets/79ebbaad-0d37-446f-a889-55047c321a48)

**Comment by enthalpie91** [comment]
think this is a reply to one other issue ???? If so do you mean i can create a new entry for these and set a low température ?
