### ISSUE TITLE
Can't find /secret endpoint

### ISSUE THREAD

**Issue by locke4** [asantaga/wiserHomeAssistantPlatform#533]
Having some trouble getting the secret key. I haven't tried SSL decryption of the packet stream from a phone as I don't have an android phone I can use for this.

I have a UK hub and I'm running firmware version 3.18.3. I have put the hub into setup mode (pressing setup button once) and connected to the wireless AP. My PC got an IP address on the 169.254.33.0/24 subnet from the wiser hub. I tried a couple of things like `Invoke-RestMethod -Method Get -UseBasicParsing -Uri http://169.254.33.1/secret/` (also tried 192.168.8.1) but didn't get a response. Running nmap and I can't see the wiser hub on any address in that subnet (only my PC at the .2 address). I also tried a PowerShell script to loop over every possible IP in the subnet and I didn't get anything at the /secret endpoint for any IP address.

Is there another way of retrieving the secret from an already set up hub?

**Comment by msp1974** [comment]
If your machine has a 169.xxx address it means it didn't get one from the hub.  You should be getting an IP of 192.168.8.x on your PC. Once you solve that the http://192.168.8.1/secret will work.

Have you got any smartphone to do this with?

**Comment by locke4** [comment]
Worked great on a smartphone, thanks! Apologies didn't think it mattered what device I used!
