### ISSUE TITLE
mode out on schedule

### ISSUE THREAD

**Issue by enthalpie91** [asantaga/wiserHomeAssistantPlatform#534]
hi
on wiser home i have a option "out" which put temperature at a low level 
is it possible to have this in the program view, ou should we create something ?
best

**Comment by msp1974** [comment]
This is away mode and is a switch on the hub device entity.

**Comment by enthalpie91** [comment]
hello
i am not sure to understand, you means that allready exist ? could you help me more to find this?

**Comment by enthalpie91** [comment]
I think i have found !!!
![Screenshot_20241126_110416](https://github.com/user-attachments/assets/a19ec33b-5a29-42e1-b3b3-6dcf1e4a3e92)

thank's !!!

**Comment by enthalpie91** [comment]
closed
