### ISSUE TITLE
Error on startup (3.4.14)

### ISSUE THREAD

**Issue by kzipkzip** [asantaga/wiserHomeAssistantPlatform#541]
Updated to 3.4.14 - all working fine, but I did notice an error in my logs as follows;

> Logger: homeassistant
> Source: custom_components/wiser/climate.py:1046
> integration: Drayton Wiser Integration for Home Assistant ([documentation](https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/README.md), [issues](https://github.com/asantaga/wiserHomeAssistantPlatform/issues))
> First occurred: 14:45:00 (1 occurrences)
> Last logged: 14:45:00
> Error doing job: Task exception was never retrieved (None)
> 
> Traceback (most recent call last):
>   File "/config/custom_components/wiser/climate.py", line 1046, in run_automation
>     if self.current_temperature <= self.target_temperature_low or (
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: '<=' not supported between instances of 'NoneType' and 'int'

I'm wondering if this is perhaps caused by the loading order of the integrations in Home Assistant. The Wiser integration loads before the Sonoff integration on my system - but the Sonoff is providing the hot water tank sensor value, so it's maybe not ready when the Wiser tries to query it.

I'm not familiar with a way to set the loading order or specify a dependency.

**Comment by msp1974** [comment]
Yes, we wait for HA to have started but it could be that some integrations also wait for HA to start before getting all their sensor values and then the first time the automation runs, it hasn't yet got a value.

We can add a fix to catch this and handle better.  thanks for raising.

**Comment by msp1974** [comment]
This should be resolved in v3.4.15 - just released

**Comment by kzipkzip** [comment]
Yes, no errors on startup now. Thanks! 😊
