### ISSUE TITLE
Error when trying to activate passive mode

### ISSUE THREAD

**Issue by RN-Say** [asantaga/wiserHomeAssistantPlatform#544]
When I try to activate passive mode in the integration configuration I am seeing the following error message briefly flash on the screen:

entity none is neither a valid entity ID nor a valid uuid for dictionary value @data ['hotwater_climate']['hotwater_sensor_entity_id']

**Comment by msp1974** [comment]
Does it activate passive mode or not?  ta

**Comment by msp1974** [comment]
As a workaround, select any entity in the Hot Water Temperature Sensor box and save it (without enabling 'Enable The CLimate Entity'.  This will aloow you to use passive mode.

**Comment by RN-Say** [comment]
> Does it activate passive mode or not? ta

No. The passive mode isn't activated.

**Comment by RN-Say** [comment]
> As a workaround, select any entity in the Hot Water Temperature Sensor box under Hot Water Climate Control and save it (without enabling 'Enable The Climate Entity'. This will aloow you to use passive mode.

This workaround worked. I now have passive mode activated. Thanks.

**Comment by RN-Say** [comment]
I think passive mode still isn't fully working, even though each room now has a passive mode switch. I've noticed that my thermostat cards don't show "passive mode" but rather look as though I might be able to cool the room with my radiator if passive mode is switched on for the room. Let me know if I have just missed something in the configuration.

![image](https://github.com/user-attachments/assets/0c58502e-4369-451e-bdc7-fdabf2f93fa5)

**Comment by msp1974** [comment]
No that is how it should look.  

The choices of colours are HA but it basically allows you to set the min temp for the room (where it will call for heat) and the max temp (which is the schedule temp in auto mode) which it will heat the room to (if something non passive is calling for heat).

**Comment by msp1974** [comment]
Fixed issue of not being able to activate passive mode in v3.4.15 - just released
