### ISSUE TITLE
Hot water temp_low not updated on first call

### ISSUE THREAD

**Issue by rnorth** [asantaga/wiserHomeAssistantPlatform#547]
I've been noticing a quirk for the last couple of days and have just had some time to confirm that it's easy to reproduce. _Background: I have a template sensor set up to calculate a desired hot water tank temperature over the course of the day, and a simple automation set up to call `climate.set_temperature` when it changes. Since the recent changes, I've changed the service call from providing one `target_temperature` field to a `target_temp_low` and `target_temp_high` field, each -/+ 0.5 from my desired temperature._

I've been noticing that while the climate controller's 'high' target temperature correctly follows desired state throughout the day, the 'low' temperature doesn't change without manual intervention.

* e.g. starting state, the hot water climate controller's target temp low/high are 35/36

* If an automation invokes, or I invoke manually:
```
action: climate.set_temperature
data:
  target_temp_high: 48.5
  target_temp_low: 47.5
target:
  entity_id: climate.wiser_hot_water
```

* following this, the target high temperature will be set to 48.5 but the low will remain 35
* if I then make the exact same `climate.set_temperature` call,
* following that, the target low temperature will update to 47.5

Note that the same is observed no matter the timing between the 1st and 2nd call - e.g. having the action duplicated in an automation shows the desired behaviour of setting both low and high targets. 

Also, having a bigger delta between the desired low/high temperatures doesn't seem to change the behaviour.

Looking at the code I can't see any obvious reason for this to happen, but it does seem repeatable so I thought I should report.
Thank you.

**Comment by msp1974** [comment]
This should now be fixed in v3.4.15 - just released.
