### ISSUE TITLE
R1.9 DEV wiser.get_schedule bug? 

### ISSUE THREAD

**Issue by Fulch** [asantaga/wiserHomeAssistantPlatform#57]
Noticed that the Get Schedule service is rounding all my temperatures to 0 dec places.

Monday:
  - Time: 07:30
    Temp: 16 ### should read 15.5
  - Time: 15:00
    Temp: 20 ### should read 19.5
  - Time: 21:15
    Temp: 20 ### should read 19.5
  - Time: 22:30
    Temp: 14 ### should read 14.5

Should line 46 in 'util.py' "value = round(value / 10)" be changed to "value = round(value / 10 , 1)"

Thanks to both  you and all the other contributors for making Wiser so much more useful!

**Comment by msp1974** [comment]
Yes it should.  Will correct. 
Does this functionality around schedules work for you?

**Comment by Fulch** [comment]
I think it provides more functionality than wiser's own app, the ability to copy schedules between rooms is a big plus.
Also provides the flexibility to switch between multiple schedules to suit different working patterns.
Previously I used the away mode but with what you have implemented I plan to automate switching the schedules instead.
Lastly backing up schedules in case of hub problems is another plus.

So in response to your question:  Yes it does and thank you for providing it!

**Comment by asantaga** [comment]
hey thanks Fulch for logging the issue , good to see that the functionality is useful!

@msp1974 : Given the amount of coding, and support, you are doing I thought it would be nice to allow u to be able to merge and collaborate properly :-)

**Comment by asantaga** [comment]
Closing this based on MR #58
