### ISSUE TITLE
Support for modes of operation

### ISSUE THREAD

**Issue by DrJohnT** [asantaga/wiserHomeAssistantPlatform#59]
Having taken a look at your excellent HA integration, I was wondering if it would support my use case.

My use case is as follows:

- When I work from home, I want to switch off all the radiators in the rest of the house apart from the study.
- When the family is at home, I want the whole house heated
- When my girlfriend is at home, only the bedroom needs heating, so switch off all the radiators in the rest of the house

So I need to be able to define "modes of operation".  I don't think this equates to zones, as the rooms overlap.

Right now I have a Salus iT500 system, but that is not properly integrated with HA, so I was thinking of buying a new heating controller and a bunch of TRVs

Does your HA extension support my use case?  (assuming I buy the Wiser kit).

**Comment by mrvladis** [comment]
@DrJohnT  I think your use case is fully supported by the current integration. However, you will need to configure automation yourself.

I personally use NodeRed for the automation flows. 

Nor sure about your house, but I personally didn't find it useful to switch the heating completely off within the none used rooms, as it will take a while to heat them back up. However, one of my automation routines that is triggered by the door / window open / close sensors, switch the heating off in the particular room if the one or more windows are open for more than 5 minutes.

For you geofencing scenarios - you will need to have a "tracker" configured in HA, so it can identify who is at home. I use life360. than you can have as many routines as you may like based on different scenarios.

**Comment by Fulch** [comment]
The wiser system supports the use of schedules for each room that has either a TRV or a Roomstat fitted.
A schedule consists of multiple time spans and temperature settings (including 'off') for each room and each day of the week.
Wiser's own implementation only allows for one schedule per room but with this integration you can create multiple schedules and switch between them based on your unique requirements.

This would totally cover your use case.

**Comment by DrJohnT** [comment]
You guys are awesome!  My Wiser kit is going to be ordered today!

**Comment by asantaga** [comment]
For the tracker I totally recommend the life360 integration, works a treat and integrates well with HA without opening ports on your FW..

thanks @Fulch @mrvladis for helping out.

@DrJohnT , When you have your kit all installed and working I think your automation it would be a great addition to the documentation as it would demonstrate the power of the HA integration vs the OOTB experience.

thanks!
