### ISSUE TITLE
SmartPlug :  Add Auto/Manual Mode Swtich

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#63]
within the smartplug data set the ManualState attribute is toggled to indicate manual or schedule mode

[
    {
        "id": 15,
        "ScheduleId": 2000,
        "ManualState": "Off",
        "Name": "Smartplug",
        "Mode": "Manual",
        "AwayAction": "Off",
        "OutputState": "Off",
        "ControlSource": "FromManualMode",
        "ScheduledState": "Off"
    }
]

Mode toggles from ```Manual``` to ```Auto```

**Enhancement**
Add controls to SmartPlug Implementation to cover this. Future Enh would be to set custom schedules using API (if people need it)

**Comment by asantaga** [comment]
Code implemented in wiser-heating-api and now partially implemented in R1.9Dev.

Need to implement a service to allow it to work

gotta go to bed now , so will do later this week.

**Comment by asantaga** [comment]
delayed due to weekend storm

**Comment by scooper1** [comment]
i hope not too much damage

**Comment by asantaga** [comment]
Hey @scooper1 , a few hangin tiles from the roof went awol and smashed into the lower kitchen pitch roof..
Ive fixed the pitch roof but getting someone out to fix the hanging tiles...

**Comment by asantaga** [comment]
This is now implemented in R1.9Dev

Also implemented service to set the "Mode" of the smartplug, The service payload is

```
entity_id :  switch.smartplugName 
plug_mode : Auto
```

There's a bug affecting all services where the documentation isnt showing.... logging a separate one for this
