### ISSUE TITLE
New Services (set/get schedule and set switch mode) dont show service data wizard properly or documentation from service.yaml

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#66]
Whilst implementing the set smartplug mode functionality I noticed that all the services we've built dont show the 

entity pull down and the documentation it the developer tools..

Ive looked at it and have no idea why..

@msp1974  Any ideas?

**Comment by Fulch** [comment]
I had this problem also and fixed it by changing Services.yaml:
https://github.com/asantaga/wiserHomeAssistantPlatform/blob/8adb4658505d88a50e4cba0461b2ae36fc28e326/custom_components/wiser/services.yaml#L72

To read as below: 

`
description: Enter the mode Auto,Manual.,
`

Remove square brackets and add missing full stop. Square brackets don't seem valid in this context.

**Comment by msp1974** [comment]
@asantaga , will have a look tonight or tomorrow. Away for weekend.

**Comment by asantaga** [comment]
Fixed in commit , thanks @Fulch !

https://github.com/asantaga/wiserHomeAssistantPlatform/commit/838034bec46462eb7a0e1ba5379d630074b6c988

**Comment by asantaga** [comment]
@msp1974  My turn!!! Enjoy the "wet" weekend away :-)
