### ISSUE TITLE
Enh : Add Mesh details showing nodeId and parentNodeId

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#67]
Within the devices payload there are two elements
NodeId and ParentNodeId

For TRVs and RoomStats 

- If parentNodeId == 0 then the connection to the hub is direct
- If parentNodeId  !=0 then the connection to the hub is via a SmartPlug/Range Extender whos Id is parentNodeId

Adding this to the iTRV and RoomStat data payloads as rawdata
Also adding a computed attribute called "HubConnection" which will be either
- Direct
- <Name of SmartPlug>

This is really useful to know when diagnosing/mapping how you trvs are communicating to the wiser hub..

Fab, really well thought out system this wiser stuff is..

**Comment by scooper1** [comment]
Good idea   
Helps in knowing if extender is helping Should this be applied  to plug extender as well so you know if extender is getting data via another extender ?


Sent from Yahoo Mail on Android 
 
  On Mon, 17 Feb 2020 at 10:37, Angelo Santagata<notifications@github.com> wrote:   
Within the devices payload there are two elements
NodeId and ParentNodeId

For TRVs and RoomStats
   
   - If parentNodeId == 0 then the connection to the hub is direct
   - If parentNodeId !=0 then the connection to the hub is via a SmartPlug/Range Extender whos Id is parentNodeId

Adding this to the iTRV and RoomStat data payloads as rawdata
Also adding a computed attribute called "HubConnection" which will be either
   
   - Direct
   - 

This is really useful to know when diagnosing/mapping how you trvs are communicating to the wiser hub..

Fab, really well thought out system this wiser stuff is..

**Comment by asantaga** [comment]
Precisely what I wanted to find out :-) 

I also found out if the battery level is <26 then its time to replace the batteries.. Whilst they show as "good" on a battery tester , there isnt enough juice to turn the actuator in the valve...

I may add that as an additional attribute

how does
```
 attribute name : replace_batteries : true or false 
```
Sound?

**Comment by scooper1** [comment]
Seams a good ideaI have a lovelace page showing battery status 
Maybe a bit high for RoomStat
Might be good idea to have a defaulted config value   one for trv battery minimum level and one for roomstat

Sent from Yahoo Mail on Android 
 
  On Mon, 17 Feb 2020 at 11:58, Angelo Santagata<notifications@github.com> wrote:   
Precisely what I wanted to find out :-)

I also found out if the battery level is <26 then its time to replace the batteries.. Whilst they show as "good" on a battery tester , there isnt enough juice to turn the actuator in the valve...

I may add that as an additional attribute

how does
 attribute name : replace_batteries : true or false 

Sound?

**Comment by scooper1** [comment]
The  battery  levels might different depending on the battery type so a config level would be good for that as well

Sent from Yahoo Mail on Android 
 
  On Mon, 17 Feb 2020 at 11:58, Angelo Santagata<notifications@github.com> wrote:   
Precisely what I wanted to find out :-)

I also found out if the battery level is <26 then its time to replace the batteries.. Whilst they show as "good" on a battery tester , there isnt enough juice to turn the actuator in the valve...

I may add that as an additional attribute

how does
 attribute name : replace_batteries : true or false 

Sound?

**Comment by Fulch** [comment]
` "Zigbee": {
        "NetworkChannel": 25,`

Could be a useful attribute to display under WiserHub data? It might help people with connectivity problems to at least know what Zigbee channel is being used and maybe then change their Wifi channel or any other Zigbee devices to minimise potential interference.

I don't know if the NetworkChannel is read only and have not been brave enough to try changing it!
The link below explains about the channel overlap between Zigbee and Wifi.

[https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence](url)

**Comment by asantaga** [comment]
Cool,

I'll be implementing this either tonight or tomorrow and I want to get R1.9 out soon.

SoI plan to expose :

```node_id : {number}
parent_node_id : {number}
zigbee_network_channel : {number}
replace_batteries  : {true | false}   , will be based on a config variable (default of 26) value<config then returns true
```

Two config variables
```replace_trv_batteries_threshold : {number default 26}
replace_roomstat_batteries_threshold: {number default 20}
```

I wont make the zigbee value read/write, too intrusive..
Will do this tonight, shouldnt take more than 1hr..

**Comment by scooper1** [comment]
Should the node Id be exposed on all devices  so can workout who is the parent Id related to 
Would be very nice to have 1.9 out  so many changes have happened 

Sent from Yahoo Mail on Android 
 
  On Wed, 19 Feb 2020 at 11:57, Angelo Santagata<notifications@github.com> wrote:   
Cool,

I'll be implementing this either tonight or tomorrow and I want to get R1.9 out soon.

SoI plan to expose :
parent_node_id : {number}
zigbee_network_channel : {number}
replace_batteries  : {true | false}   , will be based on a config variable (default of 26) value<config then returns true

Two config variables
replace_roomstat_batteries_threshold: {number default 20}

I wont make the zigbee value read/write, too intrusive..
Will do this tonight, shouldnt take more than 1hr..

**Comment by asantaga** [comment]
yes the node_id will be exposed, it was in the text but I had a markdown error.. so it wasnt showing, fixed that.

**Comment by asantaga** [comment]
Done, commit 92f7d68

Added the zigbee channel data to the heathub sensor
Added Zigbee nodeId,parentNodeId and calculated field `hub_route` to iTRV and RoomStats

DID NOT add the battery threshold figures because I noticed there was a field called `BatteryLevel` which when goes to OneThird pretty much says the same thing..

I also noticed that not all iTRVs have battery data in the raw payload.. dont know why.. may be it appears after a while..
