### ISSUE TITLE
HA won't restart after enabling config

### ISSUE THREAD

**Issue by Puntoboy** [asantaga/wiserHomeAssistantPlatform#68]
Installed the component as per the instructions. Added the config to the YAML and rebooted. Couldn't reconnect to HA. Had to physically reboot the server.

HA came back but there are no devices/entities listed. Can't find anything for Wiser. Nothing in the logs points to an issue.

**Comment by asantaga** [comment]
Hey Puntoboy, 

Just curious what was the issue? We're getting ready to release 1.9 to HACS and I was thinking of adding a troubleshooting section.

**Comment by Puntoboy** [comment]
I suddenly saw them, but only when I search for them in /developer-tools/state. They don't appear as entities in the main menu.

The reboot issue still exists, but I'm not sure if this is HACS or Wiser as they were both installed around the same time.
