### ISSUE TITLE
Info Only : Hub doesnt report all devices battery data for a period of time after reboot

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#69]
Whilst testing I noticed that the TRVs/RoomStats dont show the battery data all the time.

I rebooted my hub and then I noticed that only 2/10 devices where reporting battery levels. In this case the code doesnt show anything...

After a while the battery level appears but I dont think HA will see it because the devices arent recreated on each interval..

I'll think of a workaround for this, but logging this as a "FYI"

**Comment by msp1974** [comment]
I've seen in some other integrations that if new devices are discovered that these will get added without a restart.  I will look into this some more to see if a similar approach can be used here where attributes get added if they appear.

**Comment by asantaga** [comment]
@msp1974 , in this case it isnt an issue because these are attributes within the sensors.. but be nice to be able to "refresh" the sensors/climate devices etc periodically..

Leaving open for now, but this isnt high priority..

**Comment by asantaga** [comment]
actually closing, its logged here for all to see (if they search)
