### ISSUE TITLE
HomeAssistant Packaging

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#7]
Once we have stability the following needs to be done to be able to package up as part of HA

- WiserAPI needs to be deployed to Pypi
- Requirements and dependencies set
- Check for HA coding standards adherance

**Comment by jchasey** [comment]
In the meantime can support for custom component card be added?

**Comment by asantaga** [comment]
hey @jchasey please log a seperate issue/ER for the custom component card.. I'll look at that after

Currently working on a separate branch MigrateToPipWiserApi where I plan to migrate the code to use pypi package and then eventually publish on ha website

**Comment by asantaga** [comment]
Wiserhub code published to PyPi (https://github.com/asantaga/wiserHomeAssistantPlatform/issues/24) and https://pypi.org/project/wiser-heating-api/

**Comment by asantaga** [comment]
Still working on it in UseNewPyPi branch. PLan is to get it working with the new component layout and use library in pypi then push it along

**Comment by asantaga** [comment]
guys,

Im prepping the package for inclusion into Home Assistant. To this end Ive got he main wiserHub package now on PyPi and reformatting code etc so that it conforms to HA standards. Can someone please give it a whirl and see if its all ok?

its on dev branch "UseNewPyPi" so to get to it use 

```
git clone git@github.com:asantaga/wiserHomeAssistantPlatform.git
git checkout 
```

The rest is the same as before

**Comment by asantaga** [comment]
Partially done in R1.4.

**Comment by asantaga** [comment]
if anyone wants to help, let me know.. Im a bit baffled at how to do the documentation 
at the moment..

**Comment by asantaga** [comment]
@michthom 

Hey there, thanks for offering to assist here.
From what I know that needs doing

- [ ] 1. Code reformatting to conform to HA Standards
- [ ] 2. Documentation , havent quite worked out how that works with HA

Can u help here, especially with the latter?

**Comment by michthom** [comment]
> * [ ]  1. Code reformatting to conform to HA Standards
> * [ ]  2. Documentation , havent quite worked out how that works with HA
> Can u help here, especially with the latter?

Hopefully my pull request #47 will help a bit with part 1, and as for part 2, I think I'd need a bit more context - your readme is pretty good already I think. What are you least happy with, and I'll take that as a starting point? Or is there an "expected" format / Wiki entry required as part of the HA submission? If there's a link to that drop a link in here and I'll do some reading.

**Comment by asantaga** [comment]
thanks, I'll find some time soon to merge the PR and go through the coding standards things.. some are really archaine.. like no lines can be longer than 78characters....

**Comment by asantaga** [comment]
```[edit2] I've created a fork of the homeassistant.io repo, and added a Wiser logo and an integration page. Let me know if you're happy with the wording so far?
```
looks good..

**Comment by michthom** [comment]
> the coding standards things.. some are really archaine.. like no lines can be longer than 78characters....

When I ran the 'black' tool against your original code, I told it to shorten to no longer than 80 characters, but where did you see the 78 character restriction? I had a look [here](https://developers.home-assistant.io/docs/en/development_checklist.html) and [here](https://developers.home-assistant.io/blog/2019/07/31/black.html) but didn't see that mentioned?

**Comment by asantaga** [comment]
must have been an old thing, or I got mistaken... all good though.

**Comment by michthom** [comment]
Hi Angelo. I got some help from @balloob on Discord with my confusion about the category pages not picking up the new documentation pages, but having saved a change to /source/integrations/index.html they did update, so I've incremented the release to 0.105 and updated my fork of the HA repo. I'm assuming you'd prefer to clone my repo and then create a pull request for HA to pull from you direct?

**Comment by asantaga** [comment]
thanks Michthom, I'll do the merging this weekend...

>  I'm assuming you'd prefer to clone my repo and then create a pull request for HA to pull from you direct?

That would make sense, we need to tweak the main code a bit (I think) then we can submit it

**Comment by asantaga** [comment]
@michthom ,

I didnt get to it this weekend but yes I'll clone your repo then create the HA PR from there.. Appreciate all the work youve done and credit will be where credit is deserved.

**Comment by asantaga** [comment]
Ive paused this for a bit as we're (msp1974 ) has rewritten chunks of the code using async calls instead of sync calls. Need to test this, merge it in and then use black tool against his code (I dont think he started with the black tool PR)

**Comment by asantaga** [comment]
@michthom , I'll clone your HA repo later today so we can at least get the docs stuff ready for when we finish the work msp1974 is doing.

**Comment by asantaga** [comment]
R1.9 is nearly done, once this is done I'll work on this ticket..

**Comment by asantaga** [comment]
will do this for 2.0

**Comment by asantaga** [comment]
Closing this one for now
