### ISSUE TITLE
None Exception when there are no smartplugs

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#71]
from 
https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/53

Duke_box
Mike
2h
Hi Angelo,

I have re-installed twice now as Fulch suggested but still do not have the switch.
I have an error:

Mon Feb 24 2020 12:59:14 GMT+0000 (Greenwich Mean Time) Error while setting up wiser platform for switch Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT) File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for return fut.result() File "/config/custom_components/wiser/switch.py", line 45, in async_setup_platform WiserSmartPlug(hass, data, plug.get("id"), plug.get("Name")) for plug in data.wiserhub.getSmartPlugs() TypeError: 'NoneType' object is not iterable

Any help appreciated.
Thanks

**Comment by scooper1** [comment]
Did you setup  plug in the wiser app and assign it to a room 


Sent from Yahoo Mail on Android 
 
  On Mon, 24 Feb 2020 at 15:21, Angelo Santagata<notifications@github.com> wrote:   
from
https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/53

Duke_box
Mike
2h
Hi Angelo,

I have re-installed twice now as Fulch suggested but still do not have the switch.
I have an error:

Mon Feb 24 2020 12:59:14 GMT+0000 (Greenwich Mean Time) Error while setting up wiser platform for switch Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT) File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for return fut.result() File "/config/custom_components/wiser/switch.py", line 45, in async_setup_platform WiserSmartPlug(hass, data, plug.get("id"), plug.get("Name")) for plug in data.wiserhub.getSmartPlugs() TypeError: 'NoneType' object is not iterable

Any help appreciated.
Thanks

**Comment by asantaga** [comment]
Fixed in dev branch, just waiting to hear that it works. The code "assumed" you had smartplugs which was .. an assumption :-)

**Comment by asantaga** [comment]
fixed and released in R1.9.1

**Comment by djashjones** [comment]
I still get this error using R1.9.1

**Comment by asantaga** [comment]
@djashjones  

Hey I just checked the code on github and master does have the fix so this must be another error.. 

Can you try. deinstalling (removing the wiser directory from custom_components) and then reinstalling? Providing you dont remove the setup from the configuration.yaml you wont loose anything...

Let me know

Reopening this issue till we resolve this

**Comment by djashjones** [comment]
That fixed it. Also my away button came back and a few more services are available now. You can close it again, sorry.

What caused the issue when upgrading?

**Comment by asantaga** [comment]
No idea.. Ive seen it sometimes that the HACS upgrade process doesnt work properly... No idea, it might be my amateurish management of the git releases its based on .. not sure..

glad its fixed, for a while I thought Id have to release another version (1.9.2), which just screams DAMM Angelo test test test test :-)

thanks for letting me know
