### ISSUE TITLE
wiser.get_schedule not writing schedule to file 

### ISSUE THREAD

**Issue by naylogj** [asantaga/wiserHomeAssistantPlatform#76]
hi,  first - thanks for v1.9 a great release - I have tweeted and post in the HA Facebook group about it.  @gjna 

wiser.get_schedule service call is not writing any data out to a file.  this is what I am calling from the Developer/Services page of Home Assistant Core (v 0.106.6) running on Docker on Mint
Service being called:  wiser.get_schedule   - picked from list.  The entity below is also picked from drop down list.

entity_id: climate.wiser_lounge
filename: schedule1.yaml

No schedule1.yaml file is created.

I have also tried with an empty schedule1.yaml file in place with rw-rw-rw- permissions before calling the service.  Still no data written.

For info, here is my docker-compose file:
<code>
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /home/haconfig:/config
    environment:
      - TZ=London/Europe
    restart: always
    network_mode: host
</code>

no data is written to /home/haconfig

There are no errors for today's date in the Home Assistant Core error log.

Am I doing something wrong?

**Comment by truxntrax** [comment]
Exactly the same issue, but not using docker.  Home assistant installed in a python venv (ubuntu 16).  Installed: R1.9.1.
John

**Comment by asantaga** [comment]
mmmm any errors?

**Comment by asantaga** [comment]
I had a quick test and then remembered what it is.. If you dont provide a path to the filename it will be written to the directory where home assistant is run from..  

in my case I run HA from a venv in testing and its the directory where I run `hass --open-ui -c ./config`

try putting an absolute path, like `/tmp/room1.yaml` , this will prove out this theory

**Comment by naylogj** [comment]
Hi.  Your suggestion did not work, but I got it to work and can explain.
You are correct, you need an absolute path, i.e. /dir/dir1/filename.yaml etc.

However as I am running HA core in docker, the absolute path has to be one docker understands.

So if I specify:

filename: /config/shedule.yaml 

then get_schedule writes the file.

outside of the docker container i can then read this file at /home/haconfig/schedule.yaml

as per the docker compose file   volumes: - /home/haconfig:/config

so this is not a bug.  perhaps an update to README.md to explain this behaviour and and extra text in services.yaml?

thanks 
Gareth

**Comment by asantaga** [comment]
updated readme.md & services.yaml, thanks
