### ISSUE TITLE
Hot water schedule editing support

### ISSUE THREAD

**Issue by m01** [asantaga/wiserHomeAssistantPlatform#80]
Feature request: it'd be nice if this home assistant integration supported editing the hot water schedule as well.
Similarly to rooms, there's a `/domain/HotWater` bit, which has a `ScheduleId` referencing one of the schedules under `/domain/Schedule`. The schedule structure is the same structure as for rooms, except `Type` is set to `HotWater` and it has different values for `DegreesC`.

**Comment by asantaga** [comment]
ok , we'll do that next..

**Comment by msp1974** [comment]
Happy to take this one on if that helps.

**Comment by msp1974** [comment]
With all this lack of anything to do, seems I have much time for coding.  Been having a think about this one and would welcome thoughts on best way forward.

### Option 1
Use the same wiser.get/set/copy_schedule services to be able to use this for heating and smartplugs (they have schedule too)

**Pros**

- Keeps it simple for the user with one service and then select the entity you wish to do for.

**Cons**

- What entity would you select for hotwater schedule?  We only really have a status sensor and the set_hotwater_mode doesn't need an entity so could be confusing.
- Api will need updating to allow schedules to be get/set/copy by schedule id as well as room
- The service is defined in the climate sensor.  Will need significant change to move these to integration level so can be used across multiple entity types.


### Option 2
Create another 3 (get/set/copy) services for hotwater schedule and another 3 for smartplugs

**Pros**

- Simplifies change needed to implement
- Won't need an entity to be selected for hotwater (as per set_hotwater_mode service) so consistent

**Cons**

- There will be 9 services relating to schedules (bit messy in the list)
- Will need to rename existing schedule services to make clear they are for rooms (breaking change)

### Option 3
Relook at the water heater component to see if we can make this fit.

Pros

- We will have an obvious entity to use for hotwater services
- It already has built in functions for setting operation mode and we can add boosting in the same way that it works for climate sensors

Cons

- Will still need separate services for get/set/copy schedules - so still 9 as per option 2
- It looks like a climate sensor with set temp - can you even set temp on Wiser hotwater? Could we find a work around for this?

Welcome views on best way forward.

**Comment by msp1974** [comment]
Just as an update as this issue has been open a while. I am now working on this and should have in a week or so.

**Comment by wizmo2** [comment]
> Just as an update as this issue has been open a while. I am now working on this and should have in a week or so.

msp1974, I've just implemented and tested the hotwater schedule.  Let me know if you want me to share

**Comment by msp1974** [comment]
Thats great and thank you for sharing. I was looking to do it a similar way as you have so this is really helpful. Also planning to add ability to get and set schedules for smartplugs.

Will get you to help test it when done if that is ok?

**Comment by wizmo2** [comment]
No problem.  Don't have smartplugs as yet, but need to add in the near future, and will need scheduling support.

**Comment by msp1974** [comment]
Angelo, hope you're getting on well with the new baby. As your looking at github, could you see pull request for api so that we can update the integration to allow setting schedules for hot water and smartplugs. The update for the i tegration is in the dev branch but it needs an api update to support.  Thx

**Comment by msp1974** [comment]
Ok, Angelo managed to find some time to update the wiser heating api on pypi over the weekend.  Will be doing some testing and updating the doca this week.  Hope to publish by end of week.

**Comment by msp1974** [comment]
Ok, tonight I have just released v2.4beta3.  It is a pre-release so you will need to enable beta releases in HACs to be able to use it.  This includes long awaited functionality to be able to use the schedule management services for hot water and smartplugs.

I have also updated the readme to give instructions on how to use the updated capabilities.

@wizmo2 would be grateful if you could read instructions, test and provide feedback as to whether it a) works without error and b) does it make sense as to how it works and the instructions are clear.
 Thanks

**Comment by wizmo2** [comment]
@msp1974, Tested on on my developer docker rig (dev/0.119), and now have it running on my active RPI3 HassOS (4.11/0.112.4) for longer term tests.   Not seen any errors except the usual timeout and unknown connection errors.  Have verified heating and hotwater functionality.  Will not be able to test smartplugs until the end of this month (hopefully).  I'll try some stress testing later this week and will let you know if anything serious comes up.

Readme looks OK.  Would suggest you update the descriptions on the set and get schedules services in the yaml, re. entity_id use.

**Comment by asantaga** [comment]
closing as fixed.
