### ISSUE TITLE
Wiser Smartplugs no longer follow the standard of calling themselves "Wiser <smartplugname>"

### ISSUE THREAD

**Issue by asantaga** [asantaga/wiserHomeAssistantPlatform#88]
As above, may have broken some integrations

**Comment by asantaga** [comment]
Fixed in commit dev bf461ed, waiting for confirmation this fixed it

**Comment by asantaga** [comment]
Fixed

**Comment by asantaga** [comment]
not fixed....See https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/80

**Comment by msp1974** [comment]
The name if this will be different based on what you have called your switch when you installed it. I guess yours is call smartplug and the other guys wiser_switch. Mine is called wiser plug 1 so my sensor/switch is called sensor.wiser_plug_1.  Slightly different from how TRVs are named as when setup i guess they were just given the name of the room without wiser in the name.  Not sure prefixing wiser is a good idea, just rename the plug in app or accept how its named.

**Comment by asantaga** [comment]
I think this is actually fixed.. Everything in my install (using dev branch now) is called "wiser_"+device name...
