### ISSUE TITLE
Wiser custom-compenent not found in version 0.84.3

### ISSUE THREAD

**Issue by v966732** [asantaga/wiserHomeAssistantPlatform#9]
I'm unable to get Wiser to show up, I get the error that the wiser component could not be found.  It's in the same custom_components folder as my other components that are still working.

**Comment by asantaga** [comment]
mmmm strange.. 

Bit heavy handed but clone the entire git repo into your custom components so that the readme.md is in the custom components.. that should work..

let me know , I'll upgrade my HA to 0.84.3 tonight to see if this is a HA 0.84.3 issue

**Comment by v966732** [comment]
Thank-you, that got it working.  All looks good, will keep testing it

**Comment by asantaga** [comment]
awesome
