### ISSUE TITLE
Wiser rooms do not stay set to off

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#95]
Don't think this is an integration issue but wondering if anyone else has seen this issue.

As the warmer weather has come, I have set some of my rooms to off (as I haven't got around to creating a summer schedule yet).  However, (and I thought I was going mad at first) I keep noticing that the next day, some of the rooms are set to manual heat with a temp higher than the away set temp but not all.

It looks (from yesterday) that this happened at 11:26.  Has anyone else seen this behaviour with their hub?

**Comment by scooper1** [comment]
Yep that happens It is not a new problemI think it may be more to do with wiser cloud implementationI set mine to heat and set a 10c trigger level.  Check back a hour later and reset any that have not taken  it can take up to 5 tries to doI believe it happens at schedule switching times.  Wiser hub over rides off to next schedule time  ie  off  more like a anti boost function On 15 Apr 2020 12:04, Mark Parker <notifications@github.com> wrote:
Don't think this is an integration issue but wondering if anyone else has seen this issue.
As the warmer weather has come, I have set some of my rooms to off (as I haven't got around to creating a summer schedule yet).  However, (and I thought I was going mad at first) I keep noticing that the next day, some of the rooms are set to manual heat with a temp higher than the away set temp but not all.
It looks (from yesterday) that this happened at 11:26.  Has anyone else seen this behaviour with their hub?

**Comment by asantaga** [comment]
im not seeing this.. I have a front room which is set to off and its still off.. 

I did notice something similar to this when the battery was low.. but more like the rad was heating and reporting back the temp..

**Comment by msp1974** [comment]
I'm seeing both somehow.  I have some that just show off and some that show off- override.  Was going to have a look at this too to see if we should cancel any override first.  Have got 5 showing off and 3 showing off - override.  Will see what happens to these later.

**Comment by asantaga** [comment]
![image](https://user-images.githubusercontent.com/2940224/79339124-4dd97780-7f20-11ea-9d45-38ca1f9343fc.png)
dummy is a dummy room which I use for testing...

**Comment by msp1974** [comment]
Finding if you set of off, it is now more often than not going to off - override.  However, if you go to manual mode, change temp and then set to off, it is always off (if you don't change temp then goes to override too).  Wonder if we should do a 2 step process to turn off.  1: to set to manual mode 2: set temp to -200.

Having said this, still haven't worked out if it is just these ones that say off - override that are going back to manual mode or a random selection.  Will report back over next 24 hours if I can work it out.

**Comment by scooper1** [comment]
I just had one room to heat at 12C  and checked ok after 2 hours  4 days later it went to heat 21c  6

Sent from Mail for Windows 10

**Comment by asantaga** [comment]
actually yeah, both of the rads I set to off using HA are now back on , so yeah the turning off isnt working :-) and :-(

We'll work it out... we always do!

**Comment by djashjones** [comment]
I've noticed that one of my TRV's for the past couple of days comes on when the heating does and it's schedule is pretty much off i.e. set to 14 degrees but my other TRVs are fine for some reason.

**Comment by m01** [comment]
I've noticed this issue as well, but generally it only happens once, i.e. the turning off works the 2nd time.
Just a totally random guess, but I wonder if it's something frost-protection related. I've noticed that if you set the room stat to 5°C it has the same white circle as off, but I vaguely remember the minimum temperature in the home-assistant integration being 15 or so...
I don't currently have any TRVs in case it makes a difference.

**Comment by msp1974** [comment]
PR for the api posted that I think fixes this

**Comment by asantaga** [comment]
Needs testing.. will add to readme

**Comment by msp1974** [comment]
@asantaga just to make sure you haven't missed the PR for the wiser-heating-api that needs to be merged to fix this issue.  Best to do with 2.3 release I think.

**Comment by asantaga** [comment]
Hey mark, I think this PR is in 2.3.1 right?

**Comment by msp1974** [comment]
No. The fix for this is actually an update to the api not the HA integration. The PR is still open for the api.

**Comment by asantaga** [comment]
PR Merged into a new wisehubapi, 1.0.8 .. 

I need to think how to document how to force an API upgrade as I dont think HA automatically does it on boot

**Comment by msp1974** [comment]
don't you just update the version in manifest.json and issue a new release?

**Comment by asantaga** [comment]
yup, but i hate to create new releases just to force a library update.. although thats what Im going to do later tonight..

**Comment by msp1974** [comment]
True but ive seen lots of integrations do a version update just to upgrade the library its using so wouldnt worry.

**Comment by asantaga** [comment]
Will release this with 0.110 compatible release

**Comment by asantaga** [comment]
fixed, and tested
