### ISSUE TITLE
Climate graph is not showing the real state

### ISSUE THREAD

**Issue by thecem** [asantaga/wiserHomeAssistantPlatform#98]
Hi thanks for the nice integration!
Is it possible to show in climate log graph the right status (green filling) only when the heathub is heating?

![495D2252-D87D-4943-9248-D001AB433070](https://user-images.githubusercontent.com/46648579/80714671-85861900-8af5-11ea-87d5-64b1783d1a15.jpeg)

Right now it shows the status of the heating (hvac) mode.

Like this:

![AD506B44-6AFE-4A5E-A0C8-022FF2ADB329](https://user-images.githubusercontent.com/46648579/80715200-50c69180-8af6-11ea-88b2-155ad05180a4.jpeg)

**Comment by asantaga** [comment]
@thecem  Mark (@msp1974 ) has fixed this in PR#99, can you please check/test before I merge it to master?


You can test it easily by replacing `climate.py` with this one from the dev branch https://github.com/asantaga/wiserHomeAssistantPlatform/blob/dev/custom_components/wiser/climate.py

(obviously make a backup)

Let me know if it works ok, if its all good then I'll merge the dev branch to master and create a new release for all.

**Comment by thecem** [comment]
I have tested it and it works! Great. Up to know there is only a smal peek in the graph. I will send a picture after a few hours, to see if it is only green in case of heating.

**Comment by thecem** [comment]
![grafik](https://user-images.githubusercontent.com/46648579/80949109-a7ccaf00-8df3-11ea-8234-fe03a61028e8.png)
Added the patch at 09:58 so it is ok!

Thanks a lot.

**Comment by asantaga** [comment]
Nice :-)

Closing
